conda-forge/admin-requests

pkgs/abseil-cpp-20200225.txt

See https://github.com/conda-forge/abseil-cpp-feedstock/issues/8
cc @pitrou

Mark abseil-cpp-20200225 as broken

---

mark_broken.py

Just a workaround for https://github.com/conda-forge/cf-mark-broken/pull/28#issuecomment-603313046. 
cc: @isuruf

Ignore blank lines or Python-style comments

---

pkgs/python_osx.txt

cc @conda-forge/python 
xref: https://github.com/conda-forge/python-feedstock/issues/339

ENH mark osx build of python broken due to extra files

---

pkgs/ipyleaflet

Checklist:
Fixes https://github.com/conda-forge/ipyleaflet-feedstock/issues/85
Ping @conda-forge/ipyleaflet

Mark ipyleaflet 0.12.5 as broken

---

pkgs/sphinx.txt

Remove broken Sphinxdft version

---

pkgs/r-base-4.txt

Checklist:
ping @conda-forge/r 
Will open and issue and add here

mark R4 broken for ppc64le

---

pkgs/rbdl-feedstock.txt

remove rbdl extra package

---

.github/workflows/master.yml
mark_broken.py

ENH move labels and trigger build

---

pkgs/sysroot.txt

ENH the other sysroot

---

pkgs/aiida-core.services.txt

fixes https://github.com/conda-forge/aiida-core-feedstock/issues/32
ping @conda-forge/aiida-core
Checklist:
<!--
--!>

Mark aiida-core.services=1.2.1=0 as broken

---

pkgs/pytest-executable.txt

mark bad pytest-executable

---

pkgs/sysroot.txt

[DO NOT MERGE] ENH mark more bad symlink sysroots as broken

---

broken/broken.txt

Closes https://github.com/conda-forge/pyqt-feedstock/issues/82
@isuruf can you check if I got the right ones here please?

mark pyqt 5.12.3 build 2 and 3 as broken

---

broken/broken.txt

Ping @isuruf 
Closes https://github.com/conda-forge/sip-feedstock/issues/28

mark sip 4.19.23 and 4.19.22 as broken

---

broken/broken.txt

mark sip 4.19.24 as broken on win

---

broken/example.txt
broken/gfortran.txt
not_broken/example.txt

cc @beckermr 
see https://github.com/conda-forge/gfortran_impl_osx-64-feedstock/issues/24

mark latest gfortran as broken

---

broken/pypy_ppc.txt

See https://github.com/conda-forge/pypy3.6-feedstock/issues/28
cc @conda-forge/pypy3-6

Mark latest pypy ppc build as broken

---

broken/broken.txt

Mark python 3.9 pre-release as broken

---

broken/broken.txt

This package passed the CIs for py39 but it is actually failing a fill test suit upstream. Pinging @jkochNU.

remove scqubits

---

broken/singularity.txt

Mark singularity 3.6.4 as broken

---

broken/pdpipe.txt

Remove pdpipe v0.0.521

---

.github/auto-merge.yml

Moving this to github automerge.

REF use github automerge

---

broken/xeus-sql.txt

cc @marimeireles @wolfv 
cf. https://github.com/conda-forge/xeus-sql-feedstock/issues/3

Mark xeus-sql 0.0.8 as broken

---

broken/broken.txt

Fix https://github.com/conda-forge/basemap-feedstock/issues/74

remove basemap build number 4

---

.github/workflows/master.yml
.github/workflows/pr.yml
README.md
environment.yml
token_reset.py
token_reset/example.txt
token_reset/test.txt

This PR adds token resets.
cc @isuruf

WIP add token reset

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/master.yml
token_reset/test.txt

TST final test for token reset

---

token_reset/torchvision.txt

For https://github.com/conda-forge/torchvision-feedstock/issues/15

reset token for torchvision

---

broken/crossenv.txt

Mark crossenv=1.1.0 as broken

---

broken/freeimage.txt

https://github.com/conda-forge/freeimage-feedstock/issues/25

mark latest win-64 freeimage build as broken

---

broken/matplotlib.txt

See https://github.com/conda-forge/matplotlib-feedstock/pull/292#issuecomment-809887448

remove mpl 3.4.0

---

broken/pypardiso.txt

Mark pypardiso as broken

---

broken/gitpython.txt

Hopefully we won't break anything that depends on the 3.1.19 version :smile:

both 3.1.19 and 3.1.20 got yanked from PyPI

---

broken/hdmf.txt

I am one of the maintainers of the HDMF package. We released HDMF 2.5.0 yesterday with a breaking change. We reverted that breaking change and made a patch release as HDMF 2.5.1 today. We would like to mark 2.5.0 as broken.
Changelog: https://github.com/hdmf-dev/hdmf/blob/dev/CHANGELOG.md
hdmf feedstock: https://github.com/conda-forge/hdmf-feedstock/
ping @conda-forge/hdmf …

Mark hdmf==2.5.0 as broken

---

.github/workflows/master.yml
token_reset.py

This PR moves the repo to use an app token.

ENH move to app tokens

---

broken/test.txt

ENH test broken

---

token_reset.py
token_reset/test.txt

ENH test token reset

---

broken/openff-interchange.txt

Mark rc build of openff-interchange on main label as broken

---

.github/workflows/master.yml
.github/workflows/pr.yml

ENH master to main

---

broken/jupyter-sysml-kernel.txt

Kindly requesting removal of alpha (only used for internally testing; has not been distributed/publicized) packages of jupyter-sysml-kernel - ref: https://github.com/conda-forge/jupyter-sysml-kernel-feedstock. These alpha packages were unfortunately published with calendar versioning, e.g. `2021.05a`. This has been corrected with the first non-alpha being published as `0.14.1`, but because of semver rules `2021.05a` still shows up as the latest and default version for the package which is problematic for installing users.
* …

Remove alpha packages for jupyter-sysml-kernel

---

broken/gitpython.txt

See https://github.com/conda-forge/gitpython-feedstock/issues/58
Pinging  @xylar.

needs a py>36 selector

---

token_reset/termcolor-cpp

Request token reset for `termcolor-cpp`

---

mark_broken.py

BUG fix commit message

---

token_reset/opentelemetry-exporter-jaeger.txt
token_reset/opentelemetry-exporter-oltp.txt
token_reset/opentelemetry-exporter-otlp-proto-grpc.txt
token_reset/opentelemetry-exporter-otlp.txt
token_reset/opentelemetry-instrumentation-grpc.txt
token_reset/opentelemetry-proto.txt

Opentelemetry-token-reset

---

broken/remove_openglider.txt

version scheme has changed. 0.0x -> 0.0.x …

remove some old openglider packages

---

broken/yaml.txt

bad yaml .so

---

broken/edgetest-hub.txt

Hi @conda-forge/core team. I'd like to mark the edgetest-hub package as broken as we've had to remove it from PyPi and GitHub due to some info being captured in the source code which shouldn't be there. (Happy to explain further via chat or email). I'm hoping to get the releases off the channel until we can refactor/fix it and re-publish it.
* Packages with missing metadata can be marked as …

edgetest-hub broken

---

broken/vc.txt

remove vc wrong version

---

broken/ryven.txt

The package `ryven-3.1.1-pyhd8ed1ab_3.tar.bz2` works fine after restricting the pyside2 dependency https://github.com/leon-thomm/Ryven/issues/90 . So it would be great to remove the previous builds. Cc: @leon-thomm
* In some cases where the number …

Remove broken ryven packages

---

mark_broken.py

This PR adds support for `.conda` packages.

ENH support .conda packages

---

broken/prompt-toolkit.txt

Closes https://github.com/conda-forge/prompt_toolkit-feedstock/issues/62

mark prompt-toolkit 3.0.5 build 0 as broken

---

broken/codec2_103.txt

This was an accidental tag by upstream of 1.03 instead of 1.0.3. The identical 1.0.3 version has now been built, so now 1.03 needs to be marked as broken so the correct number is preferred.
I am the conda-forge `codec2` feedstock maintainer.
* In …

Mark codec2/libcodec2 1.03 as broken

---

token_reset/napari-console.txt

reset token for napari-console

---

broken/pyscf.txt

Add Pyscf V0 to broken

---

broken/pinning.txt

ENH mark bad pinnings as broken

---

broken/comtypes.txt

Version 1.1.12 of comtypes is broken and was already removed from PyPi, see https://github.com/enthought/comtypes/issues/284#issuecomment-1060273098 …

Mark comtypes package version 1.1.12 broken

---

broken/dials-data-2.4.0.txt

Release has been yanked on https://pypi.org/project/dials-data/2.4.0/
The pytest plugin may run tests with incomplete downloads, causing test failures …

remove yanked dials-data release 2.4.0

---

broken/rubinenv-2.0.0_1.txt

We rerendered rubinenv=2.0.0 which created a new build with new compiler pins.  Unfortunately, the upgrade caused an incompatibility with exception passing in pybind11 built with the older compilers (specifically gcc 9 to 10).  As we investigate we need to mark build 1 as broken.
cc @ktlim @beckermr 
but should be …

Mark rubinenv 2.0.0_1 as broken.

---

.github/workflows/master.yml
token_reset/test.txt

test token reset with gha

---

.github/workflows/master.yml

revert conda-smithy master

---

broken/bonsu-3.4.2.txt
broken/bonsu-3.4.3.txt
broken/bonsu-3.4.4.txt

The current release of Bonsu does have wxPython requirements
that can't be satisfied on Python <3.9, so pull those builds to
avoid broken installations.
Bonsu also does not currently support Python 3.10, so remove all
those packages as well.
cf. https://github.com/conda-forge/bonsu-feedstock/pull/41 for investigation …

Pull Bonsu 3.4.4 for Python!=3.9 and all 3.10 pkgs

---

broken/freecad_0.19.4

has symbol lookup error:
undefined symbol: _ZN5boost13match_resultsIPKcSaINS_9sub_matchIS2_EEEE12maybe_assignERKS6_ …

set freecad 0.19.4 to broken

---

token_reset/long_running.rst

Reset tokens for GHA

---

token_reset/python-ldap-feedstock.txt

reset token for python-ldap

---

broken/cutensor.txt

Mark cuTENSOR 1.5.0 build 0 as broken

---

broken/openssl.txt

The issue: https://github.com/conda-forge/openssl-feedstock/issues/87 (package is empty) …

Mark osx-64/openssl-3.0.2 as broken

---

broken/python_osxarm.txt

broken signatures on osx-arm64

---

token_reset.py

DEP remove circle and drone from token resets

---

broken/pip221.txt

See https://github.com/conda-forge/pip-feedstock/issues/94

mark pip 22.1 as broken

---

broken/pymc.txt

Discussion (and ping) here: https://github.com/conda-forge/pymc-feedstock/issues/40
* We …

Mark prematurely-released pymc 4.0.0 build 0 as broken

---

not_broken/requests.txt

see https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/287
* We …

unbreak requests

---

broken/file.txt

Mark x64 builds of osx-arm64 libmagic as broken

---

broken/example.txt
broken/osx-arm64.txt

@msarahan do you mind taking a look if this is OK?
xref.: https://github.com/conda-forge/pandoc-feedstock/pull/116#issuecomment-1210963415

Remove osx arm64 pandoc

---

broken/cmor.txt

mark broke cmor builds 

---

broken/or-tools.txt

The maintainers asked us to revert a migration we merged. We were trying to finish up the abseil migration since the C++ ABI incompatibilities have caused quite a headache.
https://github.com/conda-forge/or-tools-feedstock/pull/24#issuecomment-1242766384
but should be patched in the repo data and be marked unbroken …

List broken ortools due to premature merge

---

broken/arpack.txt

Per https://github.com/conda-forge/arpack-feedstock/pull/47#issuecomment-1247538671.
Produced with this one-liner:
```bash
$ curl https://anaconda.org/conda-forge/arpack/files 2>&1 | grep '3\.8\.0/download' | awk -F['><'] '{print $3}' | sort -u > arpack.txt
```
--- …

Label `arpack` v3.8.0=*_0 and =*_100 as broken

---

README.md

Clarify when to use this repo vs https://github.com/conda-forge/conda-forge-repodata-patches-feedstock
I think this would've helped me avoid the confusion at https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/327#issuecomment-1271810249.

Update README.md to clarify when to modify repodata

---

broken/minimalkv140.txt

See also https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/331 and https://github.com/conda-forge/minimalkv-feedstock/pull/13 …

Mark minimalkv 1.4.0 as broken

---

broken/xeus-zmq.txt

Marked xeus-zmq 1.0.0 as broken

---

broken/broken_file.txt

The recently uploaded MacOS packages for the pnab project are broken as indicated in this pull request: https://github.com/conda-forge/pnab-feedstock/pull/5. The tests failed but for some reason they were not detected by the CI. …

Label new MacOS pnab packages as broken

---

broken/test-dot-conda.txt

ENH mark a .conda broken

---

not_broken/dot-conda.txt

ENH test unbreak dot conda

---

broken/setuptools.txt

Ping @mbargull 
xref.: https://github.com/conda-forge/setuptools-feedstock/pull/295

mark setuptools 65.6.0 as broken

---

broken/gds-base-2.19.11.txt

This PR requests to mark [gds-base 2.19.11](https://anaconda.org/conda-forge/gds-base/files?version=2.19.11) as broken. This version was released with a binary incompatibility (major SO version number bump) that has since been re-released as [gds-base 3.0.0](https://anaconda.org/conda-forge/gds-base/files?version=3.0.0).
* Packages with missing metadata can be marked as broken on a temporary …

Mark gds-base 2.19.11 packages as broken

---

broken/datatoolbox-v5.0.txt

Version 5.0 of [datatoolbox](https://gitlab.com/climateanalytics/datatoolbox/) should have been version `0.5.0`
and was only introduced through a misnamed tag and mindless acceptance of the pr update.
It is shadowing /newer/ versions `0.5.[1234]`.
Datatoolbox has a limited number of users within our organisation and is maintained by @geiges and myself. 
We yanked the tag and version from [pypi](https://pypi.org/project/datatoolbox/#history) and would like to remove it from conda-forge as well, thanks. …

Mark datatoolbox 5.0 as broken (yanked on pypi)

---

broken/cutensornet.txt

I messed up and its presence prevents the solver form functioning as we expected. Build 101 has the right fix (https://github.com/conda-forge/cuquantum-feedstock/pull/21).
cc: @conda-forge/cuquantum …

Mark cutensornet 2.0.0 nompi build 100 as broken

---

broken/xz-static.txt
broken/xz.txt

See https://github.com/conda-forge/xz-feedstock/issues/31

mark xz 5.2.9 as broken

---

token_reset/python-flatbuffers_20221210.txt

Closes https://github.com/conda-forge/python-flatbuffers-feedstock/issues/8
* We …

Reset token for python-flatbuffers

---

not_broken/networkx.txt

This PR reverts https://github.com/conda-forge/admin-requests/pull/525 and we can use repodata patch so fix the build_number 0 for networkx 2.7.1 to fix https://github.com/conda-forge/networkx-feedstock/issues/44.
* In some cases where the number of …

Move networkx-2.7.1-pyhd8ed1ab_0 to unbroken

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/master.yml
.github/workflows/pr.yml
README.md
archive/example.txt
archive_feedstock.py
unarchive/example.txt

add un/archive workflow

---

broken/nbformat-5.1.2.txt

Fixes #257
We [yanked nbformat 5.1.2 from pypi](https://pypi.org/project/nbformat/#history) shortly after it was released because it made the highly problematic (socially) decision of generating random ids using dictionary words. 5.1.3 corrected this behavior. …

Mark nbformat 5.1.2 as broken since it was yanked on pypi

---

token_reset/libcpucycles.txt

Fixes https://github.com/conda-forge/libcpucycles-feedstock/issues/1 …

libcpucycles token reset

---

.github/workflows/create_feedstocks.yml

ENH add staged-recipes job

---

archive/root_pandas.txt

Archive root_pandas

---

token_reset/imageio.txt

Requesting token reset for package imageio following issue conda-forge/imageio-feedstock#1 and advice from @chrisburr at gitter.

Reset imageio upload token (c.f. conda-forge/imageio-feedstock#60)

---

hydrosignatures.txt

Reset token for hydrosignatures

---

token_reset/astroid.txt

Fixes https://github.com/conda-forge/astroid-feedstock/issues/115
cc @conda-forge/astroid
<hr> …

Reset `astroid`'s token

---

hydrosignatures.txt
token_reset/pynldas2.txt

Reset token for pynldas2

---

token_reset/jupyter_core.txt

Reset jupyter_core token to fix https://github.com/conda-forge/jupyter_core-feedstock/issues/67 …

Reset jupyter_core token

---

token_reset/faiss-split

Seeing upload issues in [this CI job]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=637176&view=logs&j=ce4c1b9d-afa5-5397-2c0a-4b68424429b0 ). The bot hasn't raised an issue to reset the token yet, but it probably soon will. So submitting this now to get that process started.
cc @conda-forge/faiss-split
<hr>
but should be patched …

Reset token for `faiss-split`

---

token_reset/ipykernel.txt

Fixes https://github.com/conda-forge/ipykernel-feedstock/issues/154
cc @conda-forge/ipykernel
<hr> …

Reset token for `ipykernel`

---

token_reset/unearth.txt

Fixes https://github.com/conda-forge/unearth-feedstock/issues/6 …

reset token for unearth

---

token_reset/conda-forge-repodata-patches.txt

token reset for conda-forge-repodata-patches

---

token_reset/nibabel.txt

Fixes https://github.com/conda-forge/nibabel-feedstock/issues/36

Request token_reset for nibabel

---

token_reset/ucx-split.txt

Reset token for `ucx-split`

---

token_reset/sharrow.txt

token reset for sharrow

---

token_reset/botocore.txt

token failure at https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=638792&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d
as instructed in https://github.com/conda-forge/status/issues/137 (I think)

token reset for botocore

---

token_reset/cfn-lint.txt

Reset token for `cfn-lint`

---

token_reset/pymatgen-analysis-defects_20230110.txt

Fix https://github.com/conda-forge/pymatgen-analysis-defects-feedstock/issues/7.
* We (`conda-forge/core`) try to make a decision …

Reset token for pymatgen-analysis-defects

---

token_reset/google-auth.txt
token_reset/google-cloud-container.txt
token_reset/google-cloud-monitoring.txt
token_reset/googleapis-common-protos.txt
token_reset/neo4j-python-driver.txt

Fixes https://github.com/conda-forge/google-cloud-container-feedstock/issues/46
Fixes https://github.com/conda-forge/google-cloud-monitoring-feedstock/issues/45
Fixes https://github.com/conda-forge/googleapis-common-protos-feedstock/issues/55
Fixes https://github.com/conda-forge/neo4j-python-driver-feedstock/issues/58
Fixes https://github.com/conda-forge/google-auth-feedstock/issues/111
ping @conda-forge/google-cloud-container
ping @conda-forge/google-cloud-monitoring 
ping @conda-forge/googleapis-common-protos

Reset several tokens

---

token_reset/libthermo.txt

Reset `libthermo` token

---

token_reset/cyclonedx-python-lib.txt

reset token for cyclonedx-python-lib

---

token_reset/astropy.txt

reset token for astropy

---

token_reset/plantuml.txt

token reset for plantuml

---

token_reset/datavzrd.txt

request token reset for datavzrd

---

token_reset/ariadne.txt

Token reset for ariadne

---

token_reset/jupyter_server_terminals.txt

token reset for jupyter_server_terminals

---

token_reset/micropipenv.txt

Token reset for micropipenv

---

token_reset/new_soapy_and_friends.txt

Token reset for new soapysdr modules and related packages

---

token_reset/centerline.txt
token_reset/example.txt

reset-token-centerline

---

token_reset/deepmd-kit.txt

Fix https://github.com/conda-forge/deepmd-kit-feedstock/issues/46 …

reset token for deepmd-kit

---

token_reset/fastapi.txt

Reset token for `fastapi`

---

token_reset/arabic_reshaper.txt

Fix https://github.com/conda-forge/arabic_reshaper-feedstock/issues/13.

Reset token for `arabic_reshaper`

---

broken/bespokefit.txt

We have a massively broken version of one of our packages released into the world, which was not caught in tests and triggered by changes in a dependency. I am one of the maintainers of this package.
the …

Mark as broken a broken release of OpenFF BespokeFit

---

token_reset/google-api-python-client.txt

request token reset for google-api-python-client

---

.github/workflows/master.yml

`token_reset/example.txt` was accidentally removed in PR ( https://github.com/conda-forge/admin-requests/pull/601 ). This readds it. …

Restore `token_reset/example.txt`

---

token_reset/graphblas.txt

Fixes https://github.com/conda-forge/graphblas-feedstock/issues/60#issuecomment-1378226898
cc @conda-forge/graphblas
<hr>
* We …

Reset token for `graphblas`

---

.github/workflows/master.yml
.github/workflows/pr.yml

Move example tests to PR workflow

---

token_reset/coverage.txt

Fixes https://github.com/conda-forge/coverage-feedstock/issues/90
cc @conda-forge/coverage
<hr> …

Reset token for `coverage`

---

token_reset/nvidia-ml-py.txt

Reset token for `nvidia-ml-py`

---

token_reset/bipedal-locomotion-framework.txt

See:
* https://github.com/conda-forge/status/issues/137
* https://github.com/conda-forge/bipedal-locomotion-framework-feedstock/issues/16 …

Reset token for bipedal-locomotion-framework

---

token_reset/mpltoolbox.txt

Reset token for mpltoolbox

---

token_reset/lsprotocol.txt

request token reset for lsprotocol

---

token_reset/jupyterlab.txt

request token reset for jupyterlab

---

token_reset/graphblas.txt

Try again to fix https://github.com/conda-forge/graphblas-feedstock/issues/60
@jakirkham first tried this in #612, but we're still seeing the same invalid token failure.
cc @conda-forge/graphblas …

Reset token for `graphblas` (second try)

---

token_reset/storage3.txt

https://github.com/conda-forge/storage3-feedstock/issues/3 …

Reset storage3 token

---

token_reset/libsndfile.txt

For https://github.com/conda-forge/libsndfile-feedstock/issues/28

reset token for libsndfile

---

token_reset/pytensor-suite.txt

For https://github.com/conda-forge/pytensor-suite-feedstock/issues/14

Request token reset for `pytensor-suite`

---

token_reset/patchelf.txt

Fixes https://github.com/conda-forge/patchelf-feedstock/issues/36
cc @conda-forge/patchelf …

Reset token for `patchelf`

---

token_reset/airflow-provider-great-expectations.txt

This was done before in PR ( https://github.com/conda-forge/admin-requests/pull/618 ). However there are still issues with this token ( https://github.com/conda-forge/airflow-provider-great-expectations-feedstock/issues/5#issuecomment-1379523364 ). So this tries resetting it again.
cc @conda-forge/airflow-provider-great-expectations
<hr>
but should be patched …

Reset token for `airflow-provider-great-expectations` (pt. 2)

---

token_reset/dask-gateway.txt

Fixes https://github.com/conda-forge/dask-gateway-feedstock/issues/35
cc @conda-forge/dask-gateway
<hr>
* We (`conda-forge/core`) …

Reset token `dask-gateway`

---

token_reset.py

ENH safer and faster token reset

---

token_reset/feedstocks_with_issues_2.txt

After going back through [this search]( https://github.com/search?q=org%3Aconda-forge+is%3Aissue+is%3Aopen+created%3A%3E%3D2023-01-01++%22invalid+feedstock+token%22+&type=issues&s=created&o=desc ) following PR ( https://github.com/conda-forge/admin-requests/pull/639 ), found some more feedstocks that had failed uploads since (or were missed previously). This resets all of their tokens.
<hr>
* Packages with missing metadata can be …

Reset tokens of feedstocks that failed uploads (2)

---

token_reset/identify.txt

Fixes https://github.com/conda-forge/identify-feedstock/issues/131
cc @conda-forge/identify
<hr> …

Reset token for `identify`

---

token_reset/hdmf_zarr.txt

Fixes https://github.com/conda-forge/hdmf_zarr-feedstock/issues/3
cc @conda-forge/hdmf_zarr
<hr> …

Reset token for `hdmf_zarr`

---

token_reset/jupyter_server_terminals.txt

Fixes https://github.com/conda-forge/jupyter_server_terminals-feedstock/issues/6
This was done before in PRs ( https://github.com/conda-forge/admin-requests/pull/593 ), ( https://github.com/conda-forge/admin-requests/pull/639 ), ~( https://github.com/conda-forge/admin-requests/pull/642 )~. However it is still having issues it seems. Maybe we should try again?
<hr>
* Packages with missing metadata can be marked as broken on a temporary …

Reset token for `jupyter_server_terminals`

---

token_reset/laz-perf.txt

Fixes https://github.com/conda-forge/laz-perf-feedstock/issues/33
cc @conda-forge/laz-perf
<hr> …

Reset token for `laz-perf`

---

broken/pangeo-forge-recipes.txt

Mark pangeo-forge-recipes 0.9.3 broken

---

token_reset/grpc-google-iam-v1.txt

Fixes https://github.com/conda-forge/grpc-google-iam-v1-feedstock/issues/21
ping @conda-forge/grpc-google-iam-v1

Request token reset for grpc-google-iam-v1

---

broken/libxml2.txt

See https://github.com/conda-forge/libxml2-feedstock/pull/82
cc @conda-forge/libxml2

Mark builds of libxml2 as broken

---

token_reset/reset_feedstocks_with_issues_3.txt

Went through [this search]( https://github.com/search?q=org%3Aconda-forge+is%3Aissue+is%3Aopen+created%3A%3E%3D2023-01-01++%22invalid+feedstock+token%22+&type=issues&s=created&o=desc ) today and found a couple feedstocks with issues, this resets their tokens.
<hr> …

Reset tokens of feedstocks that failed uploads (3)

---

token_reset/reset_feedstocks_with_issues_4.txt

Fixes https://github.com/conda-forge/mayavi-feedstock/issues/72
Fixes https://github.com/conda-forge/grpc-google-iam-v1-feedstock/issues/21 …

Reset tokens of feedstocks that failed uploads (4)

---

token_reset/nbformat.txt

request nbformat token reset

---

token_reset/reset_feedstocks_with_issues_5.txt

Resets a few more tokens of feedstocks that popped up with [this search]( https://github.com/search?q=org%3Aconda-forge+is%3Aissue+is%3Aopen+created%3A%3E%3D2023-01-01++%22invalid+feedstock+token%22+&type=issues&s=created&o=desc ).
Fixes https://github.com/conda-forge/jupyverse-feedstock/issues/16
Fixes https://github.com/conda-forge/pastas-feedstock/issues/15
Fixes https://github.com/conda-forge/pcl-feedstock/issues/52
<hr>
* Packages …

Reset tokens of feedstocks that failed uploads (5)

---

archive/cloog.txt
archive_feedstock.py
unarchive/cloog.txt

This PR fixes up the un/archive jobs so that they retry etc. 
closes #539

ENH archive/unarchive error handling and retry

---

token_reset/example.txt

Trying to address this issue
Request to reset token for pyrsm package

Request to reset token for pyrsm package

---

token_reset/google-auth.txt

Reset token for google-auth

---

token_reset/apache-airflow-providers-dbt-cloud.txt

ping @conda-forge/apache-airflow-providers-dbt-cloud (but it's just me...)
Fixes https://github.com/conda-forge/apache-airflow-providers-dbt-cloud-feedstock/issues/7

Request token reset for apache-airflow-providers-dbt-cloud

---

token_reset/reset_feedstocks_with_issues_6.txt

Resets a few more tokens of feedstocks that popped up with [this search]( https://github.com/search?q=org%3Aconda-forge+is%3Aissue+is%3Aopen+created%3A%3E%3D2023-01-01++%22invalid+feedstock+token%22+&type=issues&s=created&o=desc ).
Fixes https://github.com/conda-forge/gluonts-feedstock/issues/3
Fixes https://github.com/conda-forge/napari-pyclesperanto-assistant-feedstock/issues/15
Fixes https://github.com/conda-forge/pyrsm-feedstock/issues/8
<hr>
not technically broken and should not be …

Reset tokens of feedstocks that failed uploads (6)

---

archive/fbprophet.txt

Reference: https://github.com/conda-forge/fbprophet-feedstock/issues/41

Archive fbprophet feedstock

---

token_reset/gluonts.txt

Fixes https://github.com/conda-forge/gluonts-feedstock/issues/3

Reset token for `gluonts`

---

token_reset/eo-dataflow-ui.txt

Fixes https://github.com/conda-forge/eo-dataflow-ui-feedstock/issues/3

Reset token for `eo-dataflow-ui`

---

token_reset/apscheduler.txt

Reset apscheduler token

---

broken/interpret-0.2.7-py38haa244fe_0.txt

remove win-64 specific interpret 0.2.7

---

broken/gazebo.txt

See https://github.com/conda-forge/gazebo-feedstock/issues/161 for the discussion of the critical regression, that prevents to use gazebo on macOS at all. …

Remove gazebo macOS builds for which a critical regression was introduced

---

token_reset/analytics-python.txt

request token for analytics-python

---

archive/gmatelastoplasticqpot3d.txt

Archive gmatelastoplasticqpot3d-feedstock

---

token_reset/perl-extutils-makemaker.txt

token reset perl-extutils-makemaker-feedstock

---

broken/libxml2.txt

Mark latest libxml2 package as broken on macOS

---

token_reset/types_setuptools-20230322.txt

Reset token for types-setuptools

---

token_reset/tvips-tools.txt

Reset feedstock token for tvips-tools

---

broken/pennylane.txt

As reported in https://github.com/conda-forge/pennylane-feedstock/issues/24, it seems we didn't get the migration to osx-arm64 done correctly (https://github.com/conda-forge/pennylane-feedstock/pull/20). We're still trying to understand what's missing, but the package is currently not usable and cannot be fixed via patching repodata.
cc: @conda-forge/pennylane for vis
* Packages with missing metadata can be marked as broken on a …

Mark Pennylane 0.29.0 build 2 on osx-arm64 as broken

---

archive/pyxtensor.txt

Archive pyxtensor

---

broken/pytorch_geometric.txt

Broken pytorch_geometric 2.3.0

---

broken/pdm_backend.txt

These were marked `noarch: python` but have a dependency that is conditional on the Python version. Instead, the newer, non-noarch builds as fixed in https://github.com/conda-forge/pdm-backend-feedstock/pull/1 should be used.
* In some cases where the number of users of a package is small or …

Mark initial `pdm-backend` versions as broken

---

broken/pdfgui.txt

Remove py310 pdfgui

---

broken/boa.txt

mark boa 0.15 as broken

---

token_reset/ffmpeg-progres-yield
token_reset/ffmpeg-progress-yield

Request token reset per:
https://github.com/conda-forge/ffmpeg-progress-yield-feedstock/issues/12

ffmpeg-progress-yield token reset

---

broken/magentropy.txt

While some of the issues in the broken versions could be fixed by changing metadata, the number of users for this package is low, and I would prefer to simply mark them as broken to avoid confusion. The primary issues are numpy and typing compatibility.
* In some cases where the number of …

Mark magentropy 0.1.2 and 0.1.3 as broken

---

broken/perses.txt

I forgot to add the `conda_build_config.yaml` file to set the target to `perses_dev` …

should have been put on the perses_dev label

---

broken/ncvis-climate.txt

mark osx-arm64/ncvis-climate-2022.08.28-h9b76a12_1.conda as broken

---

broken/ncvis-climate.txt

mark ncvis-climate builds as broken

---

broken/xbyak.txt

See https://github.com/conda-forge/xbyak-feedstock/pull/11
CC @xhochy  …

Marked latest xbyak package as broken

---

broken/bluesky.txt

The dependencies were fixed via https://github.com/conda-forge/bluesky-feedstock/pull/46, need to remove build 0.
* We …

Remove broken bluesky v1.11.0 build=0

---

archive/various_r_feedstocks.txt

These have been archived on CRAN so they're no longer buildable. …

Archive various R feedstocks

---

archive/urdf-parser-py.txt

Archive urdf-parser-py

---

token_reset/r_forge.txt

Reset r-forge token (without travis)

---

broken/python-libarchive-c.txt

mark python-libarchive-c 5.0 as broken on osx

---

broken/pyiron_atomistics.txt

Remove pyiron_atomistics development release from main channel

---

token_reset/tethysplatform.txt

This repository needs a token reset

tethys-platform not uploading

---

broken/eastlake.txt

remove bad eastlake builds

---

archive/r-nlmixr.txt

archive r-nlmixr feedstock

---

broken/arviz-0.16.0.txt

`arviz=0.16.0=pyhd8ed1ab_0` was uploaded without the right version pins. This was corrected in https://github.com/conda-forge/arviz-feedstock/pull/41 for `_1`. However, the `_0` build is broken and should be marked as such.
cc @conda-forge/arviz
Closes conda-forge/arviz-feedstock#43
* In …

Mark arviz=0.16.0=pyhd8ed1ab_0 as broken

---

broken/eigen341.txt

eigen 3.4.1 was released in conda-forge by mistake
https://github.com/conda-forge/eigen-feedstock/issues/39#issuecomment-1649207683
cc @traversaro @conda-forge/eigen …

Mark eigen 3.4.1 as broken

---

broken/responses-0.23.2.txt

We missed a dependency update in https://github.com/conda-forge/responses-feedstock/pull/35 which led to failure of `pip check` elsewhere.
ping @conda-forge/responses …

Mark responses 0.23.2 b0 as broken

---

archive/r-genabel.txt

Package is removed from CRAN, so we can drop it. See https://github.com/conda-forge/r-genabel-feedstock/issues/10
@conda-forge/r-genabel

archive r-genabel feedstock

---

archive/postgres-xl.txt

This was [announced](https://github.com/conda-forge/postgres-xl-feedstock/issues/9) on the feedstock almost 8 month ago.
CC @conda-forge/postgres-xl @hmaarrfk

archive postgres-xl

---

broken/python-utils.txt

Previous Package was incompatible with mentioned python version.
I already update the recipe and build a fix (build number 1):
https://github.com/conda-forge/python-utils-feedstock/issues/34 …

fix: add broken python-utils file for removal

---

token_reset/botocore.txt

seeing upload validation failures again `ERROR getting output validation information from the webservice: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')`
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=755346&view=logs&j=516f237f-98f1-50a4-0946-c43fe5437b81

reset botocore-feedstock token

---

token_reset/mpltoolbox.txt

Create mpltoolbox.txt in token_request folder

---

token_reset/jupyterlab-github.txt

xref: https://github.com/conda-forge/jupyterlab-github-feedstock/issues/4
xref: https://github.com/conda-forge/admin-requests/pull/783

Skip Travis for `jupyterlab-github`'s token reset

---

archive/trio_asyncio.txt

Archive `trio_asyncio` feedstock

---

broken/libsolv.txt

Makr latest libsolv builds as broken

---

archive/parquet_cpp.txt

Archive parquet-cpp

---

broken/kedro-pack.txt

Remove broken kedro-pack-1.0.0

---

archive/cuda-cccl-impl.txt

Requesting `cuda-cccl-impl` to be archived. It is being renamed to `cccl`.
cc: @adibbley @jakirkham
Previous discussion:
- https://github.com/conda-forge/cuda-cccl-impl-feedstock/issues/2
- https://github.com/conda-forge/cuda-cccl-impl-feedstock/pull/3
- https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/539

Archive cuda-cccl-impl.

---

archive/libhdfs3.txt

Upstream development has stalled years ago.
See https://github.com/conda-forge/libhdfs3-feedstock/issues/53, fyi @conda-forge/libhdfs3  …

Archive libhdfs3

---

archive/qcportal.txt

There's more explanatory detail at https://github.com/conda-forge/qcportal-feedstock/issues/33, but basically we want to archive the qcportal feedstock so we can build that package from the qcfractal feedstock alongside its co-developed friends. (new recipe: https://github.com/conda-forge/qcfractal-feedstock/pull/40) The alternative route would have been opening two more feedstocks. The maintainer (both upstream and c-f) agrees with the plan: https://github.com/conda-forge/qcportal-feedstock/issues/33#issuecomment-1716114619 . Possibly broadening the creator for the qcportal package through https://github.com/conda-forge/feedstock-outputs/pull/51 is required, too.

Archive qcportal

---

broken/impi.txt

Mark impi packages broken

---

broken/flask-dance-duplicate-package.txt

Hello I would like to request one Flask-dance package be removed from `conda-forge`. 
I did not update the build number when re-rendering so now there are two v2.0.0 build 0 versions. I have created this [PR](https://github.com/conda-forge/conda-forge-webservices/pull/562) to make the docs more clear so that this mistake isn't repeated. 
but should be patched …

Remove flask-dance package

---

archive/monetdblite.txt

The upstream codebase has been archived and the feedstock maintainer @conda-forge/monetdblite  also agreed to archival in https://github.com/conda-forge/monetdblite-feedstock/issues/13 
the maintainers only, we …

Archive monetdblite

---

archive/gnuradio-soapy.txt

The `gnuradio-soapy` output has been integrated into the `gnuradio` feedstock after moving upstream, and this separate feedstock is no longer necessary to maintain the older version of `gnuradio`. I am the sole maintainer and have opened an issue here: https://github.com/conda-forge/gnuradio-soapy-feedstock/issues/42.
but should be patched in the repo data …

Archive gnuradio-soapy

---

token_reset/assimp.txt

Based on https://github.com/conda-forge/admin-requests/pull/826#issuecomment-1736161237 and https://github.com/conda-forge/admin-requests/pull/745 …

Reset assimp token (without Travis)

---

archive/pyinstrument_cext.txt

https://github.com/conda-forge/pyinstrument_cext-feedstock should be archived because the upstream package is no longer used and has been archived.
See: https://github.com/joerick/pyinstrument_cext
https://github.com/conda-forge/pyinstrument_cext-feedstock/issues/23 …

Archive pyinstrument_cext-feedstock

---

archive/pygeos.txt

Archive pygeos

---

broken/nds2-client-0.16.8-456.txt

`win-64/nds2-client-0.16.8-*_[456].conda` were all built with the wrong CMake generator, which results in apparently functional executables, but libraries that produce totally broken SWIG bindings, so this PR requests to mark them as broken.
See https://github.com/conda-forge/nds2-client-feedstock/pull/28 for the fix that will produce a `_7` build, and https://github.com/conda-forge/nds2-client-swig-feedstock/pull/37 for my misguided attempts to find the problem in the downstream SWIG bindings package.
* Packages with requirements/metadata that are too strict but …

Mark win-64/nds2-client-0.16.8-*_[456].conda as broken

---

token_reset/dulwich.txt

Request token reset (without Travis) for dulwich

---

broken/backports-datetime-fromisoformat.txt

These packages were incorrectly created as `noarch` but they include a C library that is both specific to the architecture and the python version. …

Mark 2 builds of backports-datetime-fromisoformat broken

---

archive/vscode-extensions.txt

See https://github.com/conda-forge/vscode-python-feedstock/issues/49 and https://github.com/conda-forge/vscode-icons-feedstock/issues/36, cc @conda-forge/vscode-python and @conda-forge/vscode-icons I'm the sole active maintainer in recent months.
I have been using these to install VSCode extensions into code-server but they have been broken in the latest versions and there seems to be no simple way to fix/debug this. …

Archive vscode-{icons,python}

---

token_reset/requests-kerberos.txt

Request token reset without travis for requests-kerberos

---

broken/cusparselt.txt

We accidentally uploaded one package from https://github.com/conda-forge/cusparselt-feedstock/pull/33 during the process of updating the package version. This PR marks the accidental package as broken.
cc: @conda-forge/cusparselt for vis  …

Mark cusparselt v0.4.0 linux64 build3 package as broken

---

broken/chemprop.txt

Label `chemprop==1.6.0` as Broken

---

token_reset/flower.txt

Request token reset (without travis) for `flower`

---

broken/libutf8proc.txt

This new version breaks for example pyarrow installations, see https://github.com/conda-forge/libutf8proc-feedstock/pull/16#issuecomment-1773738572 …

Mark libutf8proc 2.9.0 as broken

---

broken/mpi4py.txt

See here: https://github.com/conda-forge/mpi-feedstock/issues/11
Basically impi packages were shipped to early without the proper constraints and are being coinstalled with other mpi providers. …

ENH fix mpi4py for early impi release

---

grant_access/gpu-runner/init.txt

Add some repos for cirun testing

---

broken/jupyter_server.txt

Mark jupyter_server 2.11.0 as broken

---

archive/openmm-atmmetaforce-plugin.txt

Per the discussion in issue ( https://github.com/conda-forge/openmm-atmmetaforce-plugin-feedstock/issues/17 ), this requests archiving `openmm-atmmetaforce-plugin`
cc @conda-forge/openmm-atmmetaforce-plugin
<hr> …

Archive `openmm-atmmetaforce-plugin`

---

access_control.py

Send PR to enable GPU builds in the feedstock

---

access_control.py
environment.yml

Pass cirun args

---

grant_access/gpu-runner/pytorch.txt

Try gpu-runner for pytorch-cpu

---

access_control.py

Fix sending PR

---

access_control.py

More fixes for sending PR

---

access_control.py

Final send PR fixes

---

access_control.py

No need to have upload on branch

---

grant_access/gpu-runner-pr/magma.txt
grant_access/gpu-runner/magma.txt

Allow Magma feedstocks to use GPU runners

---

access_control.py

Fix typo in access_control.py

---

requests/pytorch-gpu.yml

PRs and CPU runners for pytorch-cpu

---

conda_forge_admin_requests/access_control.py

Use the admin github token for sending PR

---

requests/pyct-core.yml

https://github.com/conda-forge/pyct-core-feedstock/issues/5
@conda-forge/pyct-core

Archive pyct-core

---

requests/frozendict.yml

The latest frozendict noarch build is broken. It contains a `.egg` that is for python 3.12 and so doesn't work on other versions of python. 
xref: https://github.com/conda-forge/frozendict-feedstock/issues/51
cc @conda-forge/frozendict 
cc @erykoff 
* In some cases where the number of users …

frozendict noarch build is broken

---

requests/pytest-runner.yml

archive pytest-runner

---

.github/PULL_REQUEST_TEMPLATE.md
README.md
examples/example-gpu-runner.yml
examples/example-open-gpu-server.yml

Comes from https://github.com/conda-forge/admin-requests/pull/874#issuecomment-1832721298

Add some more comments for the opt-in request infra

---

requests/libpq-openssl32.yml

See discussion https://github.com/conda-forge/postgresql-feedstock/issues/191
cc: @h-vetinari @akrherz 
These packages were built requiring "openssl>=3.2", but with that version of openssl, users experience errors at runtime because we forgot to merge in a patch
the fix is proposed: https://github.com/conda-forge/postgresql-feedstock/pull/192/files
but should …

Mark libpq and postgresql 16.1 builds 1 2 and 4 as broken due to openssl 3.2

---

requests/archive.yml

Archive the `psychopy` feedstock
Relevant issue: https://github.com/conda-forge/psychopy-feedstock/issues/64
ping @conda-forge/psychopy @kastman …

Archive `psychopy` feedstock

---

requests/m2-conda.yml

Mark m2-conda-epoch as broken for now

---

requests/pydantic_core_2_14_6.yml

https://github.com/conda-forge/pydantic-core-feedstock/issues/79 …

Mark pydantic core 2.14.6 as broken on linux

---

conda_forge_admin_requests/access_control.py

See https://github.com/conda-forge/.cirun/pull/7

Add 'write' as default roles for cirun

---

requests/cf-autotick.yml

CPU large and PR for cf-autotick-bot-test-package

---

conda_forge_admin_requests/__init__.py
conda_forge_admin_requests/__main__.py
pyproject.toml

register actions so that it can be used in other repos

---

requests/tensorflow215-cuda.yml

These packages are not actually build with CUDA support, see https://github.com/conda-forge/tensorflow-feedstock/issues/365
cc @conda-forge/tensorflow  …

Mark tensorflow 2.15 CUDA builds as broken

---

conda_forge_admin_requests/access_control.py
examples/example-open-gpu-server.yml
requests/test-cirun.yml

allow large CPU runners for bot

---

conda_forge_admin_requests/access_control.py
requests/test-cirun.yml

don't send cirun-roles multiple times

---

requests/test-cirun.yml

ci-xlarge for cf-autotick-bot-test-package

---

requests/diffstar.yml

ENH diffstar broken

---

conda_forge_admin_requests/access_control.py
conda_forge_admin_requests/token_reset.py
requests/reset-pytorch-cf.yml

Fixes https://github.com/conda-forge/admin-requests/issues/920

Use a global STAGING_BINSTAR_TOKEN for GHA

---

requests/archive_cyminmax.yml

Archiving this feedstock as I'm no longer interested in maintaining it
cc @conda-forge/cyminmax
xref: https://github.com/conda-forge/cyminmax-feedstock/issues/15
<hr> …

Archive `cyminmax`

---

requests/m2-ca-certificates.yml
requests/m2-conda-epoch.yml

mark m2-ca-certificates as broken and unmark m2-conda-epoch

---

requests/archive.yml

archive antarctic-plots

---

requests/broken.yml

mark broken build of polartoolkit

---

requests/broken.yml

It was discovered that benchmark had been missed on this release. Therefore it needs to be marked as broken until confidence has been regained …

Mark arcticdb 4.3.0 broken

---

conda_forge_admin_requests/token_reset.py

BUG make sure to write tokens when resetting tokens

---

.github/workflows/main.yml
conda_forge_admin_requests/__main__.py
requests/pytorch.yaml

ENH support `.yaml`

---

requests/conda-smithy.yml

See https://github.com/conda-forge/conda-smithy/issues/1847

mark conda-smithy 3.31.0 as broken

---

requests/cutlass.yaml

Cutlass takes about 24 hours to compile in the current runners. I am trying to make it run on the openstack ones.
* We …

PRs and CPU runners for cutlass

---

requests/rm-gmsh-4.13.0.yml

gmsh v4.13.0 has not been released, but a source tarball was inadvertently created upstream, which got picked up by the package update scripts and merged. See https://github.com/conda-forge/gmsh-feedstock/pull/89 and https://gitlab.onelab.info/gmsh/gmsh/-/issues/2822 for context.
cc @conda-forge/gmsh  …

remove broken gmsh 4.13.0

---

requests/arraylake.yml

A bug in arraylake versions 0.9.0, 0.9.1, and 0.9.2 was found to produce data consistency issues in certain situations. This issues have been corrected with 0.9.3. Users are strongly recommended to not use these versions going forward. 
cc @conda-forge/arraylake …

Mark arraylake 0.9.0, 0.9.1, and 0.9.2 as broken

---

requests/archive-azure.yml

These packages are deprecated according to https://pypi.org/project/azure/ and https://pypi.org/project/azure-mgmt/
They also don't seem to be maintained here

Request to archive azure & azure-mgmt

---

requests/broken.yml

MNT: remove version of libsecp256k1 with statically-linked library

---

requests/jaxlib-open-gpu.yml

request large CPU runners for jaxlib

---

requests/openssl.txt

ENH mark openssl broken

---

requests/openssl-token.yml

ENH Reset feedstock token for openssl

---

requests/openssl.yml

Reverts conda-forge/admin-requests#962

Revert "ENH mark openssl broken"

---

requests/pycrdt.yml

Mark pycrdt v0.8.13 as broken

---

.github/workflows/main.yml
.github/workflows/repodata_patching.yml

REF use GHA action for app tokens

---

requests/archive-typer-cli.yml

Typer related packages are part of the same monorepository since 0.12.0. Therefore we decided to provide the typer-cli package as an output of the typer-feedstock recipe.
PR adding typer-cli as output to typer-feedstock: conda-forge/typer-feedstock#26
Ref: https://github.com/conda-forge/typer-cli-feedstock/issues/15
:bell: @conda-forge/typer-cli

Request to archive typer-cli

---

examples/example-open-gpu-server.yml
requests/tensorflow.yml

large runner for tensorflow

---

requests/tensorflow.yml

retry large runner for tensorflow

---

requests/unarchive-pyarrow.yml

@h-vetinari should merge this.

Unarchive pyarrow repository

---

requests/sdformat14.yml

Upstream released a version that is non-relocatable, and in a way that conda-build binary package prefix patching is not working. This interferes with any use of the library, so let's mark this releases as broken while we work on a fix, see https://github.com/conda-forge/libsdformat-feedstock/issues/116 . …

Mark libsdformat14 14.2.0==*=*_0 as broken

---

requests/archive-hydra.yml

As addressed in https://github.com/conda-forge/hydra-feedstock/issues/16, the repository is currently unmaintained since 2017.
FYI @conda-forge/hydra  …

Archive `hydra-feedstock`

---

requests/mne-rsa-broken.yml

Mark `mne-rsa` 0.91 as broken, as the upstream version has been retracted due to an incorrect version number

---

requests/howardhinnant_date-3.0.1#4-broken.yml

Mark howardhinnant_date-3.0.1#4 builds as broken

---

requests/archive-pyspark-stubs

As mentioned in https://github.com/conda-forge/pyspark-stubs-feedstock/issues/15 the upstream package has been deprecated and is no longer maintained. …

Archive pyspark-stubs-feedstock

---

requests/m2w64.yml

Archive m2w64 binary repackage feedstocks

---

requests/gromacs-broken.yml

Remove broken Gromacs package

---

requests/xsarslc.yml

add a .yml to request archiving of xsarslc-feedstock project

---

requests/nodejs.yml

I would like to use the larger runners for the @conda-forge/nodejs as we now running into the limits of the Azure runners with the latest 22.x release: https://github.com/conda-forge/nodejs-feedstock/pull/350 …

Add nodejs to cirun

---

requests/m2-filesystem.yml

Mark m2-fileystem new builds as broken

---

requests/caterva-archive.yml

see https://github.com/conda-forge/caterva-feedstock/issues/4 …

Archive caterva

---

requests/archive-omniorbpy.yml

Ping @conda-forge/omniorbpy 
omniorbpy package is now part of the [omniorb-feedstock](https://github.com/conda-forge/omniorb-feedstock).
Fix https://github.com/conda-forge/omniorbpy-feedstock/issues/18
See https://github.com/conda-forge/omniorb-feedstock/pull/53

Archive omniorbpy

---

requests/archive-rgdal.yml

archive r-rgdal

---

requests/dx-broken.yml

1. `mathdx` 24.04.0 build 0 packages have wrong file layout (cc: @conda-forge/mathdx)
2. `nvmath-python-dx` v0.1.0 does not support Python 3.12 (the skip condition was too loose, cc: @conda-forge/nvmath)
the …

Mark some `mathdx` and `nvmath-python-dx` packages as broken

---

.github/workflows/pr.yml
requests/token-pinning.yml

fix: reset token for pinnings

---

requests/opentracing_instrumentation-archive.yml

Library is no longer being maintained.
xref: https://github.com/uber-common/opentracing-python-instrumentation/issues/118
* We …

Archive opentracing_instrumentation-feedstock

---

requests/vs.txt

See https://github.com/conda-forge/vc-feedstock/pull/82#discussion_r1731979252
cc @conda-forge/vc

Mark vs 19.41 as broken

---

conda_forge_admin_requests/__main__.py
conda_forge_admin_requests/access_control.py
conda_forge_admin_requests/archive_feedstock.py
conda_forge_admin_requests/mark_broken.py
conda_forge_admin_requests/token_reset.py
update_repodata_patches.py

As per recommendations at https://docs.python.org/3/library/subprocess.html#security-considerations.

Do not use `shell=True` in subprocesses

---

requests/flash-attention-xlarge.yml

Create request for xlarge runner

---

requests/archive_pickle5.yml

This was a backport for Python pre-3.8. Builtin support is in the Python standard library. All the versions covered by this feedstock are EOL and dropped from conda-forge. So let's archive it. …

Archive `pickle5` feedstock

---

requests/archive-segalign.yml

See issue https://github.com/conda-forge/segalign-feedstock/issues/22 …

request to archive segalign-feedstock

---

requests/python-ldas-tools-framecpp-py312.yml

The Python 3.12 builds of `python-ldas-tools-framecpp` are broken, see https://github.com/conda-forge/ldas-tools-framecpp-swig-feedstock/issues/32.
I am the maintainer of that feedstock and am working with upstream on a fix, and will patch the build to skip Python 3.12 until that time.
* In …

Mark python-ldas-tools-framecpp py312 builds as broken

---

requests/irisgrib_hyphenerror_broken.yml

Package was mistakenly added with wrong name.
Should use package named "iris-grib" instead of "iris_grib" -- i.e. hyphen in place of underscore …

Label iris_grib v0.20 broken

---

requests/noentry.yml

chore: mark packages with broken entry points broken

---

requests/archive-jupyterlab_latex.yml

archive jupyterlab_latex

---

README.md

doc: clarify docs

---

requests/request-add-feedstock-output.yml

Add outputs for dartsim-feedstock

---

requests/request-archive.yml
requests/request-broken.yml

Hi,
We kindly request that you archive the specified feedstocks, as stated by @beckermr in the PR https://github.com/conda-forge/admin-requests/pull/1071.
Thank you. …

Request package archive

---

requests/archive-r-xmisc.yaml

https://github.com/conda-forge/r-xmisc-feedstock/issues/9
ping @conda-forge/r

Archive `r-xmisc` feedstock

---

requests/pysimplegui-archive.yml

See https://github.com/conda-forge/admin-requests/pull/1085 for more context. This software is no longer redistributable.

archive pysimplegui

---

requests/xlayers-archive.yml

Archive xlayers

---

broken/m2w64-sysroot-feedstock-v12.0.0.rc2.txt

Mark `{m2w64-sysroot_win-64-,mingw-*}-v12.0.0.r2` builds as broken

---

requests/grpcio-tools.yml

Follow-up to ingesting that output in the the grpc-cpp feedstock due to build circularity (https://github.com/conda-forge/grpc-cpp-feedstock/pull/370).
CC @conda-forge/grpcio-tools

archive grpcio-tools

---

requests/nexus-add-feedstock-output.yml

Package split in 2 (`libnexus` and `nexus-apps`) to avoid conflict with `nxdir` included in `nexusformat`
See https://github.com/conda-forge/nexus-feedstock/issues/20 and  https://github.com/conda-forge/nexus-feedstock/pull/22
Ping @conda-forge/nexus (I'm the only maintainer)

Add new output for nexus feedstock

---

requests/archive-halide-python.yml

See https://github.com/conda-forge/halide-python-feedstock/issues/15
cc @conda-forge/halide-python

Archive halide-python-feedstock

---

requests/broken-parcels3.0.5.yml

Remove Parcels 3.0.5

---

requests/pyside680-broken.yml

Closes: https://github.com/conda-forge/pyside2-feedstock/issues/247
xref: https://github.com/conda-forge/pyside2-feedstock/issues/247
Star imports are kinda broken, and this has been reported upstream with a "Blocker" designation.
https://bugreports.qt.io/browse/PYSIDE-2888 …

Mark PySide 6.8.0 build0 packages as broken

---

requests/archive-b2.yml

archive b2-feedstock

---

requests/pathlib-archive.yml

archive pathlib

---

requests/exa-archive.yml

Context:
* exa is unmaintained, see https://github.com/ogham/exa
* the successor is eza https://github.com/eza-community/eza
* Issue in the feedstock https://github.com/conda-forge/exa-feedstock/issues/7
(I am the exa-feestock maintainer) …

Archive exa feedstock

---

requests/coverage-lcov-token-reset.yml

Reset token coverage-lcov

---

requests/archive3.yml

context:
* https://github.com/conda-forge/ytop-feedstock/issues/10
* https://github.com/conda-forge/ann_visualizer-feedstock/issues/1
* https://github.com/conda-forge/jupyterlab-plotly-extension-feedstock/issues/3
(I am maintainer of all 3 feedstocks)
* In some cases where the number of …

Archive ytop, ann-visualizer, jupyterlab-plotly-extension

---

requests/archive.yml

These R feedstocks have all been removed from CRAN and need to be archived:
- `r-modes` - https://github.com/conda-forge/r-modes-feedstock/issues/8
- `r-pathological` - https://github.com/conda-forge/r-pathological-feedstock/issues/8
- `r-xroi` - https://github.com/conda-forge/r-xroi-feedstock/issues/2
- `r-xtractomatic` - https://github.com/conda-forge/r-xtractomatic-feedstock/issues/11
* Packages with missing metadata can be marked …

Archive R feedstocks removed from CRAN

---

requests/nebari-broken.yml

That specific release has a significant bug within its backward compatibility  we've addressed that on a hotfix, but the previous one needs to be marked as broken
the maintainers only, we can allow packages to …

Mark noarch/nebari-2024.9.1-* as broken

---

conda_forge_admin_requests/token_reset.py
examples/example-token-reset.yml

This PR adds experimental options for unique tokens and token expiration. I am using it to test these new features.

feat: add options for unique tokens and token expiration

---

requests/cftest.yml

test: token per provider test

---

requests/cftest.yml

This one tests expiring tokens.

test: try a token expiration time

---

requests/test-broken.yml

test: try automerge w/ push bypass by admin

---

requests/iris_main_remove_v3.11.0rc0

Hi, the config file in iris was accidentally misnamed with a "-" instead of "_". This has meant that the release candidate accidentally was released on the main channel. …

Mark 3.11.0rc0 as broken on iris main channel

---

requests/reset_token.rst

Change back to generic token for testing.

test: move back to generic token

---

requests/archive_feedstocks.yml

This R feedstock has been removed from CRAN and should now be archived - it has no dependents:
- https://github.com/conda-forge/r-popgenome-feedstock/issues/8 …

archive R feedstock removed from CRAN

---

requests/archive_feedstocks.yaml

I'm a maintainer of two feedstocks - hipscat and hipscat-import - which are now deprecated and should be archived.
https://github.com/conda-forge/hipscat-feedstock/issues/22
https://github.com/conda-forge/hipscat-import-feedstock/issues/13 …

Archive deprecated feedstocks

---

requests/archive_feedstocks.yml

These feedstocks are now redundant and should be archived:
- https://github.com/conda-forge/shinycustomloader-feedstock/issues/5
- ~~https://github.com/conda-forge/m2w64-muparser-feedstock/issues/14~~
the …

archive redundant shinycustomloader

---

requests/request-add-feedstock-output.yml

I would like to add two new outputs the momentum feedstock (https://github.com/conda-forge/momentum-feedstock/pull/70): pymomentum-cpu and pymomentum-gpu (similar to pytorch)
---
the maintainers only, we can …

Add outputs for momentum-feedstock

---

requests/shared-memory38.yml

Archive shared-memory38

---

requests/mark_broken_cuda_python_12.6.1_11.8.4.yml

The recently released `cuda-python`'s `12.6.1` & `11.8.4` had significant bug: https://github.com/NVIDIA/cuda-python/issues/215
For this reason both versions have been yanked from PyPI:
* https://pypi.org/project/cuda-python/12.6.1/
* https://pypi.org/project/cuda-python/11.8.4/
This marks the `cuda-python` version `12.6.1` & `11.8.4` packages broken
<hr>
but …

Mark broken `cuda-python`: `12.6.1` & `11.8.4`

---

broken/micromamba-2.0.3.txt

Marked micromamba 2.0.3 as broken

---

requests/request-add-feedstock-output.yml

add request to add pydap-server as output for pydap

---

requests/token-reset-cf.yml

This PR does another token reset for testing the new token scheme.

test: reset tokens again for testing

---

requests/curl.yml

mark curl 8.11.0 broken due to bug in netrc handling

---

requests/pydap-broken.yml

Create pydap-broken.yml because not noarch

---

requests/token-reset.yml

move cf test package back to default token

---

conda_forge_admin_requests/token_reset.py
examples/example-token-reset.yml

This PR enables unique tokens per provider.

feat: enable unique tokens per provider

---

requests/flash-attn-outputs.yml

NEW: Allow optional modules for flash-attention feedstock

---

requests/pytest-flake8.yaml

Missed `setuptools_scm`, which resulted in a version 0.0.0 being encoded in the Python package metadata. Fixed in conda-forge/pytest-flake8-feedstock#25. …

Mark pytest-flake8-1.3.0_0 broken

---

requests/conda-standalone-24.9.2.yml

Add CFEP-3 request for conda-standalone 24.9.2

---

requests/gdal.yml

add libgdal-* outputs to gdal

---

requests/urljsf.yml

add urljsf outputs

---

requests/ctng.yml

clang_impl, take 2

---

requests/flask-security.yml

https://github.com/conda-forge/flask-security-feedstock/pull/7
Perhaps the upload problem is due that the package has changed to `noarch`?
https://github.com/conda-forge/admin-requests/pull/1167 attempted to reset the token, but that did not work.

Request package output change for `flask-security`

---

requests/add-ctapipe-base.yml

We want to split our package `ctapipe` into a `ctapipe-base` package only depending on the core required dependencies and a `ctapipe` that comes with additional optional dependencies.
See PR here: https://github.com/conda-forge/ctapipe-feedstock/pull/31/files

Add request for ctapipe-base

---

requests/distutils-activate-mingw.yml

allow libpython-feedstock to output distutils-activate-mingw

---

requests/add-libgcrypt-output.yml

Add libgcrypt output mappings

---

requests/add-feedstock-output.yml

I add my package just two days ago but accidentally named it using an underscore instead of a dash when setting up my recipe.
I would like to fix this by updating the outputs for my feedstock. This way I can ensure the package name is consistent between both installation sources, i.e. both `pip install scikit-sundae` and `conda install scikit-sundae` both work. Presently, the conda installation is for `scikit_sundae` instead of `scikit-sundae`.
not technically broken and should not be marked …

scikit-sundae new output request

---

requests/sprocket-token-reset.yml

staged recipe: https://github.com/conda-forge/staged-recipes/pull/28240
failed copy from staging to prod: https://github.com/conda-forge/sprocket-feedstock/issues/1
Tried package build and rerender in https://github.com/conda-forge/sprocket-feedstock/pull/3
Now trying to reset token

sprocket feedstock reset token request

---

requests/archive_feedstocks.yml

The `lsd-rust` feedstock was found to be redundant with `lsdeluxe` as noted here: https://github.com/conda-forge/lsd-rust-feedstock/issues/3.  Since the `lsdeluxe` was the first feedstock, `lsd-rust` should be archived.
* In some cases where the number of users of a package is small or it is …

archive redundant lsd-rust feedstock

---

requests/libsemigroups_cppyy.yml

Request archiving of libsemigroups_cppyy

---

requests/xgboost-token-reset.yml

Looks like XGBoost feedstock token expired ( https://github.com/conda-forge/xgboost-feedstock/issues/202 )?
This attempts to reset the token.
<hr> …

Reset token for XGBoost feedstock

---

requests/neo4j-python-driver-rust-ext-token-reset.yml

The token seems to have expired
https://github.com/conda-forge/neo4j-python-driver-rust-ext-feedstock/issues/5
* We …

Reset token for neo4j-python-driver-rust-ext

---

requests/archive-heliopy.yaml

See issue at https://github.com/conda-forge/heliopy-feedstock/issues/37 - I'm the sole maintainer of the feedstock.
* We …

Request to archive heliopy

---

requests/spacy-models.yml

add feedstock output wildcard for spacy-model- in spacy-models

---

requests/archive_mitmproxy_wireguard.yaml

I want to requests archiving the [mitmproxy_wireguard](https://github.com/conda-forge/mitmproxy_wireguard-feedstock) feedstock. Upstream development has stopped and the last release was in April 2023. The [upstream repository](https://github.com/decathorpe/mitmproxy_wireguard) is archived. The project is not build-able on python >= 3.12.
Upstream notes that the functionality is now available in [mitmproxy_rs](https://github.com/mitmproxy/mitmproxy_rs) instead.
I opened issue https://github.com/conda-forge/mitmproxy_wireguard-feedstock/issues/13 in the feedstock. I'm the only maintainer.

Archive mitmproxy_wireguard

---

requests/conda-standalone-24.11.0.yml

Request CFEP3 for osx-arm64/conda-standalone 24.11.0

---

requests/pytorch-add-libtorch-cuda-linalg.yml

Add feedstock output for libtorch-cuda-linalg in pytorch-cpu

---

requests/add-scipy-typed.yml

Still draft for now until we decide if we want to add this, cc @rgommers @jorenham @h-vetinari 
x-ref https://github.com/conda-forge/scipy-feedstock/pull/289

add scipy-typed

---

requests/fast-barnes-py-reset.yml

reset_token_fast-barnes-py

---

requests/sqlite.yml

See https://github.com/conda-forge/sqlite-feedstock/issues/118#issuecomment-2500451436

reset sqlite token

---

requests/add-pybamm-base.yml

Add `pybamm-base`

---

requests/freetype.yml

NEW: Add versioned outputs to freetype

---

requests/archive-pep8.yml

`pep8` has long since been rebranded as `pycodestyle`. So archive the feedstock.
cc @conda-forge/pep8
xref: https://github.com/conda-forge/pep8-feedstock/issues/9
<hr> …

Archive `pep8` (since rebranded as `pycodestyle`)

---

requests/nanobind-abi.yml

Add nanobind-abi output to nanobind

---

requests/wetterdienst.yml

Previously, we only build the main `wetterdienst` package.  We now would like to build `wetterdienst-with-*` packages with the extras in:
See https://github.com/conda-forge/wetterdienst-feedstock/pull/146
the …

Add output for `wetterdienst` extras

---

requests/libfabric1.yml

Preparing to split libfabric outputs in https://github.com/conda-forge/libfabric-feedstock/pull/16 according to discussion in https://github.com/conda-forge/conda-forge.github.io/issues/2401

prepare to split libfabric outputs

---

requests/wetterdienst.yml

Fix wetterdienst request

---

requests/wetterdienst.yml

Try another fix for adding wetterdienst-with-* extras

---

requests/freetype.yml

Change syntax of freetype request

---

requests/nvmath.yml

Add nvmath-python-cpu output to nvmath-feedstock

---

requests/archive-super_state_machine.yml

Appears unmaintained upstream and one feedstock that had it as a dependency no longer does.
xref https://github.com/conda-forge/super_state_machine-feedstock/issues/11
ping @conda-forge/super_state_machine (but I am the only one of the three listed maintainers who still has a professional interest in it). …

Archive super_state_machine

---

requests/archive_nose.yml

Archive the `nose` feedstock as the upstream repo has been unmaintained for 8 years
cc @conda-forge/nose
xref: https://github.com/conda-forge/nose-feedstock/issues/26
<hr> …

Archive `nose` feedstock

---

requests/add-cf-xarray-outputs.yml
requests/add-ioos-qc-outputs.yml
requests/add-ioos-tools-outputs.yml

request new outputs for these feedstocks

---

requests/python-wget.yml

Needed in https://github.com/conda-forge/python-wget-feedstock/pull/1

reset token python-wget

---

requests/add-cuquantum-feedstock-output.yml

Add cudensitymat output to cuquantum-feedstock.

---

requests/cleo-broken.yml

See:
https://pypi.org/project/cleo/#history
https://github.com/conda-forge/cleo-feedstock/issues/20
* We (`conda-forge/core`) try …

Mark yanked version of cleo as broken

---

requests/stopit.yml

request stopit to be able to publish stopit

---

requests/add-cuda-core-output.yml

We (@conda-forge/cuda-python) are adding a new output `cuda-core` to cuda-python-feedstock that we maintain. This is a  new Python package that will eventually become part of `cuda-python`.
- https://pypi.org/project/cuda-core/
- https://nvidia.github.io/cuda-python/cuda-core/latest/
* In …

Add `cuda-core` output to cuda-python-feedstock

---

requests/archive-aesara.yml

Aesara is no longer maintained. See the "Important" notice near the top of the project [readme](https://github.com/aesara-devs/aesara):
> [!IMPORTANT]
> This project is no longer actively maintained.  See https://github.com/aesara-devs/aesara/discussions/1521#discussioncomment-7687831 and https://x.com/BrandonTWillard/status/1729350499793588249 for more details.
The project lead @brandonwillard has agreed that the feedstock should be archived in https://github.com/conda-forge/aesara-feedstock/pull/139#issuecomment-2558528511.

Archive aesara feedstock

---

requests/xlwt-archive.yml

Repo has been archived since May 4, 2020
xref: https://github.com/python-excel/xlwt …

Archive xlwt-feedstock

---

requests/tune-sklearn-archive.yml

archive tune-sklearn

---

requests/databricks-sql-connector-add-extras.yml

Previously, I only build the main `databricks-sql-connector` package. I now would like to build `databricks-sql-connector-with-*` packages with the extras included.
See https://github.com/conda-forge/databricks-sql-connector-feedstock/pull/38 …

Add `databricks-sql-connector-with-*` extras

---

requests/jupyter-dash-archive.yml

See conda-forge/jupyter-dash-feedstock#12. The original packagehas been archived since 3 June 2024 as well. Last version update was on 1 April 2022.

archive jupyter-dash feedstock

---

requests/oddt-archive.yml

Archive oddt

---

requests/bleach.yml

add output bleach-with- wildcard to bleach

---

requests/archive-ff-static.yml

* Archive the ff-static feedstock (https://github.com/conda-forge/ff-static-feedstock) in favor of the ff-feedstock (https://github.com/conda-forge/ff-feedstock).
- c.f. https://github.com/conda-forge/ff-static-feedstock/issues/3
- c.f. Discussion on https://github.com/conda-forge/ff-static-feedstock/pull/1
- Related: https://github.com/conda-forge/admin-requests/pull/1260
* Packages with missing metadata can be marked as broken on a …

Archive ff-static in favor of ff

---

requests/behave.yml

Request token reset for behave-feedstock:
https://github.com/conda-forge/behave-feedstock/issues/11

reset feedstock token for behave

---

requests/jax-unirep-archive.yml

archive jax-unirep

---

requests/fair-esm-archive.yml

Archive fair-esm

---

requests/argo-workflows-dsl-archive.yml

Archive argo-workflows-dsl

---

requests/greykite.yml

For some reason, this was not done when creating the feedstock. …

allow greykite for greykite-feedstock

---

requests/podaacpy-archive.yml

Archive request for podaacpy-feedstock

---

requests/spotify2musicbrainz-archive.yml

Archive spotify2musicbrainz

---

requests/or-datasets-archive.yml

https://github.com/conda-forge/or-datasets-feedstock/issues/2
@conda-forge/or-datasets  …

Archive or-datasets

---

requests/requests_download-archive.yml

See conda-forge/requests_download-feedstock#6

Archival of requests_download

---

requests/pychef-archive.yml

archive pychef

---

requests/vincent-archive.yml

archive vincent

---

requests/parambokeh-archive.yml

archive parambokeh

---

requests/paegan-transport.yml

archive paegan-transport

---

requests/transx2gtfs-archive.yml

archive transx2gtfs

---

requests/cgsn_processing.yml

Reset token for cgsn_processing.

reset cgsn_processing token

---

requests/geojsonio-archive.yml

archive geojsonio

---

requests/valideer-archive.yml

archive valideer

---

requests/conda-build-all-archive.yml

archive conda-build-all

---

requests/jupyter_http_over_ws-archive.yml

request to archive jupyter_http_over_ws

---

requests/tensorflow.yaml

build tensorflow on the cirun GPU machine

---

requests/brewer2mpl-archive.yml

archive brewer2mpl

---

requests/nbclean-archive.yml

archive nbclean

---

requests/flake8-polyfill-output.yaml

Add flake8-polyfill output

---

requests/feedstocks-archive.yml

archive a few feedstocks

---

requests/token-reset.yml

Reset the token of peak-finder-app feedstock 

---

requests/dave-archive.yml

The package is no longer maintained. It will continue as commercial project.
Archive: https://github.com/conda-forge/dave-feedstock/issues/47
ping @conda-forge/dave

Archive DAVE

---

requests/linopy-broken.yml

See discussion at https://github.com/conda-forge/linopy-feedstock/pull/37#issuecomment-2580089355 …

Mark linopy 0.4.2 and 0.4.3 as broken

---

requests/archive-decimal128.yml

request to archive decimal128

---

requests/feedstocks-archive.yml

archive some abandoned packages

---

requests/ursabot.yml

Archive ursabot

---

requests/bio-embeddings-plus-archive.yml

Archive bio-embeddings-plus

---

requests/archive-matplotlib2tikz.yml

Archive matplotlib2tikz

---

requests/hyp3_metadata-archive.yml

As discussed in https://github.com/conda-forge/hyp3_metadata-feedstock/issues/20, the hyp3_metadata package has been [archived upstream](https://github.com/ASFHyP3/hyp3-metadata-templates) so it would make sense to archive the hyp3_metadata feedstock as well.
CC @conda-forge/hyp3_metadata 
* …

Archive hyp3_metadata-feedstock

---

requests/jupyterlab_heroku.yml

cc @conda-forge/jupyterlab_heroku , see https://github.com/conda-forge/jupyterlab_heroku-feedstock/pull/2#issuecomment-2593420271
* …

Archive jupyterlab_heroku

---

requests/flask-jwt-simple.yml

Archive flask-jwt-simple

---

requests/jupyterlab-dash.yml

Archive jupyterlab-dash

---

requests/s3transfer-0.11.0.yml

dependency range on botocore was incorrect in upstream release ref https://github.com/boto/s3transfer/issues/324
there will be an 0.11.1 release very soon with the corrected dependency range …

mark s3transfer 0.11.0 as broken

---

requests/pycrystal.yml

reset token pycrystal

---

requests/bio-embeddings-cpcprot.yml

archive bio-embeddings-cpcprot

---

requests/atoml-archive.yml

archive atoml

---

requests/minuit2-standalone.yml

feat: add outputs for minuit2-standalone

---

requests/minuit2-standalone-archive.yml

feat: archive minuit2-standalone

---

requests/fast-barnes-py-token-reset.yml

Reset fast-barnes-py token

---

requests/pipefunc.yml

xref: https://github.com/conda-forge/pipefunc-feedstock/pull/80
I am adding the `pipefunc-extra` package with includes the recommended dependencies. …

Add `pipefunc-*` output

---

requests/fast-barnes-py-output.yaml

Looks like https://github.com/conda-forge/admin-requests/pull/1335 did not work. Let's try this then.

try fast-barnes-py token reset

---

requests/archive-many.yml

Archive bio-embeddings-bepler, lock and hpbandster

---

requests/fletcher.yml

See https://github.com/conda-forge/fletcher-feedstock/issues/21 cc @conda-forge/fletcher  …

Archive fletcher

---

requests/pipefunc.yml

When converting pipefunc to to a split package with `pipefunc-extras` I used `noarch: generic` for the python package by accident.
I had already opened https://github.com/conda-forge/admin-requests/pull/1341 (already merged) but I noticed it affected more builds. …

Mark broken pipefunc builds

---

requests/add-cuda-bindings-output.yml

We (@conda-forge/cuda-python) are adding a new output `cuda-bindings` to cuda-python-feedstock that we maintain. This is a new Python package that is being refactored out of (but is still) part of `cuda-python`.
- https://pypi.org/project/cuda-bindings/
- https://nvidia.github.io/cuda-python/cuda-bindings/latest/
but should be patched in the repo data and be …

Add `cuda-bindings` output to cuda-python-feedstock

---

requests/archive-pyqi.yml

Project not active for 11 years and archived since November 2023: https://github.com/biocore/pyqi
Only works with Python 2.7 and 3.3: https://github.com/conda-forge/pyqi-feedstock/pull/1#issuecomment-2616047365
xref: https://github.com/conda-forge/pyqi-feedstock/issues/2 …

Archive pyqi

---

requests/archive-pytypes-feedstock.yml

Upsteam https://github.com/Stewori/pytypes has seen no activity in 4 years and it doesn't work with python 3.10 which will become the minimum python version at some point
https://github.com/conda-forge/pytypes-feedstock/issues/8
* In some cases where the number of users of a package is small …

Archive pytypes

---

requests/pydantic-1.10.4-0-broken.yml

Mark `pydantic==1.10.4=0` as broken

---

requests/add-output-dash-pydantic-form.yml

dash-pydantic-form split into form and utils …

Add dash-pydantic-utils output

---

requests/nvpl-broken.yml

mark broken for packages from 3 NVPL feedstocks

---

requests/nvpl-unbroken.yml

Need to make NVPL packages whose feedstock changes are already merged.
The feedstocks:
libnvpl-feedstock
libnvpl-common-feedstock
Packages:
- noarch/libnvpl-dev-25.1.0-hd8ed1ab_0.conda
- noarch/_nvpl_dev_mutex-25.1.0-hd8ed1ab_0.conda
- noarch/libnvpl-common-dev-0.3.1-h707e725_1.conda
* In …

mark not_broken on nvpl meta + common packages

---

requests/csvdiff-archive.yml

xref: https://github.com/larsyencken/csvdiff/commit/533326dd …

Archive csvdiff

---

requests/pdfminer-archive.yml

xref: https://github.com/euske/pdfminer/commit/423f851f
* We (`conda-forge/core`) try to make a decision on these requests within …

Archive pdfminer

---

requests/meld3-archive.yml

xref: https://github.com/Supervisor/meld3/commit/ed4e7b30
* We (`conda-forge/core`) try to make a decision on these requests within …

Archive meld3

---

requests/pyrogram-archive.yml

Pyrogram isn't maintained anymore https://github.com/pyrogram/pyrogram/commit/30de1e21 …

Archive pyrogram

---

requests/feedstocks-archive.yml

Archive a few feedstocks as their related projects are not maintained and their upstream repos have been archived.
* We …

Archive a few unmaintained feedstocks

---

requests/tegra.yml

NEW: Add arm-variant target metapackage

---

requests/sqlite.yml

Looks like this version broke all builds on osx. Let's mark it as broken until we figure it out. …

mark latest sqlite as broken

---

requests/archive-feedstocks.yml

Archive some unmaintained feedstock

---

requests/add-qdoas-output.yaml

requests: add request for output 'doas_cl' in qdoas-feedstock.

---

requests/add-libcudss-output.yaml

requests: added a request to extend allowed outputs in the libcudss feedstock
Changes: extending the allowed outputs to libcudss*
Why: After publishing first conda packages for libcudss, we've decided there are too many and we want to do some renaming, as well as one more output for the new release (hopefully, the last one).
but should be patched in the repo …

requests: added a request to extend allowed outputs in the libcudss feedstock

---

requests/libffi-broken.yml

See https://github.com/conda-forge/libffi-feedstock/pull/53#issuecomment-2651686273 and https://github.com/conda-forge/libffi-feedstock/issues/52. Latest `libffi` on macOS arm64 is broken and prevents imports of packages that use it. cc @isuruf  …

Mark libffi arm64 3.6.4 broken

---

requests/add-ibis-framework-feedstock-output.yml

ping @conda-forge/ibis-framework, Adding two new outputs ibis-athena and ibis-databricks
- https://github.com/conda-forge/ibis-framework-feedstock/pull/109 …

Add ibis-framework-feedstock-outputs ibis-athena and ibis-databricks

---

requests/add-cusparselt-output.yaml

(requests: added a request to extend allowed outputs in the cusparselt feedstock)
Changes: extending the allowed outputs to cusparselt*
Why: We'd like to split the outputs into the runtime and dev packages (cusparselt and cusparselt-dev). To get a bit more flexibility in the future, used a wildcard for the allowed names.
but should be patched in the repo data …

requests: added a request to extend allowed outputs in the cusparselt feedstock

---

requests/openfast-add-feedstock-output.yml

The `openfast` team would like to add a python package for common and batch IO operations of model files.  This python package is part of the standard OpenFAST repository [here](https://github.com/OpenFAST/openfast/tree/main/openfast_io) and has been added to PyPI as well [here](https://pypi.org/project/openfast_io/).
but should be patched in the repo data …

request to add additional output (a python IO library) to openfast feedstock

---

requests/roocs-utils-archive.yml

Archive roocs-utils feedstock

---

requests/jupytergis-add-outputs.yml

This is to allow https://github.com/conda-forge/jupytergis-packages-feedstock/pull/12

Add outputs for jupytergis

---

requests/archive-go1.4-bootstrap.yml

The `go1.4-bootstrap` was previously used to bootstrap `go`. However that is no longer needed as `go` has its own bootstrapping included in its feedstock. So this archives `go1.4-bootstrap`.
xref: https://github.com/conda-forge/go1.4-bootstrap-feedstock/issues/8
xref: https://github.com/conda-forge/go-feedstock/issues/269
<hr>
but should be patched in the …

Archive `go1.4-bootstrap`

---

requests/maxima-upload.yml

upload osx-arm64 maxima package

---

requests/pyg.yml
requests/pytorch_geometric.yml

To support https://github.com/conda-forge/pytorch_geometric-feedstock/pull/51. Justification and agreement from maintainers are in that PR. …

Request additional outputs for pytorch_geometric

---

requests/basictools-archive.yml

Remove BasicTools feedstock. Change name of lib to Muscat

---

requests/arcticdb-5_4_2-broken.yml

We released this off of master inadvertently and it seems to have some regressions.
I am an ArcticDB maintainer.
* We …

Mark arcticdb 5.4.2 as broken

---

requests/add-libltdl-libtool.yml

Add libltdl to libtool feedstock outputs

---

requests/archive-boa.yml

Archiving `boa` as it is archived upstream and is no longer being developed. All relevant details in linked issue on the feedstock.
cc @conda-forge/boa
xref: https://github.com/conda-forge/boa-feedstock/issues/87
<hr>
* In some cases where the number of users of a package is small or it is …

Archive `boa`

---

requests/rattler-37-broken.yml

Mark osx builds of rattler-build 0.37 as broken

---

requests/tpot-output-wildcard.yml

Add tpot sklearnx and amltk

---

requests/archive_typst-test.yaml

I want to request archiving the [typst-test](https://github.com/conda-forge/typst-test-feedstock) feedstock.
Upstream development has stopped with the [upstream repository](https://github.com/tingerrr/typst-test/) being archived.
The project is replaced by [tytanic](https://github.com/tingerrr/tytanic), which I will submit to staged-recipes shortly.
I opened issue https://github.com/conda-forge/typst-test-feedstock/issues/6 in the feedstock. I'm the only maintainer.

Archive typst-test

---

requests/granian-with-star.yml

add output wildcard for granian-*

---

requests/archive-r-spatial-retirees.yml

https://github.com/conda-forge/r-rgeos-feedstock/issues/52
https://github.com/conda-forge/r-maptools-feedstock/issues/26
ping @conda-forge/r-rgeos
ping @conda-forge/r-maptools

Archive R-spatial Retirees

---

requests/jupytercad-add-outputs.yml

I want to add a new output to the jupytercad feedstock: `jupytercad_lite` …

Add outputs for jupytercad

---

requests/add_pythiapyhlopredictor_pypythia.yml

Add PythiaPyhloPredictor to PyPythia outputs

---

requests/cme.yaml

fix: mark conda-managed-env broken for now

---

requests/cctk-broken.yml

remove bioconda/conda-forge namespace collision

---

requests/archive-daft.yml

Closes https://github.com/conda-forge/admin-requests/issues/1424
Issue explaining why it's being archived: https://github.com/conda-forge/daft-feedstock/issues/4
I'm the only feedstock maintainer, and I have pinged the original authors in https://github.com/conda-forge/daft-feedstock/pull/3 to get the full story.
but should be patched in the repo data and be …

Archive daft

---

requests/add-flask-outpouts.yml

This is needed for https://github.com/conda-forge/flask-feedstock/pull/55, which will add these extras.  The extras were requested in https://github.com/conda-forge/flask-feedstock/issues/54.
ping @conda-forge/flask

Add outputs for `flask-with-*` extras

---

requests/add-connexion-outputs.yml

This is needed for https://github.com/conda-forge/connexion-feedstock/pull/48, which will add these extras.  The extras were requested in https://github.com/conda-forge/connexion-feedstock/issues/46.
ping @conda-forge/connexion

Add outputs for `connexion-with-*` extras

---

requests/add-sqlalchemy-outputs.yml

This is needed for https://github.com/conda-forge/sqlalchemy-feedstock/pull/184, which will add these extras.  The extras were requested in https://github.com/conda-forge/sqlalchemy-feedstock/issues/183.
ping @conda-forge/sqlalchemy

Add outputs for `sqlalchemy-with-*` extras

---

requests/conda-forge-pinning.yml

For fixing https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/4412

rotate tokens for pinning repo

---

requests/add_dspy_dspy-ai.yml

add dspy to dspy-ai

---

requests/request-add-feedstock-output.yml

I would like add two new outputs for the sphericart feedstock:
- sphericart-torch (like https://pypi.org/project/sphericart-torch/)
- sphericart-jax (like https://pypi.org/project/sphericart-jax/)
The outputs are from the same GitHub repo: https://github.com/lab-cosmo/sphericart, so it would make sense to have those outputs in the same feedstock.
but should …

Add outputs for sphericart-feedstock

---

requests/doctest.yml

Reset token for doctest

---

requests/add_pyeinsums_einsums.yml

add pyeinsums to einsums outputs

---

requests/opedao-with-wildcard.yml

add openmdao output wildcard opendmao-with-*

---

requests/archive-gaussiancl.yml

`gaussiancl` has been archived on GitHub and is now a part of `glass` (see https://github.com/glass-dev/glass/pull/494).
XRef: https://github.com/conda-forge/gaussiancl-feedstock/issues/7
cc: @conda-forge/gaussiancl 
* In some cases where the number of users of a package is small or it is …

archive `gaussiancl`

---

requests/add-dagster-output-dagster-shared.yml

add dagster output dagster-shared

---

requests/archive.yml

* Close https://github.com/conda-forge/metanetx-post-feedstock/issues/5
* Close https://github.com/conda-forge/metanetx-sdk-feedstock/issues/7
* Close https://github.com/conda-forge/metanetx-assets-feedstock/issues/10
* Close https://github.com/conda-forge/versioneer-518-feedstock/issues/3

Archive versioneer-518 and metanetx feedstocks

---

requests/cudnn.yaml

add cudnn output glob patterns

---

requests/libcudnn.yaml

add libcudnn

---

requests/request-add-feedstock-output.yml

We release a locked version of our package, that pins all dependencies such that users can (if they want to) install without getting any surprises from updates in downstream repos. We forgot to add this in our initial registration, so would like to add it now. The PR changing the recipe is here: https://github.com/conda-forge/pandas-openscm-feedstock/pull/3/files#diff-f3725a55bf339595bf865fec73bda8ac99f283b0810c205442021f29c06eea9a
Thanks for your help!

Add expected outputs for pandas-openscm

---

requests/request-add-feedstock-output.yml

This PR adds a new output for https://github.com/conda-forge/intel-compiler-repack-feedstock

Add expected outputs for intel-compiler-repack-feedstock

---

requests/bloscpack-archive.yml

bloscpack-archive.yml

---

requests/archive-jonmorton-haven.yml

I would like to archive `jonmorton-haven`. Please refer to:
- https://github.com/conda-forge/jonmorton-haven-feedstock/issues/3
- https://github.com/conda-forge/staged-recipes/pull/29574
the maintainers only, we …

Archive jonmorton-haven

---

requests/request-add-feedstock-output.yml

Add expected PyQt6 outputs for pyqt-feedstock

---

requests/nrtk-jatic-archive.yml

Related feedstock PR: https://github.com/conda-forge/nrtk-jatic-feedstock/issues/7
* We (`conda-forge/core`) try to make a decision …

Archive nrtk-jatic-feedstock

---

requests/arcticdb-5.2.5.yaml

Mark some builds of arcticdb 5.2.5 as broken

---

requests/cuquantum-python-archive.yml

The cuquantum-python feedstock is no longer needed since it's output is built in the [cuquantum feedstock](https://github.com/conda-forge/cuquantum-feedstock), see [this issue](https://github.com/conda-forge/cuquantum-python-feedstock/issues/25).
ping @conda-forge/cuquantum-python 
* In some …

Archive cuquantum-python-feedstock.

---

requests/archive_prismatic.yml

Add request to archive prismatic feedstock

---

requests/add-feedstock-output.yml
requests/token-reset.yml

output validation step is failing for no explanation
* We (`conda-forge/core`) try to make a decision on these requests within 24 …

attempt to fix recipe for peak-finder-app

---

requests/libholoscan.yml

add libholoscan-dev

---

requests/add-feedstock-output.yml

add output for renamed geoh5_interop

---

requests/add-rust_win-arm64.yml

Allow rust-activation-feedstock to upload rust_win-arm64

---

requests/archive-opencv-python-headless.yml

As discussed in https://github.com/conda-forge/opencv-python-headless-feedstock/issues/3 and https://github.com/conda-forge/admin-requests/pull/1505 .
fyi @conda-forge/opencv-python-headless @conda-forge/opencv

Add request to archive opencv-python-headless

---

requests/rav1e.yml

Related to https://github.com/conda-forge/rav1e-feedstock/issues/13
@conda-forge/rav1e, Marking the latest built packages as broken since the soname has changed on a rebuild?
For reasons unknown as yet, the name of the library changed from librav1e.so.0 to librav1e.so.0.6 …

NEW: Mark soname change packages as broken

---

requests/arrow-add-utils.yml

Add arrow binaries

---

requests/nvidia.yml

All of the packages listed here are a library which includes the ABI version in the library name. e.g. `libfoo0` I have expanded the allowed outputs for these feedstocks to include `libfoo` (unversioned) and `libfoo[012346789]` to include any single digit versioned library output in the future.
Relevant teams:
@conda-forge/dav1d 
@conda-forge/libnvpl
@conda-forge/cuda
* Packages with missing metadata can be marked as broken on a …

NEW: Expand allowed output names for sonamed packages

---

requests/add_lsstdesc_bpz.yml

feat: add lsstdesc-bpz output

---

requests/pyplanc.yml

add pyplanc output to libplanc

---

requests/add-apache-airflow-core-output.yml

Needed for https://github.com/conda-forge/apache-airflow-core-split-feedstock/pull/2 …

Add `apache-airflow-core-with-all` output

---

requests/archive.yml

Archive cloud-functions-utils

---

requests/add-airflow-outputs.yml

Aargh!  I somehow missed 2 more outputs in in https://github.com/conda-forge/admin-requests/pull/1526 and https://github.com/conda-forge/admin-requests/pull/1527.  These are the last ones for now, I promise!
ping @conda-forge/airflow
Needed for https://github.com/conda-forge/airflow-feedstock/pull/148 …

Add 2 more `airflow-with-*` outputs

---

requests/add-apache-airflow-providers-common-sql-outputs.yml

Needed for https://github.com/conda-forge/apache-airflow-providers-common-sql-feedstock/pull/49
I am the only maintainer so no ping needed. …

Add `apache-airflow-providers-common-sql-with-*` outputs

---

requests/add-airflow-outputs.yml

This is needed for
https://github.com/conda-forge/airflow-feedstock/pull/150.
ping @conda-forge/airflow
* We (`conda-forge/core`) …

Add `airflow-with-polars` output

---

requests/importlib-metadata.yml

Mark importlib-metadata 8.7.0 as broken

---

requests/add-pandera-pandas-feedstock-output.yml

request adding pandera-pandas to pandera-feedtock

---

requests/add-s2geometry-outputs.yml

This is needed for
https://github.com/conda-forge/s2geometry-feedstock/pull/24.
ping @conda-forge/s2geometry
* We …

Add s2geometry-python output to s2geometry

---

requests/arcticdb-5_8_0_man0-broken.yml

I am an ArcticDB maintainer.
I published these build to the main channel rather than to `arcticdb_rc` by mistake yesterday and we'd like to remove them. They've only been downloaded a few times, likely by our own CI jobs.
cf the list here https://anaconda.org/conda-forge/arcticdb/files?channel=main&version=5.8.0%2Bman0 for the packages that I'd like to remove.
* Packages with missing metadata can be marked as broken on a temporary …

Mark ArcticDB 5.8.0+man0 as broken - it should not have been released to the main channel

---

requests/nvmath.yml

NEW: Add nvmath-distributed to nvmath-feedstock

---

requests/add-metatensor-torch-output.yml

Add `metatensor-torch` output to `python-metatensor-torch`

---

requests/broken.yml

Mark beta packages as broken

---

requests/add-libxmlpp-output.yml

Howdy,
The `libxmlpp` feedstock uses different package names for ABI compatibility (e.g. `libxmlpp-4.0`, `libxmlpp-5.0`) - this PR is requesting that `libxmlpp-5.0` be added as an allowed output name.
Thanks! …

Add new output for libxmlpp

---

requests/structlog-gcp.yml

Reset token for structlog-gcp

---

requests/add-csp-gateway-client.yml

Added `csp-gateway-client` upstream:
https://github.com/Point72/csp-gateway/pull/83
using this library:
https://github.com/python-project-templates/hatch-multi …

Add `csp-gateway-client` to `asp-gateway`

---

requests/structlog-gcp-add-feedstock-output.yml

https://github.com/conda-forge/admin-requests/pull/1581#issuecomment-3073355881 conda-forge/structlog-gcp-feedstock#6 (comment)
* …

Add structlog-gcp-add-feedstock-output.yml

---

requests/vcomp.yml

Add vcomp14 output to vc-feedstock

---

requests/add-output.yml

Add libnvptxcompiler-dev

---

environment.yml
scripts/create_feedstocks

They introduced an breakage in their API
cc: @h-vetinari

limit version of pygithub to <2.7.0

---

requests/gymnasium.yml

Adding some new outputs and renaming some to match upstream
https://github.com/conda-forge/gymnasium-feedstock/pull/48
@conda-forge/gymnasium

Add outputs for gymnasium

---

requests/add-libpinocchio-output.yml

Add libpinocchio and pinocchio-python

---

requests/add-output.yml

add cuda-ctadvisor*

---

requests/graphite2-broken.yml

Closes https://github.com/conda-forge/graphite2-feedstock/issues/21
We built the graphite2 package on windows for this specific
build number with the wrong flags
https://github.com/conda-forge/graphite2-feedstock/issues/21#issuecomment-3184562881
It was fixed in https://github.com/conda-forge/graphite2-feedstock/pull/22
but should be patched in the repo data …

Mark graphite2 1.3.14 hac47afa_1 as broken

---

requests/webkit2gtk4.1.yml

WebKit requires a lot of resources to build due to its [unified sources](https://docs.webkit.org/Deep%20Dive/Build/UnifiedBuilds.html). Currently, the build often fails because
- we run out of time (duration >6h),
- or the runner simply stops, probably running out of memory.
Example:
- https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1312004&view=logs&j=f4da4d1f-390b-5521-e6df-2f06cb62cc8d&t=caf1a362-b66b-5153-f05a-912b513ef6fc

Request cirun-openstack-cpu-2xlarge for webkit2gtk4.1

---

requests/qt-main-5.15-libboost1.88.yml

xref: https://github.com/conda-forge/qt-main-feedstock/pull/345
[qt-main-libboost1.88.zip](https://github.com/user-attachments/files/21958635/qt-main-libboost1.88.zip) …

Upload qt-5.15 libboost 1.88 for aarch64 and ppc64le

---

requests/reskit-broken.yml

Mark reskit=0.4.0 and 0.4.1 as broken

---

requests/libmagma-devel.yml

Use -devel instead of -dev suffix for magma

---

requests/torchao.yml

allow torchao to run on open gpu server

---

requests/torchao.yml

re-issue torchao request

---

requests/archive-stacrs.yml

Package has been renamed from `stacrs` to `rustac`.
See renaming issue at https://github.com/stac-utils/rustac-py/issues/90. New feedstock is at https://github.com/conda-forge/rustac-feedstock.
Cc @gadomski. Issue about archiving is at https://github.com/conda-forge/stacrs-feedstock/issues/13
but should be patched in the repo data and be marked unbroken …

Archive stacrs-feedstock

---

requests/archive-prefligit.yml

Package has been renamed from `prefligit` to `prek`
See upstream renaming PR at https://github.com/j178/prek/pull/402. New feedstock is at https://github.com/conda-forge/prek-feedstock.
Cc @ocefpaf. Issue about archiving is at https://github.com/conda-forge/prefligit-feedstock/issues/6
* In …

Archive prefligit-feedstock

---

requests/pillow-tests.yml

Add pillow-tests output in pillow-feedstock

---

requests/ibm_db.yml

mark broken: ibm_db-3.2.7 build 1

---

requests/more-des-archive.yml

I am archiving more DES-related feedstocks that I maintain.

feat: more DES packages to archive

---

requests/add-polars-outputs.yml

Add polars-runtime packages to output of polars-feedstock

---

requests/broken-newrelic-11.0.0.yml

mark all newrelic 11.0.0 broken

---

requests/rattler-build.yml

See https://github.com/prefix-dev/rattler-build/issues/1922 …

mark latest rattler-build broken

---

requests/compiler-rt.yml

Add compiler-rt21 etc for compiler-rt-feedstock

---

requests/cached_interpolate.yml

Following instructions from https://github.com/conda-forge/cached_interpolate-feedstock/issues/17 …

Add token reset request for cached_interpolate
