conda-forge/admin-requests

pkgs/grpc127.txt
They are missing a host dependency on `abseil-cpp`.
=> Mark grpc=1.27.0 0 as broken

pkgs/chardet.txt
See: https://github.com/conda-forge/chardet-feedstock/pull/19
=> Mark chardet noarch/chardet-3.0.4-py_1004 broken

pkgs/cupy.txt
We just merged conda-forge/cupy-feedstock#39 and the updated packages are up online, so the buggy ones should be marked as broken.
cc: @jakirkham
=> Remove CuPy v7.2.0 build 0

pkgs/python_36_2020_03_04.txt
It appears the PyPy packages are being pulled in when CPython is expected. This appears to be causing builds to break. For now, let's pull these packages until someone is able to debug this further.
xref: https://github.com/conda-forge/conda-forge.github.io/issues/867#issuecomment-594985046
cc @conda-forge/core
=> Pull Python 3.6 packages with ABI tags

pkgs/gpi.txt
v1.2.5 has a critical bug that prevented building a downstream package.
=> Add v1.2.5 to be marked broken

pkgs/openmpi.txt
In conda-forge/openmpi-feedstock#56 we temporarily disabled (but still built) the support for CUDA awareness. This is to remove the package that enabled the support by default.
cc: @jakirkham @dalcinl
=> Remove the openmpi package with CUDA-awareness enabled

pkgs/spyder.txt
This package has the wrong Jedi dependency. See https://github.com/conda-forge/spyder-feedstock/pull/79 for the fix.
Build 1 is already up with the fix.
=> Mark Spyder 4.1.1 build 0 as broken

pkgs/marshmallow.txt
Release candidates of marshmallow were uploaded to the main label and break
builds for artifacts that depend on `<3`.
Feedstock issue: https://github.com/conda-forge/marshmallow-feedstock/issues/40
=> Mark marshmallow RCs as broken

pkgs/libvorbis.txt
=> Mark libvorbis 1.3.6 build 0 as broken

pkgs/cupy.txt
Not sure if we can leave comments in the txt file, so let me explain here:
- The first two batches are PyPy builds (build numbers 2 & 3 x CUDA versions 9.2, 10.0, 10.1, 10.2). They should be marked broken because of the observation https://github.com/conda-forge/cupy-feedstock/issues/43#issuecomment-603032749.
- The rest two batches are CUDA 10.2 builds (build number 1 & 2 x CPython 3.6, 3.7, 3.8). They are broken because the fp16 headers are missed (conda-forge/cupy-feedstock#41).
@jakirkham, could you confirm the list is correct? Thanks!
=> Remove some CuPy v7.2.0 packages

pkgs/gwosc-0.5.1.txt
gwosc-0.5.1 was released without proper python version information, this was fixed in 0.5.2.
=> Mark gwosc-0.5.1 as broken

pkgs/xeus-python.txt
These packages were build with conda-build 3.19.1 which is [broken](https://github.com/conda/conda-build/pull/3893#discussion_r398439576).
Fixes https://github.com/conda-forge/xeus-python-feedstock/issues/64.
=> Mark some builds of xeus-python as broken

pkgs/svgwrite.txt
Svgwrite 1.4 needs Python 3.6+, and the recipe did not initially remove support for Python 2. This removes the broken package built initially, and the broken package built by a botched effort to fix the issue.
See https://github.com/conda-forge/svgwrite-feedstock/issues/6
@dwhswenson do you agree with marking these packages as broken?
=> svgwrite packages broken by py2 removal

pkgs/openmpi.txt
On OS X we learned that there's a cleanup failure in the fresh v4.0.3, see https://github.com/conda-forge/openmpi-feedstock/pull/57#issuecomment-610678486. We are still discussing what to do for OS X, and in the meanwhile it's best to remove the OS X build.
cc: @dalcinl
=> Remove Open MPI v4.0.3 for OS X

pkgs/terraform-provider-azurerm.txt
=> Mark terraform-provider-azurerm 2.5.0 for win-64 as broken

pkgs/python_osx.txt
cc @conda-forge/python
xref: conda-forge/python-feedstock#339
=> ENH mark osx build of python broken due to extra files

pkgs/cloudpickle.txt
Unfortunately this version is Python 3 only but we did not add the necessary metadata to make it so on the `conda-forge` channel.
cc @ogrisel
=> Mark cloudpickle-1.4.0-pyh9f0ad1d_0 as broken

pkgs/freeimage.txt
we encountered some linker issues with occt. Somehow the older build is used at runtime while the newer package is used during the build.
https://github.com/conda-forge/occt-feedstock/issues/42
=> mark  osx-64/freeimage-3.18.0-h4a8c4bd_0 as broken

pkgs/cupy.txt
Checklist:
The bug is fixed in conda-forge/cupy-feedstock#55 and conda-forge/cupy-feedstock#56.
ping @conda-forge/cupy
=> Remove CuPy builds with a bug in activate/deactivate scripts

pkgs/mesalib_18.0.0_osx.txt
Checklist:
Broken in: https://github.com/conda-forge/mesalib-feedstock/pull/26#issuecomment-614901653
Fixed in: https://github.com/conda-forge/mesalib-feedstock/pull/28
sorry this took so long @muryanto1 
cc @conda-forge/mesalib (i am part of the team too)
<!
!>
=> Remove mesalib since it wasn't tagged with the correct OSX version

pkgs/python-language-server.txt
* Dependencies were not updated correctly in that build. See https://github.com/conda-forge/python-language-server-feedstock/pull/52 and https://github.com/conda-forge/python-language-server-feedstock/pull/53 for the fix.
* Ping @conda-forge/python-language-server about it (I'm part of that team).
=> Mark python-language-server 0.32.0 build0 as broken

pkgs/openjdk.txt
These break `rjava` by putting `libjvm` into a non-standard location: https://github.com/conda-forge/openjdk-feedstock/issues/66
Note that for openjdk11, build 1019 did not run on Azure, so there are no builds for linux-/win-/osx-64 to be marked as broken.
Checklist:
ping @conda-forge/openjdk @CJ-Wright 
PRs to fix the build:
- https://github.com/conda-forge/openjdk-feedstock/pull/70
- https://github.com/conda-forge/openjdk-feedstock/pull/69
=> Mark recent OpenJDK builds as broken

pkgs/arrow-cpp0171.txt, pkgs/pyarrow0171.txt
`arrow-cpp=0.17.1` had an incorrect run_exports that wasn't applied to `pyarrow`. As the scope was limited to both, I just rebuilt them instead of doing a repodata patch.
PRs to fix this:
- https://github.com/conda-forge/pyarrow-feedstock/pull/110
- https://github.com/conda-forge/arrow-cpp-feedstock/pull/144
Checklist:
=> Mark pyarrow=0.17.1=0 as broken

pkgs/xeus.txt
Last release of xeus is not binray compatible, leading to crash of applications linking with it.
The release should be tagged as backward incompatible (even if it is compatible regarding the API).
=> Remove broken xeus 0.23.15

pkgs/sysroot.txt
=> ENH mark sysroot 2.17 for linux-64 as broken

pkgs/sphinxdft.txt
Checklist:
@conda-forge/sphinxdft 
Follow-up to https://github.com/conda-forge/cf-mark-broken/pull/48 
Discussed in: https://github.com/conda-forge/sphinxdft-feedstock/issues/15 
I had to add `CFLAGS="${CFLAGS}"`  and `CPPFLAGS="${CPPFLAGS}"` to make the executables work on systems other than the Azure container they were built in.
=> Remove broken SphinxDFT packages

pkgs/abinit.txt
Checklist: @conda-forge/abinit 
Somehow the tests passed but when using the executable on services like mybinder they fail: 
https://github.com/jan-janssen/abinit-example - https://github.com/conda-forge/abinit-feedstock/issues/5
=> Remove broken abinit executables

pkgs/vaex.txt
Without updating version:
https://github.com/conda-forge/vaex-feedstock/pull/26
Fix:
https://github.com/conda-forge/vaex-feedstock/pull/27
=> fix: accidently re-released 2.6 while pinning to newer versions

pkgs/aiida-core.txt
Checklist:
enforce dependency constraint introduced in https://github.com/conda-forge/aiida-core-feedstock/pull/34
ping @conda-forge/aiida-core
<!--
--!>
=> mark aiida-core=1.2.1 old builds as broken

pkgs/sysroot.txt
=> ENH mark broken for symlinks

pkgs/pyarrow_cuda_9.2.txt
These packages were missing `ignore_run_exports`, which they should have had as they do not need a specific CUDA version (unlike what is typically the case). Instead they build against the oldest supported CUDA version and make that the lower bound. However as `ignore_run_exports` was not applied to `cudatoolkit`, the result was they were pinned to CUDA 9.2, which made it impossible to install them with newer CUDA versions (as was intended). This has since been fixed. However we should mark these packages with the incorrect constraint as `broken` to avoid them getting pulled in.
cc @conda-forge/pyarrow @conda-forge/arrow-cpp
Checklist:
xref: https://github.com/conda-forge/arrow-cpp-feedstock/issues/149
xref: https://github.com/conda-forge/arrow-cpp-feedstock/pull/150
=> Remove `pyarrow` packages restricted to CUDA 9.2

pkgs/simbody.txt
Checklist:
<!--
--!>
I'm submitting the `opensim` package to conda-forge (https://github.com/conda-forge/staged-recipes#11894). This package depends on `simbody >=3.7`, but there are two builds of simbody 3.7 (https://anaconda.org/conda-forge/simbody/files): number 0 and number 1. The automated build is installing build 0, which has a bug in it (https://github.com/conda-forge/simbody-feedstock/issues/33). This PR marks build 0 as broken. Thank you to @wolfv, who suggested I make this PR.
<br><br>
ping @conda-forge/simbody 
<br><br>
What is the process for having this PRs reviewed? I am a maintainer of `simbody-feedstock`.
=> Build number 0 of simbody 3.7 is broken

pkgs/pytest-doctestplus-broken.txt
Checklist:
<!--
--!>
The issue is described at https://github.com/astropy/conda-channel-astropy/issues/181#issuecomment-643259324; essentially, build `0` did not have the correct version restrictions on Python and pytest.
Ping @conda-forge/pytest-doctestplus
=> Mark broken pytest-doctestplus that is missing dependency restrictions

pkgs/root-migration-macos.txt
Closes https://github.com/conda-forge/root_numpy-feedstock/issues/15
Closes https://github.com/conda-forge/rapidsim-feedstock/issues/7
Checklist:
<!--
--!>
=> Mark builds with unpinned macOS SDK as broken

pkgs/broken.txt
Checklist:
<!--
--!>
https://github.com/conda-forge/cdat_info-feedstock/issues/22
=> mark noarch/cdat_info-8.2.1.rc1-py_0.tar.bz2 to be broken

pkgs/cykhash.txt
Removing broken Cykhash package build from conda-forge. More info here: https://github.com/conda-forge/cykhash-feedstock/pull/1
@conda-forge/cykhash 
Checklist:
<!--
--!>
=> Remove broken Cykhash package.

pkgs/scipy-win64.txt
There is (as far as I know) nothing wrong with these packages in an
isolated sense. However when conda is configured according to the
conda-forge documentation: strict channel priority and higher priority
to conda-forge they lock users into the version of scipy provided by
conda-forge (1 for each python version).
As I understand it building scipy on Windows is a cumbersome and manual
process hence only 1 version of scipy has been built for each python
version. Thus users of conda-forge on Windows are locked into scipy 1.3.1
(1.3.2 for python 3.8), whereas it is my understanding that if these
packages are marked as broken conda will resolve to scipy from pkgs/main
which provides both newer and older versions of scipy.
I am by no means sure if this is the right approach, but I think that …
=> Mark win-64 scipy packages as broken.

broken/pytest6.txt
=> ENH mark pytest 6 rc1 as broken

broken/yamllint-124.txt
=> request yamllint 1.24.0 be marked broken

broken/broken.txt
=> mark all recent curl builds for OS X as broken

broken/black.txt
because it includes "vendored" packages (such as attr, regex and click)
(it has been fixed in build number 3)
See https://github.com/conda-forge/black-feedstock/issues/13
* In some cases where the number of users of a package is small or it is used …
=> Mark black-19.10b0-py_2 as broken

broken/blackd.txt, broken/example.txt
it depends on noarch/black-19.10b0-2.tar.bz2 which is itself broken
relevant issue/PR: https://github.com/conda-forge/black-feedstock/issues/13 and  https://github.com/conda-forge/black-feedstock/pull/12
* In some cases where the number of users of …
=> mark noarch/blackd-19.10b0-2.tar.bz2 as broken

broken/gmsh.txt
=> Mark gmsh 4.6.0 OSX build as broken

broken/python-split-windows.txt
The latest Python 3.8.5 builds on Windows are broken as they don't contain the `-script` / `.exe` scripts, see https://github.com/conda-forge/python-feedstock/issues/384
* In some cases where the number of users of a package is small or it is used …
=> Mark Python 3.8.5 build with multiple outputs as broken

broken/chemfiles.txt
As we realized in MDAnalysis/mdanalysis#2798, conda-forge/chemfiles-lib-feedstock#33 had some unintentional fallout: chemfiles now uses the version of libnetcdf provided by conda-forge, butsSince the code was built with libnetcdf==4.7.4, this means the .so file it looks for is libnetcdf.so.18, making the code incompatible with other versions of libnetcdf, in particular 4.6.* which seems to only provides libnetcdf.so.15. To reflect this, I updated dependencies requirements in conda-forge/chemfiles-lib-feedstock#34 and changed the build number to 2. 
I would like to mark the build number 1 as broken to ensure it is no longer picked by conda, while I figure out what is the best solution here.
----
As a side note, the issue appeared when trying to use both netcdf4 and chemfiles in the same …
=> Mark chemfiles 0.9.3 build 1 as broken

broken/python-split-windows-2.txt
Following up #116. It turns out one package was missed: there are two _2 builds, h60c2a47_2 and h5fd99cc_2. The former is also broken, the latter looks OK.
xref https://github.com/conda-forge/tectonic-feedstock/issues/21
cc @conda-forge/python @isuruf
=> Oops, one more Python 3.8.5 build to mark broken

broken/nbclient.txt
Checklist:
We should have released 0.5 instead of 0.4.2 (because of breaking changes).
0.4.2 and 0.4.3 are already yanked in PyPI. Only 0.4.2 was released on conda-forge.
See:
https://github.com/conda-forge/nbclient-feedstock/issues/8
https://github.com/jupyter/nbclient/issues/103
=> nbclient broken build

broken/example.txt, broken/xlwings.txt, not_broken/example.txt
=> mark xlwings 20.0.6 as broken on conda-forge

broken/iota-1.4.19.txt
[Release yanked from pypi](https://pypi.org/project/iota/1.4.19/) because of missing source files …
=> Remove yanked iota 1.4.19 release

broken/pulp-2.3-0.txt
Newer PuLP versions don't include a default solver.
`pulp[version=2.3,build_number=1]` has a dep on external LP solvers now.
cc @johanneskoester @conda-forge/pulp
=> pulp[version=2.3,build_number=0] broken

broken/pyppeteer.txt
Cf https://github.com/conda-forge/pyppeteer-feedstock/pull/6, there was a missing import in the patch.
cc @conda-forge/pyppeteer 
=> Build 0 of Pyppeteer 0.2.2 missed an import in conda-forge patch

broken/xwidgets.txt
Cf https://github.com/conda-forge/xwidgets-feedstock/pull/17
Build number 0 would crash xeus-cling while build 1 does not.
The main difference between the two builds is the version of binutils used. 2.34 vs 2.35.
cc @conda-forge/xwidgets 
Checklist:
=> Build 0 of 0.20.2 broke binary compatibility

pkgs/broken.txt
The package has an incorrect verison specification for grpcio. The package requires grpcio>=1.29.0, but specifies grpcio >=1.8.2, 
cf. https://github.com/conda-forge/google-api-core-feedstock/issues/44
Checklist:
<!--
--!>
=> Remove broken ``google-api-core-grpc-1.20.0``

broken/bullet-200922-builds.txt
Yesterday's `bullet` builds should be marked as `broken` because:
- They are missing the C++ libraries (only contain the pybullet output)
- They were version bumped to match `pybullet`'s version which is out of sync with the C++ `bullet` one 
The broken build was introduced on https://github.com/conda-forge/bullet-feedstock/pull/9 and there's an on-going PR to revert back the previous build method on https://github.com/conda-forge/bullet-feedstock/pull/11.
Ping @conda-forge/bullet 
Checklist:
=> Mark bullet builds of 2020.09.22 as broken

broken/broken.txt
xref.: https://github.com/conda-forge/sip-feedstock/pull/33#issuecomment-700171915
Thanks @isuruf for pointing it out to me. The current conda-build is broken and it is not replacing the prefix correctly on this one on Windows.
Pinging @wolfv.
=> move windows builds of sip to broken

broken/xeus.txt
=> xeus 0.24.2 builds 0 are broken

broken/broken.txt
This one has a bad python dependency. Ideally we should repo-patch it but this is simpler for now.
=> remove noarch/pymc3-3.9.3-py_0.tar.bz2

broken/xvega.txt
The first builds of xvega were not properly constraining the version of nlohmann_json used at runtime based on the version used at build time with `run_exports` and `pin_compatible`. Cf https://github.com/conda-forge/xvega-feedstock/issues/5.
Ping @conda-forge/xvega 
Checklist:
=> Mark first builds of xvega as broken

broken/py39-win-and-pre.txt
=> Mark win-64 py39 as broken due to issues with entrypoints

broken/nose.txt
`nose` can't be fully noarch because it generates different code for Python 2 and Python 3 (dealing with metaclasses). See details in https://github.com/conda-forge/nose-feedstock/issues/23.
New build in https://github.com/conda-forge/nose-feedstock/pull/24.
ping @conda-forge/nose
Checklist:
=> Broken: noarch nose (build 1005)

broken/pytest.txt
=> Mark pytest noarch build as broken

broken/broken.txt
This is a duplicate of redis-py and not the same package as redis from defaults. We should remove this ASAP.
=> remove redis

broken/cudatoolkit.txt
As we haven't built all of the `cudatoolkit` versions yet and we use strict channel priority, having just one `cudatoolkit` package show up with one version causes trouble installing from `defaults` currently. For now just mark this as `broken` until we are able to build out the other versions as well. Then we can move this back.
xref: https://github.com/conda-forge/ucx-split-feedstock/pull/80#issuecomment-708864031
cc @conda-forge/cudatoolkit
not …
=> Temporarily mark `cudatoolkit` as `broken`

broken/zlib.txt
=> mark zlib aarch64 build with same hash as linux-64 as broken

broken/broken.txt
This build number has bad dependencies and are causing trouble in downstream packages. Ideally we should repopatch it but bn 1 is fixes this and I'm not sure it is worth doing the patch.
=> remove aiohttp bn 0

broken/ovito-windows.txt
=> Mark ovito 3 windows broken because of wrong install path.

broken/django-3.1.2.txt
Checklist:
---
I noticed something weird in https://github.com/conda-forge/prospector-feedstock/pull/15 where the PR was[ broken during verification because a django dependency (asgiref) was not present with the correct version](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=234149&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d):
```
The following NEW packages will be INSTALLED:
asgiref:               3.3.0-py_0               conda-forge
django:                3.1.2-py_0               conda-forge
(..)
django 3.1.2 has requirement asgiref~=3.2.10, but you have asgiref 3.3.0.
```
You can reproduce this by creating a new conda environment with
```
$ conda create -p thing -c conda-forge --strict-channel-priority pylint-django …
```
=> yank django 3.1.2-0 release

broken/grpcio-health-checking.txt
=> Mark as broken noarch/grpcio-health-checking-1.33.2-py*_0.tar.bz2 (bad protobuf pin)

broken/mpifx.txt
- upstream switched from year based versioning (20.x) to semantic versioning 1.0
- only uploaded this one version so far, probably easier to mark as broken as to introduce a version epoch
- no dependents in regro/libcfgraph found
- https://github.com/conda-forge/mpifx-feedstock/pull/3 creates the new 1.0 version
--- …
=> Mark mpifx-20.1 versions as broken

broken/mambawin.txt
we got some bug reports here: https://github.com/mamba-org/mamba/issues/586
* We …
=> move mamba 0.7.0 on win to broken

broken/r-magrittr.txt
These packages should not have been noarch. …
=> Mark old r-magrittr 2.0.1 packages as broken.

broken/example.txt, broken/openexr_250
There was an so name change between 2.5.0 and 2.5.1
https://github.com/conda-forge/conda-forge-pinning-feedstock/pulls?q=is%3Apr+is%3Aclosed
We want to pin to 2.X, but this version needs to be omitted.
=> Mark openexr 2.5.0 as broken

broken/tqdm.txt
Checklist:
ping @conda-forge/tqdm @jan-janssen 
tqdm added `setuptools_scm[toml]` to their `setup_requires`, which resulted in a `0.0.0` in the metadata on disk after `pip install`. the automerge on `tqdm-feedstock` shipped this version. This causes all subsequent `pip checks` to fail if any constraint is put on `tqdm`, causing issues for downstream builds. 
Related issues:
- original downstream work-around https://github.com/conda-forge/dagster-feedstock/pull/87/files#r528398464
- issue on tqdm feedstock https://github.com/conda-forge/tqdm-feedstock/issues/84
- pr to fix with correct `host` requirements: https://github.com/conda-forge/tqdm-feedstock/pull/85
- my kingdom for a `pip check --setup-requires .`
- bad metadata PR …
=> Mark tqdm-4.53.0-pyhd3deb0d_0 as broken

broken/meshpy-9c29d28f.txt
Hi @conda-forge/meshpy! I am the friendly conda-forge webservice! …
=> mark invalid packages for meshpy as broken

broken/autovizwidget-53e96986.txt
Hi @conda-forge/autovizwidget! I am the friendly conda-forge webservice! …
=> mark invalid packages for autovizwidget as broken

broken/compas-b7272e8f.txt
Hi @conda-forge/compas! I am the friendly conda-forge webservice! …
=> mark invalid packages for compas as broken

broken/libmemcached-981ca610.txt
Hi @conda-forge/libmemcached! I am the friendly conda-forge webservice! …
=> mark invalid packages for libmemcached as broken

broken/apache-libcloud-b149f8e3.txt
Hi @conda-forge/apache-libcloud! I am the friendly conda-forge webservice! …
=> mark invalid packages for apache-libcloud as broken

broken/signac-dashboard-cf984ca7.txt
Hi @conda-forge/signac-dashboard! I am the friendly conda-forge webservice! …
=> mark invalid packages for signac-dashboard as broken

broken/tpot.txt
`tpot` upstream added a hard dependency on `py-xgboost`, and automerge shipped it (because we had it as a test dep). 
practically, this means `tpot-0.11.6.post1` will be the last version that works on windows until somebody (not me, :weary:) picks up [this PR](https://github.com/conda-forge/xgboost-feedstock/pull/43). Sigh.
- tracking issue: https://github.com/conda-forge/tpot-feedstock/issues/30
- `1` with correct deps, just merged: https://github.com/conda-forge/tpot-feedstock/pull/31
- also removes automerge
- this has happened before (torch, but that got rolled back)
- we can put it back if...
- `conda-build` adds the ability to do multiple test sections (e.g. a dedicated one for `pip check`)
- we do multiple outputs, so we can `pip` check `tpot-core`
- …
=> mark tpot-0.11.6.post2-*_0 broken

broken/importlib_-_metadata.txt
importlib-metadata added a dependency for pythons older than 3.8, and `pip check` didn't pick it up.
- fix:
- https://github.com/conda-forge/importlib_metadata-feedstock/pull/55
- upstream change:
- https://github.com/python/importlib_metadata/blame/6955586a940f6bfda0c662039f4c7b7cc0876c9e/setup.cfg#L22
:bellhop_bell: @conda-forge/importlib-metadata  @conda-forge/importlib_metadata 
Checklist:
=> mark importlib-metadata-3.3.0-*_0.tar.bz2 broken

broken/aubio-1723455d.txt
Hi @conda-forge/aubio! I am the friendly conda-forge webservice! …
=> mark invalid packages for aubio as broken

broken/conda-devenv-f11ce133.txt
Hi @conda-forge/conda-devenv! I am the friendly conda-forge webservice! …
=> mark invalid packages for conda-devenv as broken

broken/dbxfs-de5f4fa6.txt
Hi @conda-forge/dbxfs! I am the friendly conda-forge webservice! …
=> mark invalid packages for dbxfs as broken

broken/pyemd-685a9e5b.txt
Hi @conda-forge/pyemd! I am the friendly conda-forge webservice! …
=> mark invalid packages for pyemd as broken

broken/pymapd-81be4af7.txt
Hi @conda-forge/pymapd! I am the friendly conda-forge webservice! …
=> mark invalid packages for pymapd as broken

broken/pyamg-eb1ca2d9.txt
Hi @conda-forge/pyamg! I am the friendly conda-forge webservice! …
=> mark invalid packages for pyamg as broken

broken/gridfill-86a826e2.txt
Hi @conda-forge/gridfill! I am the friendly conda-forge webservice! …
=> mark invalid packages for gridfill as broken

broken/metakernel-6a8cb69d.txt
Hi @conda-forge/metakernel! I am the friendly conda-forge webservice! …
=> mark invalid packages for metakernel as broken

broken/jsoncpp-6e1c7b06.txt
Hi @conda-forge/jsoncpp! I am the friendly conda-forge webservice! …
=> mark invalid packages for jsoncpp as broken

broken/flask-rest-orm-8b97d2f9.txt
Hi @conda-forge/flask-rest-orm! I am the friendly conda-forge webservice! …
=> mark invalid packages for flask-rest-orm as broken

broken/sentry-sdk-1ae062cc.txt
Hi @conda-forge/sentry-sdk! I am the friendly conda-forge webservice! …
=> mark invalid packages for sentry-sdk as broken

broken/libarchive-769469e0.txt
Hi @conda-forge/libarchive! I am the friendly conda-forge webservice! …
=> mark invalid packages for libarchive as broken

broken/gensim-e49e5d83.txt
Hi @conda-forge/gensim! I am the friendly conda-forge webservice! …
=> mark invalid packages for gensim as broken

broken/flask-creole-d6be97cd.txt
Hi @conda-forge/flask-creole! I am the friendly conda-forge webservice! …
=> mark invalid packages for flask-creole as broken

broken/flask-debugtoolbar-f4481d63.txt
Hi @conda-forge/flask-debugtoolbar! I am the friendly conda-forge webservice! …
=> mark invalid packages for flask-debugtoolbar as broken

broken/google-api-core-cf6921e2.txt
Hi @conda-forge/google-api-core! I am the friendly conda-forge webservice! …
=> mark invalid packages for google-api-core as broken

broken/cling.txt
We failed to bump the build number in a cling rebuild, which ended up with some platforms having two builds of cling with the same version and build numbers, but not the same hash.
The newest builds were done against a new version of gcc. Now we have a higher build number available for the gcc 9 flavor of it.
Fixes https://github.com/conda-forge/cling-feedstock/issues/45
=> Duplicate builds of cling

broken/broken.txt
This package is not installable on Windows due to a bad manifest. See https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/253336/logs/63
=> remove noarch openquake.engine-3.10.1 pyhd8ed1ab_1

broken/broken.txt
Build 0 has the same issue as 1. See #205
=> remove noarch openquake.engine-3.10.1 build 0

broken/pytest-check-links.txt
Checklist:
The out-of-order version `4.3.3` (missing a leading `0.`) was yanked:
https://pypi.org/project/pytest-check-links/#history
This prevented the actual `0.4.3` from being built (though it was released that day) as well as the later `0.4.4`, which has now been merged in https://github.com/conda-forge/pytest-check-links-feedstock/pull/3 .... but won't be found because of the `4` line. Marking this broken should fix this up!
:bellhop_bell:  @conda-forge/pytest-check-links (which is me)
=> mark noarch/pytest-check-links-4.3.3-py_0.tar.bz2 broken

broken/cudnn.txt, broken/pytest-check-links.txt
=> mark cudnn=8.0.5.39=*_0 packages as broken

broken/libopencv.txt
These packages are broken because they contain the pypy instead of cpython modules.
Related to https://github.com/conda-forge/opencv-feedstock/pull/259 …
=> Remove mislabeled libopencv binaries

broken/msmpi.txt
=> Mark msmpi as broken

broken/opencv_build_6.txt
A pypy conflict is giving us trouble with Python 3.6
https://github.com/conda-forge/opencv-feedstock/pull/259
https://github.com/conda-forge/opencv-feedstock/issues/258
In these cases, it is likely that the pypy build gets installed for cpython making it unusable by the end user.
Work is underway to remedy the siutation
https://github.com/conda-forge/opencv-feedstock/pull/261#issuecomment-756746555
not technically broken and should not be marked as …
=> Mark python 3.6 builds for opencv broken

broken/pypy.txt
=> mark pypy 7.3.3 older build numbers as broken

broken/clangdev.txt
As per issue https://github.com/conda-forge/clangdev-feedstock/issues/126, the cling-v0.8 tag was pointing at the wrong commit (this was fixed since).
Besides, we should have increased the build number for that build.
=> Latest builds of clangdev 5.0 are broken

broken/nbformat-5.1.0.txt
=> mark nbformat-5.1.0-*_0.tar.bz2 broken

broken/ipython-7.19.0_0.txt
=> Mark ipython-7.19.0_0 as broken

broken/r_lattice.txt
Fixes https://github.com/conda-forge/r-lattice-feedstock/issues/14 with the PR addressing the build script https://github.com/conda-forge/r-lattice-feedstock/pull/15 …
=> Mark osx-64 build of osx-arm64 r-lattice as broken

broken/clang.txt
=> ENH mark latest clang activation broken

broken/xtl.txt
xtl 0.6.24 is broken as explained in the [dedicated issue](https://github.com/conda-forge/xtl-feedstock/issues/88)
=> Flag xtl 0.6.24 a broken

broken/poppler089.txt
Recent builds of @conda-forge/poppler 0.89 are missing the headers for some of its libraries and thus lead to downstream issues when building as outlined in https://github.com/conda-forge/poppler-feedstock/issues/101.
This has been fixed in https://github.com/conda-forge/poppler-feedstock/pull/100 for future build numbers. Only Unix builds were affected, thus the Windows builds don't need to be marked as broken.
not technically broken and should not …
=> Mark builds of poppler 0.89 as broken that are missing headers

broken/orjson_3.4.7_0.txt
The contents haven't been compiled correctly (are osx-64)
xref: https://github.com/conda-forge/orjson-feedstock/pull/28#issuecomment-766280636
the maintainers only, we …
=> Mark osx-arm64 builds of orjson 3.4.7 as broken

broken/robotframework-seleniumlibrary.txt
=> mark as broken robotframework-seleniumlibrary-5.0.0-*_0.tar.bz2

broken/cpython.txt
=> Mark osx-arm64 cpython build 3.8.5-h05baefb_9_cpython as broken.

broken/ipykernel_noarch.txt
For some reason conda picks up up an old noarch build of ipykernel (5.1.0) and it happen that this package is broken on windows; working fine on linux.
To reproduce (specify ipykernel=5.1.0 if a more recent version is pickep up)
```
conda create -n test python=3.8 jupyter_console
```
```
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... 
Warning: 2 possible package resolutions (only showing differing packages):
- defaults/noarch::ipykernel-5.1.0-pyh24bf2e0_0, defaults/win-64::pyzmq-22.0.3-py38h7a0e47e_0
- defaults/win-64::ipykernel-5.4.3-py38hc5df569_0, defaults/win-64::pyzmq-20.0.0-py38h7a0e47e_1done
environment location: C:\Users\Eric\HyperSpy-bundle\envs\test2
added / updated specs:
- jupyter_console
- python=3.8
The following …
```
=> Mark ipykernel 5.1.0 noarch as broken

broken/ipykernel_5.0.0_noarch.txt
Similar as #231, but for ipykernel 5.0.0 noarch packages - obviously, conda is now picking up [one of the these two](https://anaconda.org/conda-forge/ipykernel/files?version=5.0.0)!
From looking at https://conda.anaconda.org/conda-forge/noarch/repodata.json.bz2, there shouldn't be any other!
but should be patched in …
=> Mark ipykernel 5.0.0 noarch as broken

broken/srm-ifce.txt
Marks builds which were mis-compiled by the newer gsoap release. A workaround was applied in: https://github.com/conda-forge/srm-ifce-feedstock/pull/2
The bug is being investigated upstream in https://its.cern.ch/jira/browse/DMC-1240
=> Mark some srm-ifce builds as broken

broken/faiss-gpu.txt, broken/faiss-proc.txt, broken/faiss.txt, broken/libfaiss.txt
=> mark initial win+cuda builds for faiss as broken

broken/spacy-model-en_core_web-3.0.0_0.txt
=> mark noarch/spacy-model-en_core_web_*_0 broken

broken/freud-osx-arm64.txt
I added osx-arm64 support to freud in the PR linked below, but the builds segfault on import. It is not clear what causes the problem, but I want to remove the packages for now. https://github.com/conda-forge/freud-feedstock/pull/34/files
Checklist:
Segfault output:
```
(lldb) run -c "import freud"
Process 62231 launched: '~/miniforge3/bin/python' (arm64)
Process 62231 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x10)
frame #0: 0x0000000101b9f028 libpython3.9.dylib`_PyObject_GC_Alloc + 56
libpython3.9.dylib`_PyObject_GC_Alloc:
->  0x101b9f028 <+56>: ldr    x22, [x19, #0x10]
0x101b9f02c <+60>: add    x2, x1, #0x10             ; =0x10 
0x101b9f030 <+64>: adrp   x8, 309 …
```
=> Remove freud osx-arm64 packages (fail on import)

broken/weldx.txt
This version does not have important data packages included due to a mistake during packaging. So this renders this particular version unusable (and meta-data patching wouldn't help, right?).
Note that I'm one the weldx packages maintainers (fyi @CagtayFabry)
Checklist:
=> mark weldx-0.3.2 as broken

broken/libwebp-base.txt
This two builds have the following problems:
* Missing `libwepmux.dll` file, causing problems such as https://github.com/conda-forge/freeimage-feedstock/issues/27 and fixed in https://github.com/conda-forge/libwebp-base-feedstock/pull/5
* Missing headers, fixed in https://github.com/conda-forge/libwebp-base-feedstock/pull/6
FYI @conda-forge/freeimage @conda-forge/libwebp-base @jakirkham @adam-urbanczyk  
Checklist:
=> Mark some recent Windows libwebp-base packages as broken

broken/jupyter_client.txt
=> Mark jupyter_client=6.1.13 as broken

not_broken/faiss-proc.txt
Follow-up to #235 after https://github.com/conda-forge/faiss-split-feedstock/pull/32 has been merged.
In #235, I included the `faiss-proc` selector package as well, but since this does not get a new build number / version / hash, it just needs to be reinstated, now that builds have arrived.
=> mark faiss-proc unbroken for win+cuda again

broken/bullet-cpp.txt
Some `bullet-cpp` on Windows had the right MT option (instead of MD as the rest of conda-forge Windows libraries). This has been fixed in https://github.com/conda-forge/bullet-feedstock/pull/33 , and this PR mark the previous builds as broken.
cc @conda-forge/bullet 
Checklist:
=> Mark recent bullet-cpp Windows builds with wrong runtime options as broken

broken/jupyter_client.txt
=> Mark jupyter_client=6.2.0 as broken

broken/librmm0.txt
These accidentally included some `spdlog` components that shouldn't have been in there. We've since fixed the issue ( https://github.com/conda-forge/librmm-feedstock/pull/3 ). Though it would be good to remove these packages so that users environments don't accidentally get clobbered by them
cc @isuruf @kkraus14 @leofang
=> Mark `librmm` build number `0` as broken

broken/msmpi.txt
In the 4 listed builds we accidentally packaged 32-bit binaries, causing issues in downstream (mpi4py/mpi4py#19). In addition, in the first 2 builds of each version, `MSMPI_VER` was not correctly patched, so all users would see the default version (0x100), which lacks tons of features that MS-MPI actually implemented. All these are fixed after conda-forge/msmpi-feedstock#11.
The lack of the patching for `MSMPI_VER` also exists in earlier builds, but at least their binaries worked so it's ok to not mark them as broken.
cc: @conda-forge/msmpi @conda-forge/mpi4py 
instead of marking packages as broken. This alternative workflow …
=> Mark `msmpi` 10.1.1 builds 3, 4 and 10.1.2 builds 0, 1 as broken

broken/xsimd.txt
=> addes xsimd 7.5.1 as broken

broken/pyopencl-2021.2.txt
Checklist:
These (ostensibly broken) versions of the pyopencl 2021.2 package somehow made it onto the [archive](https://anaconda.org/conda-forge/pyopencl), when, in reality, I'm still working on that package: https://github.com/conda-forge/pyopencl-feedstock/pull/64. I suspect, but don't know, that these uploads may have been caused by my mistakenly pushing to a branch of the feedstock at first: https://github.com/conda-forge/pyopencl-feedstock/pull/63 (Sorry!). I closed that PR right away, but I guess that may not have prevented damage from being done.
The packages themselves may be mostly fine, however 2021.2 also had a [bug](https://github.com/inducer/pyopencl/pull/474) that caused me …
=> Remove broken pyopencl 2021.2

broken/libcxx.txt
=> ENH mark libcxx 12 as broken for osx

broken/xeus.txt
The library binary version is wrong, this breaks downstream packages which cannot find the xeus library anymore.
=> Marked xeus 1.0.2 as broken

broken/libsolv.txt
the combination of the two patches I recently created is having some not-so-nice effect on solutions. 
E.g: https://github.com/mamba-org/mamba/issues/986
I am going to fix this and push another libsolv build later this week.
=> mark recent libsolv build as broken

broken/python38.txt
=> mark latest python 3.8 on osx-64 as broken

broken/xeus.txt
=> Marked xeus 1.0.2 and 1.0.3 as broken on OSX platforms

broken/msmpi.txt
=> Mark msmpi binary builds as broken

broken/pari.txt
=> Remove pari without correct run_exports

broken/botocore.txt
I screwed up and merged the version bump before tightening the python requirements (which was done in build 1)
don't want weird environments using build 0 to be possible
* In some cases where the number of users of a package is small or it is used …
=> mark botocore 1.21.0 build 0 as broken

broken/lemon-non-shared.txt
All builds prior to the `_2` (linux, osx), and `_3` (win) were static builds in lemon. This means they were useful in context of building other packages. Currently [the solver seems to pick up](https://github.com/conda-forge/lemon-feedstock/issues/23) the non-shared versions of this library when installing vigra (afaik the only downstream dependency of lemon).
So - I don't think there will be any negative side effects to removing the non-shared libs here.
I'm not sure if this qualifies to adding the `broken` label. (I probably would remove main and add `static_lib` or something like this).
Checklist:
ping @conda-forge/lemon
=> move all non-shared-builds of lemon to broken

broken/galsim.txt
=> mark galsim 2.3.2 build 0 broken due to wrong library IDs

broken/pinocchio.txt
Hello,
Pinocchio version 2.9.1 is a pre-release, and not meant for stable release. However, conda still released this version, which might break some downstream packages. 
In order to keep users from installing 2.9.1 accidentally, we wish to mark it as broken and keep 2.6.2 as the last stable release version.
This PR is a continuation of https://github.com/conda-forge/pinocchio-feedstock/pull/62 in order to revert this change.
Best,Rohan
ping @conda-forge/pinocchio-feedstock
* Packages with requirements/metadata that are too …
=> [pinocchio] mark version 2.9.1 as broken

broken/libkml.txt
This one was broken on Windows. The next build number is fixed but it would be nice to prevent users from easily installing this one. xref.: https://github.com/conda-forge/gdal-feedstock/pull/508
=> remove win-64/libkml-1.3.0-h9859afa_1013.tar.bz2

broken/pypy.txt
=> mark pypy latest build as broken

broken/ppc64le-elf.txt
This is due to patchelf being buggy on ppc64le such that the binaries are corrupted, see 
- https://github.com/conda-forge/cutensor-feedstock/issues/16
- https://github.com/conda-forge/cudnn-feedstock/issues/31
- https://github.com/conda-forge/patchelf-feedstock/issues/21
Ping @conda-forge/cudnn @conda-forge/cutensor.
Checklist:
=> Mark cuDNN and cuTENSOR on ppc64le as broken

broken/polyagamma.txt
Checklist:
Build 0 of version 1.3.2b3 of polyagamma is broken for Unix systems as outline in https://github.com/conda-forge/polyagamma-feedstock/issues/1 . Build 1 was issued [shortly after](https://github.com/conda-forge/polyagamma-feedstock/pull/2) so I think build 0 should be pulled.
Im the maintainer of the feedstock.
=> Remove build 0 of unix platforms for polyagamma v1.3.2b3

broken/broken_puma_builds.txt
=> Removing first build because broken

broken/libssh2.txt
=> Marking libssh2=1.10.0 as broken on ARM OSx

broken/prophet.txt
The initial noarch version of the Prophet package is broken, throwing the error `AttributeError: 'StanModel' object has no attribute 'fit_class'`.
See https://github.com/conda-forge/prophet-feedstock/issues/1 for a description of the issues.
Checklist:
ping @conda-forge/prophet
=> Mark noarch Prophet package as broken

broken/broken_parallelcluster_3.txt
The dependency aws-cdk is missing in conda, create-cluster, build-image commands don't work. 
ping @conda-forge/aws-parallelcluster
Signed-off-by: Yulei Wang <yuleiwan@amazon.com>
* In some cases where the number of users of a package is small or it …
=> Mark aws-parallelcluster v3.0.0 as broken

broken/llvmdev-cling.txt
These cling variants of clangdev should track the cling feature.
Fixes https://github.com/conda-forge/clangdev-feedstock/issues/151
ping @conda-forge/clangdev
=> Remove cling variant broken builds

broken/nbconvert-6.2.0rc0.txt
We released nbconvert 6.2.0rc0 in the main channel instead of using the rc label by mistake. See https://github.com/conda-forge/nbconvert-feedstock/issues/58#issuecomment-920274460 and the file list at https://anaconda.org/conda-forge/nbconvert/files
but should be patched in the repo data and be marked unbroken …
=> Mark nbconvert 6.2.0rc0 on main as broken

broken/python38.txt
Similar to https://github.com/conda-forge/admin-requests/pull/267
Python 3.8 does not support using the macOS 11 SDK while also building to support 10.9.
the …
=> Mark osx-64/python-3.8.10-hb51f844_2_cpython as broken 

broken/nbconvert-6.2.0rc0.txt
*This PR is a continuation of #307. Apparently some of the packages hadn't built yet when #307 was submitted*
We released nbconvert 6.2.0rc0 in the main channel instead of using the rc label by mistake. See https://github.com/conda-forge/nbconvert-feedstock/issues/58#issuecomment-920274460 and the file list at https://anaconda.org/conda-forge/nbconvert/files
* Packages with missing metadata …
=> Mark nbconvert 6.2.0rc0 on main channel as broken

broken/curl.txt
This bug https://github.com/curl/curl/issues/7738 is solved in 7.79.1 and that one will be in the channel soon (https://github.com/conda-forge/curl-feedstock/pull/96) but we need to remove the 7.79.0 to avoid headaches.
=> remove curl 7.79.0

broken/libdap4.txt
@isuruf these two have a run_exports that does not match the pinning. I guess it makes sense to move them to broken, right?
=> remove libdap4 builds 0 and 1 for the 3.20.6 version

broken/libssh2_1.10.0_1.txt
We run into https://github.com/conda-forge/libssh2-feedstock/issues/46 with https://github.com/conda-forge/libssh2-feedstock/pull/47 . This breaks a lot of things, especially new installations of `mamba`.
FYI @conda-forge/libssh2  …
=> Mark libssh2=1.10.0=1 broken on osx-arm64

broken/libtiff.txt
Fixes https://github.com/conda-forge/gdal-feedstock/issues/537. This build number is missing a codec that is used by downstream dependencies. Mamba works great b/c it pulls latest bn but conda optimizer does not prioritize build numbers yet.
=> remove build number 0 of libtiff 4.3.0

broken/uwsift.txt
=> Mark uwsift 1.2.0 py36 packages as broken

broken/piff.txt
=> ENh mark piff 1.1.0 as broken

broken/broken_wren.txt
=> marked win packages of wren broken since the there was a missing *.lib file

broken/compass.txt
=> ENH mark compass-interface outputs broken

broken/python-3.10-without-conda-symlink-workaround.txt
ref:
- https://github.com/conda-forge/python-feedstock/pull/511
cc @conda-forge/python
The first builds of `python=3.10` did not carry the workaround for https://github.com/conda/conda/issues/10969 added in the PR referenced above.
----
* In some …
=> Broken: python=3.10 w/o conda symlink workaround

broken/pygdp.txt
This package is noarch without a proper constraint. It should not install in py>36 b/c it uses async, a reserved keyword in py37. as a variable.
Pinging @rsignell-usgs who reported this.
=> remove noarch/pygdp-2.1.2-py_0.tar.bz2

broken/libcint_0.txt
=> Add libcint_0 to broken

broken/jaxlib.txt
@xhochy this removes all jaxlib builds for osx-arm64. Can you review it?
=> remove all osx-arm64 builds of jaxlib

broken/cf-units.txt
This post release has the same code as the pre-post one but with extra metadata that broken packages builds. Any build number update on cf-units-3.0.1 would be hindered if we keep the cf-units-3.0.1.post here.
=> remove all cf-units post release

.github/workflows/repodata_patching.yml, update_repodata_patches.py
=> ENH cronjob for repodata patching

broken/nbclient.txt
A `jupyter execute` command was added to `nbclient`, and in v0.5.6 `jupyter run` was added as an alias to `jupyter execute`. This conflicts with `jupyter_client`'s `jupyter run`. I'm planning to remove `nbclient`'s `jupyter run` in v0.5.9.
See https://github.com/jupyter/nbclient/pull/173.
ping @conda-forge/nbclient
Checklist:
=> Mark nbclient 0.5.8 as broken

update_repodata_patches.py
=> BUG do not post empty diffs

broken/dotnet-sdk.txt
=> Mark `dotnet-sdk` 6.0.100 build 0 as broken

broken/pennylane-lightning.txt, broken/pennylane.txt
=> Mark Pennylane as broken

broken/rdt_and_sdmetrics.txt
=> mark broken packages for rdt and sdmetrics

broken/antlr4-python3-runtime.txt
=> Add antlr4-python3-runtime to broken

broken/ipycanvas.txt
ipycanvas 0.10.0 is not working, whether it's installed via pip or conda. See https://github.com/martinRenou/ipycanvas/pull/234 …
=> Mark ipycanvas 0.10.0 as broken

broken/mesalib_21_with_gl.txt
These packages were accentally built with `GL.so` which overrides the user's system GL.so file causing all opengl to be software rendered. This is almost certainly not what people want when they are trying to use scientific visualization software that depends on GL.so
See https://github.com/conda-forge/mesalib-feedstock/pull/40#issuecomment-984808054
And an issue raised by a user: https://github.com/conda-forge/mesalib-feedstock/issues/16#issuecomment-984504934
@conda-forge/mesalib do you support marking all 21 builds as broken? …
=> Mark mesalib with gl builds as broken

broken/ipyleaflet.txt
=> Mark ipyleaflet 0.15.0 as broken

broken/mistune-2.0.0.txt
Checklist:
`mistune 2.0.0` dropped recently, and has a few thousand downloads.
A key downstream, `nbconvert`, does not support `mistune 2.0.0`:
- it has correct mistune pin starting from https://github.com/conda-forge/nbconvert-feedstock/pull/54 but there are hundreds of older builds that are broken
This is probably blocked by a review by @conda-forge/mistune of:
- https://github.com/conda-forge/mistune-feedstock/pull/23 which adds `run_constrained` for nbconvert to align with the above pin, 
- it is currently unsatisfiable, but...
- would allow for a future release to be relax its pin https://github.com/jupyter/nbconvert/issues/1685
=> Make mistune-2.0.0_0 broken

broken/tomli-2.0.0-py36.txt
Checklist:
tomli 2.0.0 dropped Python 3.6 support. This has been fixed in build 1 (see https://github.com/conda-forge/tomli-feedstock/pull/11).
Ping @thewchan
=> Mark tomli-2.0.0-pyhd8ed1ab_0 as broken

broken/orange3.txt
=> Mark current orange3 packages for python310 as broken

broken/fmt.txt
fmt-8.1.0 introduced a breaking ABI change. This breaks packages that
were built against fmt-8.0.1 when they use fmt-8.1.0 at runtime.
The issue has been reported upstream and a patch is waiting to be
merged. We might create a patched 8.1.0 build or wait for 8.1.1; the
relevant discussion is at
https://github.com/conda-forge/fmt-feedstock/pull/28 and
https://github.com/fmtlib/fmt/pull/2696.
An alternative here would be to patch the repodata and tell the <8.1.0
build to use !=8.1.0_0. However, it does not seem to be the correct
approach to me to exclude a single build with a constraint.
=> Mark fmt-8.1.0 as broken

broken/dynaconf.txt
I'm marking this package as broken since it had a too loose constraint on the python version (see issue https://github.com/conda-forge/dynaconf-feedstock/issues/5, solved in https://github.com/conda-forge/dynaconf-feedstock/pull/6 with build 1).
Please excuse me, this is likely not the best way to fix it but I had no mental energy to learn how to create repodata patches at the moment...
Checklist:
=> mark dynaconf 3.1.7 build 0 for removal

broken/filelock.txt
It should not support Python 3.6, see https://github.com/conda-forge/filelock-feedstock/issues/30.
=> Remove filelock 3.4.2 build 0

broken/julia.txt
These two packages accidentally got uploaded with label main instead of label julia_dev. I have since rerendered the branch to correctly point to julia_dev. Please remove this in the meanwhile. Thank you and sorry about this messup.
Relevant PR: https://github.com/conda-forge/julia-feedstock/pull/181
Relevant branch: https://github.com/conda-forge/julia-feedstock/tree/dev
cc @conda-forge/julia (especially @mkitti)
---
More details about how the problem happened:
There was a disconnect between the PR and the dev branch. I mistakenly created the dev branch without rerendering, insteading relying on rerendering in the PR. So the rerendering calls in the PR didn't change the files inside .ci_support. I could have avoided this mess if I followed the description on conda-forge knowledge base …
=> removing julia 1.8.0 dev uploads from label main

broken/nbclient.txt
Checklist:
Lower Python pin should follow nbclient 0.5.10 on PyPI.
See https://github.com/jupyter/nbclient/issues/194
=> Mark nbclient 0.5.10 build 0 as broken

broken/flake8.txt
Checklist:
----
Problem
* That build doesn't require the right version of `importlib-metadata`, which is `<4.3` for Python 3.7. Build 1 solved that problem.
* This problem was identified by @xhochy in https://github.com/conda-forge/spyder-terminal-feedstock/pull/25#issuecomment-1003160831, so I'm making the PR he thinks is necessary to solve it.
* Pinging @conda-forge/flake8 about this.
=> Mark flake8 4.0.1 build 0 as broken

.github/PULL_REQUEST_TEMPLATE.md
=> ENH add more details on how marking things broken works

broken/sphinx.txt
Checklist:
----
* Sphinx 4.4.0 depends on `importlib-metadata >=4.4`, but that dependency was added in build 1 (see https://github.com/conda-forge/sphinx-feedstock/pull/116). So, build 0 is broken and needs to be marked as such.
* Due to this problem, conda/mamba can't resolve the right constraints when you need packages that depend on different versions of `importlib-metadata`, such as flake8 4.0.1 (`importlib-metadata < 4.3`) and Sphinx 4.4.0.
* This was detected in  conda-forge/spyder-feedstock#123
* Pinging @conda-forge/sphinx about this.
=> Mark sphinx 4.4.0 build 0 as broken

broken/ryven.txt
=> ryven is broken - dependencies do not work with Python 3.10

broken/splipy_1_5_6_noarch.txt
=> mark noarch version broken

broken/mpi-fort.txt
This specific build of mpi-fort is uninstallable because it requires the corresponding compiler build which doesn't exist? Perhaps that build was already removed for being broken, but they forgot to remove this package too? …
=> Remove uninstallable mpifort

broken/verilator_12.txt
In conda-forge/verilator-feedstock#13, I screwed up and uploaded packages with the same build number.
not sure if this is a valid reason to mark them broken but I'm starting with this because patching repodata doesn't
seem like it can fix the build number being wrong in the filename.
but should be patched in the repo …
=> verilator-feedstock#13 uploaded new packages with same build number

broken/abseil-cpp.txt
The new shared windows builds of https://github.com/conda-forge/abseil-cpp-feedstock/pull/25 caused some issues for arrow-cpp; mark them broken to unjam other people's CIs (and then figure out what went wrong and how to fix it).
=> mark shared windows build of abseil-cpp as broken

broken/openmm.txt
We merged https://github.com/conda-forge/openmm-feedstock/pull/70 two days ago to build Python 3.10 packages for OpenMM.  In addition to building Python 3.10 packages, it also rebuilt the packages for all earlier Python versions.  It appears that all the newly built packages for Mac are broken.  They produce segfaults when anyone tries to use them.  We don't understand why, but the old packages work correctly and the new packages built from the same tag fail.  Presumably this is due to a change to something else in the conda-forge build infrastructure?  See https://github.com/openmm/openmm/issues/3495.
Checklist:
=> OpenMM packages for Mac are broken

broken/voms.txt
It seems that gsoap doesn't work correctly when cross-compiling and spits out bizzare SSL errors. Hopefully VOMS won't last too much longer before it can be archived so I'll just switch to native builds (https://github.com/conda-forge/voms-feedstock/pull/11).
=> Mark cross-compiled VOMS binaries as broken

broken/example.txt, broken/reaktoro.txt
=> Set latest Reaktoro package to broken state

broken/qhub.txt
=> Set latest builds of Qhub as broken

broken/fix_805_validation_omniorb-libs.txt
Closes https://github.com/conda-forge/artifact-validation/issues/805
Closes https://github.com/conda-forge/artifact-validation/issues/806
Closes https://github.com/conda-forge/artifact-validation/issues/807
These `omniorb-libs` packages included components of `openssl` that shouldn't have been included. This would result in clobbering `openssl`'s files and potentially issues for packages built on top of them. So here they are marked `broken` to ensure they don't get picked up. The feedstock will need to address this issue further to ensure new packages don't have the same issue.
cc @beckermr @conda-forge/core @conda-forge/omniorb …
=> Fix validation error with `omniorb-libs`

broken/poppler.txt
Follow up to https://github.com/conda-forge/poppler-feedstock/pull/125
=> mark poppler 22.01.0 on win as broken

broken/broken-fiona.txt
See https://github.com/conda-forge/fiona-feedstock/pull/191 and https://github.com/conda-forge/fiona-feedstock/issues/192: after the latest rebuild of fiona (it was only a rerendering, no package version update), there have been several reports of the package being broken on Windows. I don't know why this is happening, but until we figure this out, it might be nice to mark this as broken (since the previous build of the same version works just fine for Windows users).
Checklist:
=> Mark latest Fiona build for Windows as broken

broken/nbconvert-645-1.txt
On @conda-forge/nbconvert,  splitting off `nbconvert` into `nbconvert(|-core|-pandoc)` has created the situation where `nbconvert 5` can be installed next to `nbconvert-core 6.4.5`, and the latter seems to clobber the upstream files.
We fixed the issue with a `_2` build, now up on a.o...
> **TBD: and it appears to be available from CDN.**
- files on a.o: https://anaconda.org/conda-forge/nbconvert/files?version=6.4.5
- already had 25k downloads :cold_sweat:
- noted on https://github.com/conda-forge/nbconvert-feedstock/issues/73
- fixed on https://github.com/conda-forge/nbconvert-feedstock/pull/74
- conda-build issue reported https://github.com/conda/conda-build/issues/4415
- upstream bug https://github.com/conda-forge/nbconvert-feedstock/issues/75
=> mark nbconvert*-6.4.5-*_1 broken

broken/vigra_1030.txt
Vigra is quite old and hasn't been updating cmake files for a while.
This makes migrations tricky.
I fixed openexr support in https://github.com/conda-forge/vigra-feedstock/pull/92
* In some cases where the number of users of a package is small or …
=> Mark Vigra without openexr as broken

broken/libignition-fuel-tools-yaml.txt
=> Mark as broken libignition-fuel-tools builds against broken libyaml builds

token_reset/moviepy.txt
=> Request moviepy token reset

broken/sklearn.txt
Reference: <https://github.com/conda-forge/scikit-learn-feedstock/pull/182>
I added a legacy build of sklearn for py310. Turns out it was unwanted, and sklearn with py310 is unsupported for versions <1.0. Hence the request to mark as broken.
Files to remove are from 2 days ago [here](https://anaconda.org/conda-forge/scikit-learn/files).
Checklist:
ping @conda-forge/scikit-learn
=> Remove new scikit-learn<1.0 for py310

broken/message-ix.txt
Conda doesn't install the latest message-ix package on windows-latest by default (current version 3.4.0), but rather installs message-ix version 1.0.0, please see [here](https://github.com/iiasa/message_ix/runs/5001443802?check_suite_focus=true) and the corresponding workflow step [here](https://github.com/iiasa/message_ix/blob/main/.github/workflows/conda.yaml#L71). Relevant PR https://github.com/iiasa/message_ix/pull/541.
Ping @conda-forge/message-ix 
Checklist:
=> Mark message-ix 1.0.0 as broken

broken/napari-0.4.15-0.txt
=> mark napari-0.4.15-0 as broken

broken/landlab.txt
=> Mark landlab 2.5.0 build 0 builds as broken

broken/qt-webengine-osx-arm64.txt
See https://github.com/conda-forge/qt-webengine-feedstock/pull/5
/cc @hmaarrfk
=> Mark qt-webengine packages for osx-arm64 as broken

broken/openssl.txt
This is an optional-but-IMO-good-idea companion to https://github.com/conda-forge/openssl-feedstock/pull/100, due to the [potential](https://guidovranken.com/2022/06/27/notes-on-openssl-remote-memory-corruption/) to exploit 3.0.4.
Since this only affects AVX512, we don't need to do this on aarch64/ppc64le/arm64.
Filled by:
```
mamba repoquery search openssl=3.0.4 -p linux-64 --json | grep url | awk -F'conda-forge/' '{print $2}'  | awk -F'",' '{print $1}'
mamba repoquery search openssl=3.0.4 -p osx-64 --json | grep url | awk -F'conda-forge/' '{print $2}'  | awk -F'",' '{print $1}'
mamba repoquery search openssl=3.0.4 -p win-64 --json | grep url | awk -F'conda-forge/' '{print $2}'  | awk -F'",' '{print $1}'
```
=> mark current openssl 3.0.4 builds as broken on x86

broken/requests.txt
`requests` has an optional runtime dependency on `chardet <5`, but this wasn't encoded in the feedstock for 2.28.0-0. This has been fixed in build 1.  See https://github.com/conda-forge/requests-feedstock/pull/54 and https://github.com/conda-forge/requests-feedstock/pull/54#issuecomment-1167251225. 
Ping @conda-forge/requests
Checklist:
=> Mark requests-2.28.0-pyhd8ed1ab_0 as broken

broken/jupyter_client.txt
The `jupyter_client` package allows too low of a version of `pyzmq` in build 0, and this leads to a failed build in https://github.com/conda-forge/rise-feedstock/issues/38. The issue was fixed for build 1 in https://github.com/conda-forge/jupyter_client-feedstock/pull/77, but build 0 was never marked as broken.
I have opened the issue https://github.com/conda-forge/jupyter_client-feedstock/issues/80.
not technically broken and should not be marked …
=> Mark jupyter_client-7.3.2_0 as broken

broken/libxml2.txt
=> Mark recent libxml2 Windows builds with wrong .pc file as broken

broken/aeppl.txt
Last night we [converted aeppl to be multi-output](https://github.com/conda-forge/aeppl-feedstock/pull/30) with `aeppl-base` and `aeppl`. The resulting packages were supposed to be `noarch: python`, and I had this in the top-level `build:` block, but unfortunately the resulting package was not noarch, and was instead built for 3.10 on linux/osx/win.
I subsequently [fixed this](https://github.com/conda-forge/aeppl-feedstock/pull/32) by adding noarch to each build block. (I really don't understand the logic here, this feels buggy to me, but anyways, it's working now.)
So in this PR I want to clean up the non-noarch builds. They were only available overnight, and there is now a replacement package, so I expect the impact to be minimal.
ping @conda-forge/aeppl
Guidelines for marking packages …
=> Mark aeppl 0.0.31_1 as broken

broken/scienceplots.txt
=> Remove scienceplots packages

broken/cruft.txt
There was a recent version update which was automerged although the dependencies changed.
I have since [removed automerge](https://github.com/conda-forge/cruft-feedstock/pull/20) and [corrected the dependencies](https://github.com/conda-forge/cruft-feedstock/pull/21). The old build is only 12 hours old, so I'd like to mark it as broken.
* Packages with missing metadata can be marked as broken …
=> Mark cruft 2.11.0_0 as broken

broken/attrs-22.1.0_0.txt
Broken because [attrs dropped Python 2.7 support in 22.1.0](https://github.com/python-attrs/attrs/releases/tag/22.1.0), but this didn't get changed in the conda-forge recipe.
PR to fix the recipe: https://github.com/conda-forge/attrs-feedstock/pull/27
ping @conda-forge/attrs 
---
Checklist:
=> add broken attrs 22.1.0 build 0

broken/unyt.txt
=> mark broken unyt builds

broken/riverrem-broken-versions.txt
Previous versions will solve environment to use scipy version >1.6 and using deprecated "n_jobs" kwarg of scipy.spatial.cKDTree.query. Version 1.0.3 has been rewritten to fix this issue using the new kwarg convention and require scipy>1.6.0, so older versions will be marked as broken.
but should be patched in the …
=> mark riverrem versions <1.0.3 as broken

broken/grpc-cpp.txt
Requested by @kkraus14 in https://github.com/conda-forge/grpc-cpp-feedstock/issues/214. Unfortunately, grpc sets abseil as a required link interface. @hmaarrfk and I are trying to fix this correctly in https://github.com/conda-forge/grpc-cpp-feedstock/pull/213, in the meantime there have been stopgap fixes to stop the bleeding. These don't get picked up by the solver however, so we need to mark the old builds (without the explicit run-requirement on abseil) as broken.
queries:
```
mamba repoquery search grpc-cpp=1.46.4 -p win-64 --json | grep url | awk -F'conda-forge/' '{print $2}'  | awk -F'",' '{print $1}
mamba repoquery search grpc-cpp=1.47 -p win-64 --json | grep url | awk -F'conda-forge/' '{print $2}'  | awk -F'",' '{print $1}
mamba repoquery search grpc-cpp=1.48 -p win-64 --json | …
```
=> broken grpc-cpp builds due to implicit abseil run-dep

broken/xeus_octave.txt
Cf https://github.com/conda-forge/xeus_octave-feedstock/issues/6
=> Mark builds of xeus_octave that do not pin octave as broken

broken/libprotobuf.txt
There's some fall-out from building libprotobuf via cmake, see post-merge comments in https://github.com/conda-forge/libprotobuf-feedstock/pull/128.
It's bizarre to me because the SO-numbers match (see this [comment](https://github.com/conda-forge/libprotobuf-feedstock/pull/128#issuecomment-1238947823)), but mark it broken for now to not further break people.
~Original reporter (@peastman) mentioned specifically that:~
> ~This only happens on x86, not ARM.~
Queries used:
```
mamba repoquery search libprotobuf=3.20.1=*_2 -p osx-64 --json | grep url | awk -F'conda-forge/' '{print $2}'  | awk -F'",' '{print $1}
mamba repoquery search libprotobuf=3.21.5=*_1 -p osx-64 --json | grep url | awk -F'conda-forge/' '{print $2}'  | awk -F'",' '{print $1}
```
and so on for the other platforms
=> mark cmake-built libprotobuf's broken on unix

broken/grpc-cpp.txt
As part of the fall-out from https://github.com/conda-forge/grpc-cpp-feedstock/pull/213 & friends (basically, private linkage for static builds turns public...) there are still some problematic windows builds that don't have a run-export on abseil, and can therefore be co-installed with older abseil versions, but then fail because the static grpc-build still needs `libabseil-static` with the same ABI to be present as at build-time.
I verified the affected build numbers in the blame per branch, happy to provide more details if requested.
Queries used
```
mamba repoquery search grpc-cpp=1.46.4=*_4 -p win-64 --json | grep url | awk -F'conda-forge/' '{print $2}'  | awk -F'",' '{print $1}
mamba repoquery search grpc-cpp=1.46.4=*_5 -p win-64 --json | grep url | awk -F'conda-forge/' '{print $2}' …
```
=> mark grpc-cpp builds with no abseil run-export as broken

broken/assimp.txt
As discussed in https://github.com/conda-forge/assimp-feedstock/issues/45#issuecomment-1242976661, there was an uninteded ABI breakage due to a spurious change of library name in the updated (due to rerendering) from VS2017 to VS2019 .
This has been solved in https://github.com/conda-forge/assimp-feedstock/pull/47, but there is still around the build with wrong names, this PR marks it as broken.
fyi @conda-forge/assimp 
Checklist:
=> Mark as broken assimp windows package with changed name

broken/cachecontrol.txt
This version was yanked from PyPI. See https://pypi.org/project/CacheControl/0.12.12/
=> remove cachecontrol

broken/evaluator.txt
I accidentally did pushed to upstream version of a feedstock instead of my fork, which to my surprise caused an RC build to be published without the appropriate labelling. The rest of the process went fine (https://github.com/conda-forge/openff-evaluator-feedstock/pull/20) and there is an RC build online with the RC label I intended. I am afraid the solver may pull down this RC build, which includes many API breaks and new dependency constraints, instead of a full release.
I asked in the gitter how to go about getting this fixed, since I cannot do it myself. It was suggested that I ask to mark it as broken instead of patching the repodata as repodata patches do not update labels.
Thanks!
=> Mark OpenFF Evaluator RC package pushed to wrong label

broken/dask-kubernetes.txt
Automerge has been publishing bad packages for a while but let's remove at least this last one to be sure only 1 build number is correct.
=> mark dask-kubernetes as broken

broken/noarch_clisops_092.txt
=> Mark CLISOPS 0.9.2 as broken

broken/spdlog.txt
The spdlog builds `1.10.0-*_1` have a different ABI w.r.t. `1.10.0-*_0`, resulting in runtime errors if `1.10.0-*_1` is installed with libraries and executables that were builded and linked against `1.10.0-*_0`, see https://github.com/conda-forge/spdlog-feedstock/issues/53 for more info.
but should be patched in the …
=> Mark spdlog builds 1.10.0-*_1 as broken to ABI breakage

broken/grpc-cpp.txt, broken/libgrpc.txt
There were two oversights in https://github.com/conda-forge/grpc-cpp-feedstock/pull/245, and unfortunately they will continue to trap the solver unless the builds are marked broken:
* missing `run_constrained` to avoid co-installation of new `libgrpc` with old `grpc-cpp`
* missing host-dep on openssl in the wrapper (which therefore collided because the hashes were the same)
~This should ideally wait for about an hour so the builds from https://github.com/conda-forge/grpc-cpp-feedstock/pull/254 are live.~ All good
Queries:
```
mamba repoquery search libgrpc=1.49 -p linux-64 --json | grep url | awk -F'conda-forge/' '{print $2}'  | awk -F'",' '{print $1}
mamba repoquery search libgrpc=1.49 -p linux-aarch64 --json | grep url | awk -F'conda-forge/' '{print $2}'  | awk -F'",' '{print $1}
mamba …
```
=> mark _0 builds of grpc-cpp 1.49 as broken

broken/dask-2022.10.1.txt
Dask Distributed 2022.10.1 introduced a change to its compatibility handling for unsupported Bokeh versions such that any environment without `bokeh` would cause Distributed clusters to fail to initalize; this is outlined in https://github.com/dask/community/issues/284 and has since been resolved with 2022.10.2.
This PR marks `distributed` 2022.10.1 as broken, as well as the associated `dask` and `dask-core` packages.
Checklist:
=> Mark Dask 2022.10.1 packages as broken

broken/xeus-cling.txt
=> Marked xeus-cling 0.14 as broken

broken/pytango.txt
=> Remove pytango 9.4.0rc1 from main channel

broken/qgrid-broken.txt
When installing qgrid as part of an existing environment, it will solve to the _3 version. This version is broken with changes to upstream packages (jupyter-nbclassic). 
See:
https://github.com/conda-forge/qgrid-feedstock/pull/37
https://github.com/conda-forge/qgrid-feedstock/issues/35
https://github.com/quantopian/qgrid/issues/378
https://github.com/tardis-sn/tardis/issues/2137
```ERROR conda.core.link:_execute(701): An error occurred while installing package 'conda-forge::qgrid-1.3.1-pyhd8ed1ab_3'.
Rolling back transaction: done
LinkError: post-link script failed for package conda-forge::qgrid-1.3.1-pyhd8ed1ab_3
location of failed script: /home/afullard/.conda/envs/tardis2/bin/.qgrid-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout: 
stderr: 
return code: 1
``` …
=> Marks qgrid as broken due to failing post-link script

broken/ipykernel.txt
=> Mark ipykernel 6.18.0 as broken

broken/googleapis-common-protos.txt
This build vendored files from other packages installed alongside the main package.
See https://github.com/conda-forge/googleapis-common-protos-feedstock/issues/50 for more details.
The broken build was: https://github.com/conda-forge/googleapis-common-protos-feedstock/pull/49
This was fixed in build 2: https://github.com/conda-forge/googleapis-common-protos-feedstock/pull/51 …
=> Mark googleapis-common-protos 1.57.0 build 1 as broken

broken/googleapis-common-protos.txt
Unfortunately, after #517 I build another package with the same problem.
Build 2 (as well as build 1 already marked as broken) vendored files from other packages installed alongside the main package.
See https://github.com/conda-forge/googleapis-common-protos-feedstock/issues/50 for more details.
The broken build was: https://github.com/conda-forge/googleapis-common-protos-feedstock/pull/51
This was fixed (for real this time) in build 3: https://github.com/conda-forge/googleapis-common-protos-feedstock/pull/52. I have downloaded the resulting package and verified that it does not contain protobuf files.
instead of marking …
=> Mark googleapis-common-protos 1.57.0 build 2 as broken

broken/ipykernel.txt
=> Mark ipykernel 6.18.1 and 6.18.2 as broken (yanked on pypi)

broken/conda-22.11.0.txt
=> Mark conda=22.11.0 as broken

broken/pytest-jupyter.txt
Checklist:
Description:
When doing an `outputs` build of `0.5.3`, I missed `noarch: python` in the subpackages. 
- https://github.com/conda-forge/pytest-jupyter-feedstock/pull/3
This yielded a bunch of super broken builds that also vendored `pytest` and much of the `jupyter` stack.
- https://github.com/conda-forge/pytest-jupyter-feedstock/issues/4
A successive build of `0.6.0` somehow made the problem worse.
A fix has been deployed:
- https://github.com/conda-forge/pytest-jupyter-feedstock/pull/3
@conda-forge/jupyter_server _mea culpa_ :crying_cat_face:
=> mark pytest-jupyter-* 0.5.3*_1, 0.6.0*_0 broken

broken/networkx.txt
=> Add broken networkx build

broken/cachecontrol.txt
The upstream package with this version was yanked from PyPI.
https://github.com/conda-forge/cachecontrol-feedstock/issues/15
Attn: @ocefpaf 
the maintainers only, we …
=> Mark cachecontrol v0.12.12 as broken

broken/bw2calc.txt
=> Mark initial noarch version of bw2calc as broken

broken/isce3.txt
ISCE3 was missing a dependency on libgdal. This is now fixed in the feedstock, but older builds can still be used accidentally, as pointed out here: https://github.com/conda-forge/isce3-feedstock/issues/33#issuecomment-1336261954
This might be fixable by patching the package metadata - this is my first time dealing with a broken build, advice is appreciated.
* Packages with missing metadata …
=> Mark isce3-0.8.0-*_3 broken

README.md
Although there is an example, it is not obvious from the description (See #546).
=> Clarify to include package name in file contents for resetting token

broken/bespokefit.txt
This is a small follow-on to #605, in which I mistakenly forgot that there were multiple builds of that release. The justification is the same as the issue persists with both builds. I apologize for neglecting this detail and I am very grateful to the maintainers' time and all they do.
As before:
> We have a massively broken version of one of our packages released into the world, which was not caught in tests and triggered by changes in a dependency. I am one of the maintainers of this package.
* Packages with requirements/metadata that are too strict but otherwise work …
=> Mark as broken all builds of a broken release of OpenFF BespokeFit

token_reset/opusfile.txt
Fix https://github.com/conda-forge/opusfile-feedstock/issues/8
=> reset token for opusfile

token_reset/hdbpp-es.txt
The new build of hdbpp-es failed to upload. I guess this is linked to https://github.com/conda-forge/status/issues/137
The feedstock has 2 outputs: `hdbpp-es` and `hdbpp-es-dbg`.
I put both in the same `hdbpp-es.txt` file but I'm not sure this is correct or if I should create two txt files.
=> Reset token for hdbpp-es-feedstock

token_reset/conda-forge-pinning.txt
Builds on the feedstock are failing, which is why migrations aren't opened/closed correctly.
This one should be pretty urgent. CC @beckermr @jakirkham
=> reset token for conda-forge-pinning

broken/configobj.txt
=> Mark configobj 5.0.7 as broken

broken/sphinx-autodoc-typehints.txt
This version was yanked from PyPI. Closes https://github.com/conda-forge/sphinx-autodoc-typehints-feedstock/issues/39
=> remove sphinx-autodoc-typehints

broken/jupyter_server_ydoc.txt
`jupyter_server_ydoc` v0.6.2 pins `jupyter_ydoc >=0.3.0` and should have been released as v0.7.0 in order not to break `jupyterlab` v3.6.0.
`jupyter_server_ydoc` v0.6.2 has been yanked [on PyPI](https://pypi.org/project/jupyter-server-ydoc/0.6.2).
ping @conda-forge/jupyter_server, @hbcarlos, @fcollonval
=> Mark jupyter_server_ydoc=0.6.2 as broken

broken/pangeo-dask.txt
=> Mark 2023.1.4 pangeo-dask version as broken 

broken/libxml2.txt
This one have some bad activation scripts. See https://github.com/conda-forge/libxml2-feedstock/pull/87#issuecomment-1456302688
=> remove libxml2-2.10.3 bn 2

broken/xbitinfo.txt
These dev releases were published on main, have the wrong Python dependency, and were superseded but the correct version that implements both Python and Julia packages. Marking them as broken is the easiest thing here b/c it is not worth patching them.
=> remove bad xbitinfo versions

broken/cctools.txt, broken/cctools_osx-64.txt, broken/cctools_osx-arm64.txt, broken/ld64.txt, broken/ld64_osx-64.txt, broken/ld64_osx-arm64.txt
Since llvm 15 started depending on libxml2 (which itself depends on a few libs), conda twists itself into a knot when trying to rebuild one of those dependencies. Even though this feedstock [pins](https://github.com/conda-forge/cctools-and-ld64-feedstock/blob/main/recipe/meta.yaml#L70) `llvm` to an exact version, which in turn [exports](https://github.com/conda-forge/llvmdev-feedstock/blob/main/recipe/meta.yaml#L105) `libllvm<same_major>`, the actual clang-implementation doesn't [pin](https://github.com/conda-forge/clang-compiler-activation-feedstock/blob/main/recipe/meta.yaml#L39-L40) cctools.
After fixing this inhttps://github.com/conda-forge/cctools-and-ld64-feedstock/pull/59, mark the old builds as broken so the resolver can't get caught in this trap (=package with too loose …
=> mark cctools build number 12 broken on osx

broken/xeus-zmq.txt
As per https://github.com/conda-forge/xeus-zmq-feedstock/issues/11.
Fixes https://github.com/conda-forge/xeus-zmq-feedstock/issues/11/.
=> Mark xeus-zmq 1.0.2 build 0 as broken

broken/openmmtools0215_build_0.txt
The `openmmtools` 0.21.5 package in [noarch/openmmtools-0.21.5-pyhd8ed1ab_0.tar.bz2](https://anaconda.org/conda-forge/openmmtools/0.21.5/download/noarch/openmmtools-0.21.5-pyhd8ed1ab_0.tar.bz2) is broken since it doesn't work with the upstream dependencies, we want to avoid this build of the package to be pulled by users. The `*_1` build should be used instead.
=> Specifying broken files for openmmtools pkg build

broken/cutensor.txt
My apology. I made a bad judgement call in merging https://github.com/conda-forge/cutensor-feedstock/pull/40 prematurely. Because the infrastructure is not yet set up (using `cuda-version` to create mutual exclusion between different CUDA versions), that PR breaks production environments on pre-CUDA 12. 
As a bandaid solution, please kindly help merge this PR to mark the offending packages as broken. Once the infra is ready, we can unmark it.
Sorry again for the trouble and inconvenience. It's been a long day...
cc: @conda-forge/cutensor, @jakirkham @kkraus14 @jaimergp @beckermr 
instead of marking packages as broken. This alternative workflow makes environments more …
=> Tentatively mark cuTENSOR 1.7.0 build 1 as broken

broken/kokkos-kernels.txt
Kokkos-kernels v3.7.01 should depend on Kokkos v3.7.01, but it depends on v4.0.0. 
=> Remove broken kokkos-kernels build #0.

not_broken/cutensor.txt
Now that we have `cuda-version` constraints set up properly:
- https://github.com/conda-forge/cuda-version-feedstock/pull/6
- https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/435
The previous PR (https://github.com/conda-forge/admin-requests/pull/701) can be reverted.
cc: @conda-forge/cutensor @jakirkham @kkraus14 for vis
but should …
=> Revert marking cuTENSOR v1.7.0 build 1 as broken

broken/r-cli.txt
We identified `r-cli-feedstock` was generating non-functional builds due to upstream no longer being `noarch` compatible. The recipe was corrected, but the broken builds are still on `main`. This marks them as broken.
Related Issues:
- https://github.com/conda-forge/r-cli-feedstock/issues/20
- https://github.com/conda-forge/r-tidyverse-feedstock/issues/13
I am on the maintainer team, but for good measure we can also ping @conda-forge/r-cli 
=> r-cli v3 noarchs broken

archive/cpp-opentelemetry-api.txt
The [feedstock](https://github.com/conda-forge/cpp-opentelemetry-api-feedstock) was unified with another in https://github.com/conda-forge/cpp-opentelemetry-sdk-feedstock/pull/46 and is now obsolete
=> archive cpp-opentelemetry-api

archive/articdb.txt, broken/articdb.txt
The name of the package is arcticdb, not articdb.
cc @DerThorsten @jjerphan @JohanMabille.
=> Package name typo: archive feedstock and mark packages as broken

broken/xeus.txt
The current package leads to crashes on OSX if kernels using it do not change their implementation.
=> Marked xeus 3.1.0 as broken

broken/pint.txt
=> Mark pint 0.22 build 0 as broken as python 3.8 support was dropped

broken/pluggy.txt
The new style hook wrappers unintentionally broke some downstream projects, including `conda` itself.
We decided to yank this release and reassess how to release this new feature:
https://pypi.org/project/pluggy/1.1.0
https://github.com/pytest-dev/pluggy/issues/403
ping @conda-forge/pluggy 
Note: I'm on of the maintainers of the conda package and a `pluggy` maintainer as well.
=> Mark pluggy 1.1.0 as broken

broken/kokkos3-cuda.txt
I published CUDA builds for Kokkos 3 targeting arch 3.5 + PTX, but Kokkos does not support CUDA binaries with PTX until Kokkos 4. Conda requires building conda packages for all CUDA compatible major architectures or building for the lowest and including PTX for forward compatability because Conda does not track CUDA archs, however, Kokkos only supports targeting one CUDA arch at build time, so it must be built with PTX.
The effect of leaving these broken packages is that programs that link against them but are running on hardware later than 3.5 may stall/hang OR the runtime will raise an error about the library being compiled for the wrong architecture.
Discussion of this and other Kokkos with CUDA packaging issues are here: 
https://github.com/conda-forge/kokkos-feedstock/issues/21
* We …
=> Remove broken kokkos cuda packages

broken/patchelf18.txt
Fixes https://github.com/conda-forge/conda-smithy/issues/1737
This version of `patchelf` regularly corrupts libraries it is patching. Upstream is aware of the issue, but it is not yet fixed. Suggesting we mark these broken to avoid further issues in packages that wind up broken because of `patchelf`.
xref: https://github.com/NixOS/patchelf/issues/492
<hr>
but …
=> Mark `patchelf` version `0.18.0` broken

broken/napari0417.txt
I was overeager in merging an update to the napari feedstock updating the
dependencies of 0.4.17: conda-forge/napari-feedstock#50. There are two
problems:
- I incorrectly specified a requirement
- I had updated the build number locally but neglected to push that change
before merging the PR 🤦
This PR marks the artifacts of that PR as broken.
CC @jaimergp @conda-forge/napari
=> Mark new napari 0.4.17 builds as broken

broken/joblib.txt
Version 1.3.0 no longer supports Python 3.6:
https://github.com/joblib/joblib/blob/1.3.0/pyproject.toml#L28
This has been fixed in https://github.com/conda-forge/joblib-feedstock/pull/38 already, but the broken package is still available which causes problems for downstream users using Python 3.6.
=> Yank noarch/joblib-1.3.0 b0

broken/spacy-transformers-1.3.0.txt
=> Mark spacy-transformers 1.3.0 as broken

broken/shakenbreak.txt
Hi! 
We are kindly requesting removal of old `CalVer` versions of `ShakeNBreak` on `conda-forge` (https://github.com/conda-forge/shakenbreak-feedstock). These packages were unfortunately published with calendar versioning, e.g. `2023.6.23`. This has been corrected with the recent switch to `SemVer`, but because of `SemVer` version ordering, `2023.6.23` still shows up as the latest and default version for the package which is problematic for installing users.
Checked, and no dependents in `regro/libcfgraph` were found. To our knowledge, no other packages depend on these versions of `ShakeNBreak`, our latest version is compatible with a wider range of python versions (`3.8` - `3.11`) with looser dependency requirements, and worst case scenario if one of these versions is required by someone …
=> Remove `CalVer` packages for `ShakeNBreak`

broken/shakenbreak.txt
Reverts conda-forge/admin-requests#788
=> Revert "Remove `CalVer` packages for `ShakeNBreak`"

archive_feedstock.py, mark_broken.py, token_reset.py
Currently, the README tells contributors to add files with a .txt extension, and the [fast finish](https://github.com/conda-forge/admin-requests/blob/f688e516044556305fa160ba632017ac383aafee/.github/workflows/main.yml#L32-L36) code in the CI also looks for txt files. However, the python scripts in the root folder will happily glob any file regardless of extension. This can lead to [careless users submitting PR's](https://github.com/conda-forge/admin-requests/pull/794) that [look okay in the PR's CI run](https://github.com/conda-forge/admin-requests/actions/runs/5864699118/job/15901307635#step:4:1) but then [don't do anything when merged to main](https://github.com/conda-forge/admin-requests/actions/runs/5865447965/job/15902394960#step:5:44).
This change makes sure that the Python scripts …
=> Only glob files with txt extension

broken/iris_main_remove_v3x0x0rc0.txt
The problem was created by a malformed push to the iris-feedstock/release-candidate branch.
This has mistakenly created an RC version package in the iris "main"  channel.
=> Req to remove rc build from main iris channel.

broken/libnetcdf.txt
Same as https://github.com/conda-forge/admin-requests/pull/761. We need to address this before another build number of this version goes out :-/
=> mark win-64/libnetcdf-4.9.2-nompi_hefebadb_110 as broken

broken/libprotobuf_python_headers.txt
I created this new @conda-forge/libprotobuf output and immediately after merge, I realised that a `run_constraint` is missing. The packages have not yet been used anywhere and thus I went with the simple approach of marking them as broken. Fix for the underlying problem is here: https://github.com/conda-forge/libprotobuf-feedstock/pull/177
but should be …
=> Mark initial build of libprotobuf_python_headers as broken

broken/conda-smithy.txt
This release has an issue with the swap_file on azure and that was fixed in https://github.com/conda-forge/conda-smithy/pull/1759
Previous releases and the next one should be OK.
=> mark latest conda-smithy as broken

broken/blas-devel.txt, broken/blas.txt, broken/libblas.txt, broken/libcblas.txt, broken/liblapack.txt, broken/liblapacke.txt
We recently merged openblas 0.3.24 [support](https://github.com/conda-forge/blas-feedstock/pull/104) in the blas meta-package. This seems to have lead to pretty severe fall-out in some scenarios for numpy & scipy (complete garbage results), see https://github.com/scipy/scipy/issues/19210 & https://github.com/numpy/numpy/issues/24660. 
Packages are all from the same [job](https://app.travis-ci.com/github/conda-forge/blas-feedstock/jobs/609267019), quoted from log at the end:
```
anaconda upload \
/home/conda/feedstock_root/build_artifacts/linux-aarch64/libblas-3.9.0-18_linuxaarch64_openblas.conda \
/home/conda/feedstock_root/build_artifacts/linux-aarch64/libcblas-3.9.0-18_linuxaarch64_openblas.conda \
/home/conda/feedstock_root/build_artifacts/linux-aarch64/liblapack-3.9.0-18_linuxaarch64_o …
```
=> mark blas 2.118 broken on linux-aarch

broken/boa.txt
=> mark boa=0.15.1=1 as broken

broken/soupsieve.txt
Mark soupsieve 2.5 build 0 as broken since it doesn't work on Python 3.6 environments (Build 1 fix this by adding `python >=3.8` to the recipe).
=> Mark soupsieve 2.5_0 as broken

broken/configspace.txt
ConfigSpace 0.7.2 is broken and has been removed by the authors from pypi (see https://github.com/automl/ConfigSpace/issues/336 or https://github.com/automl/ConfigSpace/issues/338).
ping @conda-forge/configspace
=> Remove configspace-0.7.2

broken/graphql-core.txt
=> mark graphql-core 3.3.0a3 broken

broken/patchelf18_2.txt
This version of `patchelf` regularly corrupts libraries it is patching (on Linux; don't know about macOS). Upstream is aware of the issue, but it is not yet fixed. Also we encountered this before and marked packages `broken`. However some new ones were published recently.  So this marks the new Linux packages broken to avoid further issues due to this `patchelf` version (have left macOS packages alone).
Fixes https://github.com/conda-forge/patchelf-feedstock/issues/41
xref: https://github.com/conda-forge/admin-requests/pull/746
xref: https://github.com/NixOS/patchelf/issues/492
<hr>
instead of marking packages as broken. This alternative workflow makes environments more …
=> Mark `patchelf` version 0.18.0 `linux*` broken (pt. 2)

environment.yml
`conda-forge-repodata-patches` uses `typing.Annotated`, which needs Python 3.9. This has been failing for the last 3 months 😬
=> Bump to Python 3.9

environment.yml
Follow up for #860. Type `|` unions require Python 3.10.
=> Bump to Python 3.10

broken/conda-index.txt
This package was unintentionally published from a branch build and should not be used.
See: https://github.com/conda-forge/conda-index-feedstock/pull/1#issuecomment-1791113088
@conda-forge/conda-index
=> Mark linux-64 conda-index 0.3.0 broken

broken/pytest-asyncio.txt
There were numerous issues with pytest-asyncio v0.22.0:
* https://github.com/pytest-dev/pytest-asyncio/issues/654
* https://github.com/pytest-dev/pytest-asyncio/issues/655
* https://github.com/pytest-dev/pytest-asyncio/issues/657
Since https://github.com/pytest-dev/pytest-asyncio/issues/657 was not achievable with the implementation approach taken in pytest-asyncio v0.22, the version was yanked from PyPI a few hours after release:
https://pypi.org/project/pytest-asyncio/#history
@conda-forge/pytest-asyncio
=> Mark pytest-asyncio v0.22.0 as broken.

requests/joseki.yml
Version 2.4 of the Joseki package contains features that were not intended for public release. This was fixed in v2.5 and later.
cc @conda-forge/joseki …
=> Mark Joseki v2.4 package as broken

requests/joseki.yml
Versions 2.2 and 2.3 of the Joseki package contains features that were not intended for public release. This was fixed in v2.5 and later.
cc @conda-forge/joseki
xref: https://github.com/conda-forge/admin-requests/pull/891
* In some cases where the number of users of a package is small or it …
=> joseki 2.2 and 2.3 noarch build is broken

requests/pandas-profiling.yml
pandas-profiling has been deprecated and replaced by [ydata-profiling](https://github.com/ydataai/ydata-profiling).
This [issue](https://github.com/conda-forge/pandas-profiling-feedstock/issues/51) has been raised in the feedstock.
=> Add request to archive pandas-profiling

requests/fmt.yml
This is a follow-up of an unintentional ABI-break in fmt 10.2 that caused mamba to break, see https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/628.
However, upstream merged a fix that restores the missing symbol, and we already have new builds for that on the fmt feedstock: https://github.com/conda-forge/fmt-feedstock/pull/42
This marks `_0` as broken on windows (the missing symbol isn't used on unix), which will allow to keep using the major-level ABI-pinning of `fmt`.
CC @jaimergp @saraedum @bdice
=> mark _0 build of fmt 10.2.0 as broken on windows

requests/deltalake-015x-broken.yml
Due to some combination of https://github.com/conda-forge/conda-smithy/issues/1827 and https://github.com/PyO3/maturin/issues/1911, the initial builds of deltalake 0.15.x for linux-64 contained no members, tracked by https://github.com/conda-forge/deltalake-feedstock/issues/18.
This has now been resolved for 0.15.1 with https://github.com/conda-forge/deltalake-feedstock/pull/20, and it doesn't seem like there's a strong desire to backport this fix to 0.15.0.
cc @dhirschfeld
not technically …
=> Mark old deltalake linux-64 0.15.x builds broken

requests/azure-core-cpp-1-11.yml
See https://github.com/conda-forge/tiledb-feedstock/issues/228#issuecomment-1890919858 for context. This latest release breaks tiledb (which doesn't have a strict pin on the azure-core-cpp version, just <2), and in that way also breaks eg libgdal.
In our CI where we noticed this, it's only on Linux that we see the crash, not on Windows or Mac. Therefore I only marked the linux packages as broken. We only test linux-64, but I marked aarch64 and pplc as well (assuming those would have the same issue?)
cc @conda-forge/azure-core-cpp 
* Packages with requirements/metadata …
=> Mark azure-core-cpp 1.11 broken on linux

.github/workflows/main.yml, conda_forge_admin_requests/mark_broken.py
=> Use PROD_BINSTAR_TOKEN to avoid clashes

conda_forge_admin_requests/token_reset.py, requests/reset-pytorch-cf.yml
=> reset tokens for pytorch-cpu and cf-autotick-bot-test-package

requests/broken.yml
The initial build of the tiledb-py 0.25.0 package linked to an older version of tiledb. Build 1 now contains the correct dependency. We had considered repodata patching, but due to formatting differences in tiledb 2.18 vs 2.19, we want to mark the previous binaries as broken. …
=> Remove tiledb-py 0.25.0 - Build 0

requests/kim-api-2.3.0-broken.yml
We have recently added the ability to build models to the kim-api conda-forge package. This is not a new functionality of the KIM API, it just was not present in the conda-forge package. This involved adding compilers (e.g. {{ compiler('c') }}, etc.) and build tools as run requirements, as well as a modification to the build script in order to set paths to compilers through CMake (so this is not just a metadata deficiency).
Because older builds of kim-api-2.3.0 don't have these dependencies, the solver will preferentially install them if any conflicting versions of the compilers are present in the environment. This is confusing to users, who expect the fixed model-building functionality to be present in their environment, but it is not because they accidentally obtained an older build …
=> mark older builds of kim-api-2.3.0 as broken

requests/archive-jupyter_sphinx.yml
I am a new maintainer of the jupyter-sphinx package and by setting up the badges in the readme file I realized there are 2 feedstocks wired to the same package..
we have:
https://github.com/conda-forge/jupyter_sphinx-feedstock
https://github.com/conda-forge/jupyter-sphinx-feedstock
I would like to only keep the "jupyter-sphinx" one to use the same naming convention as in the pypi package.
What we did is to refactor the "jupyter-sphinx" recipe to create 2 outputs and avoid breaking the existing environment relying on "jupyter_sphinx" (https://github.com/conda-forge/jupyter-sphinx-feedstock/pull/9) and then use "jupyter_sphinx" as an alias for jupyter-sphinx (https://github.com/conda-forge/feedstock-outputs/pull/56). 
Now it seems the last step is to archive the jupyter_sphinx repository …
=> request archive of jupyter_sphinx feedstock

requests/broken.yml
nbstripout version 0.7.0 is broken due to a major regression, truncating input files before they are read (see kynan/nbstripout#190). This regression makes this release practically unusable.
I'm the maintainer of both https://github.com/kynan/nbstripout and https://github.com/conda-forge/nbstripout-feedstock.
=> Mark nbstripout 0.7.0 broken

requests/arcticdb-broken.yml
I'm one of the maintainers for the ArcticDB project.
We want to mark the 4.3.0 release, which was made yesterday, as broken due to a fairly severe bug in the release, that means it should not be used.
the …
=> Mark ArcticDB 4.3.0 as broken

requests/intake-esm.yml
👋🏽 all,  i'm one of the maintainers for the  intake-esm
i would like to flag the 2024.2.6-pyhd8ed1ab_0 release as broken because it incorrectly includes support for Python 3.9. this particular version, 2024.02.6, of intake-esm [no longer supports Python 3.9](https://github.com/intake/intake-esm/pull/652), yet i erroneously retained compatibility with Python 3.9 in this build.
* Packages with missing metadata can be marked as broken on …
=> Mark intake-esm 2024.2.6-pyhd8ed1ab_0 as broken

update_repodata_patches.py
=> BUG reject new diff format

requests/loopy_token_reset.yml
Seeing issues uploading: https://github.com/conda-forge/loopy-feedstock/pull/6#issuecomment-1949935801
Also looks like the PR template no longer has a reset token option?
=> Reset Azure token for `loopy`

conda_forge_admin_requests/token_reset.py
Looks like all the `pkg` variables were renamed to `feedstock` in PR ( https://github.com/conda-forge/admin-requests/pull/921 ), but there was a stray one
This resulted in an issue resetting a token: https://github.com/conda-forge/admin-requests/pull/939#issuecomment-1949938245
=> Change one last `pkg` to `feedstock`

conda_forge_admin_requests/token_reset.py
Ran into a missing `import` here: https://github.com/conda-forge/admin-requests/pull/940#issuecomment-1949941110
This adds the `import`
=> Add missing `import copy` to token reset script

requests/r-parallelly-broken.yml
The last round of autoticked builds of `r-parallelly` didn't catch that upstream switched from `noarch` to compiled. The recipe [has been updated](https://github.com/conda-forge/r-parallelly-feedstock/pull/24). This marks the mislabelled `noarch` builds as broken (resolves https://github.com/conda-forge/r-parallelly-feedstock/issues/25).
ping @conda-forge/r-parallelly
=> Mark broken compiled "noarch" builds of `r-parallelly`

requests/tensorflow.yaml
Tensorflow has long been stuck in CFEP-03 land, let's try to get it out of there. ;-)
CC @jaimergp @isuruf @hmaarrfk @xhochy
=> enable tensorflow to use cirun

requests/mongodb.yaml
Current mongodb v7 manages to compile about half the objects before running into the 6h timecap ([example](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=882735&view=results); around `[2385+2/4544]` on linux-64, `[2398+2/4489]` on win-64, etc.) - completely hopeless to get it over the line.
CC @jaimergp
=> enable mongodb to use cirun

requests/pytest-8.1.0.yml
`pytest 8.1.0` has been yanked from PyPI: https://github.com/pytest-dev/pytest/pull/12075 …
=> Mark pytest-8.1.0 as broken

requests/glib.yml
These builds contain a proxy implementation of `libintl` (which is actually part of `gettext`) and thus break all packages that were previously build against `libglib`. See also https://github.com/conda-forge/glib-feedstock/issues/162 We cannot repodata patch as the respective library should never be installed.
cc @conda-forge/glib 
but should be patched in …
=> Mark glib build with proxy-libintl as broken

requests/add_travis_libnvfatbin.yml
Adding Travis CI to `libnvfatbin` for native `linux_aarch64` and `linux_ppc64le` builds.
<hr>
* We (`conda-forge/core`) try to make …
=> Add `libnvfatbin` to Travis CI

requests/rdma-core.yml
Some `rdma-core` packages were corrupted by `conda-build`. Mark these broken so feedstock builds or users don't pick them up accidentally.
xref: https://github.com/conda-forge/openmpi-feedstock/pull/142#issuecomment-1936503202
xref: https://github.com/conda-forge/rdma-core-feedstock/pull/17
xref: https://github.com/conda/conda-build/issues/5179
<hr>
but …
=> Mark corrupted `rdma-core` packages broken

requests/gcc_gxx_all.yml
They don't have a run_exports, cc @isuruf @h-vetinari
=> Mark non-cross gcc/gxx*_2 as broken

archive/boost-cpp.txt, requests/boost-archive.yml
After https://github.com/conda-forge/boost-feedstock/pull/164, the [boost-cpp](https://github.com/conda-forge/boost-cpp-feedstock/) feedstock is now obsolete. I've closed issues and PRs as appropriate, and moved unresolved issues to the unified feedstock.
I guess the only point would be to keep the possibility to rebuild boost-cpp 1.78 if necessary (though that should hopefully soon be obsolete too by migrating to 1.82), otherwise I think we're good to go with archiving that feedstock
=> archive boost-cpp feedstock

requests/pydtmc-broken.yml
Hi @conda-forge/pydtmc
please move the specified packages from main to broken on the conda-forge channel. The reason is that I recently checked all the past releases and I found out that those packages are unusable because of a bad setup, which I cannot recover.
=> PyDTMC Broken Packages

requests/graphite2-broken.yml
`conda create -n ffmpeg ffmpeg` On Windows currently results in a broken package, and similarly `import cv2` crashes, as harfbuzz can't find `graphite2.dll`. The package contain a file called `libgraphite2.dll` instead, as I guess it was compiled with mingw. See https://github.com/conda-forge/graphite2-feedstock/issues/14 for more details, however I think it is a good idea to just mark it as broken to fix all the library that depends on harfbuzz.
cc @conda-forge/ffmpeg @conda-forge/opencv @conda-forge/harfbuzz @conda-forge/graphite2 
* Packages with requirements/metadata …
=> Mark graphite2-1.3.13-*_1002 Windows package as broken

requests/snappy-broken.yml
See https://github.com/conda-forge/snappy-feedstock/issues/35 for context. Snappy 1.2.0, although providing the same .so version as 1.1.10, changed some APIs leading to broken imports in packages built against snappy (eg pyarrow)
* In some cases where the number of users of a package is …
=> Mark snappy 1.2.0 as broken

requests/jaraco.context-broken.yml
=> Mark jaraco.context 5.3.0 build 0 as broken

requests/proj-broken.yml
Tests were skipped in 
https://github.com/conda-forge/proj.4-feedstock/pull/141
but then caused downstream problems, e.g.
https://github.com/conda-forge/pyproj-feedstock/pull/148
The expertise is not there to figure out the problem, see
https://github.com/conda-forge/proj.4-feedstock/pull/142 
and we don't want to hold up migration on other platforms.
We are skipping ppc64le for now:
https://github.com/conda-forge/proj.4-feedstock/pull/143
ping @conda-forge/proj-4 
not technically broken and …
=> Mark proj 9.4.0 for ppc64le as broken

.github/dependabot.yml, .github/workflows/create_feedstocks.yml, .github/workflows/main.yml, .github/workflows/pr.yml, .github/workflows/repodata_patching.yml
=> pin github actions; add dependabot

requests/example-broken.yml
We renamed it upstream and we don't want folks installing this one by mistake.
=> mark ioos_metrics as broken

examples/pytorch-gpu.yml
This expands on #881 because we run out of memory on the cirun server. Based on [observed](https://github.com/conda-forge/pytorch-cpu-feedstock/pull/237#issuecomment-2113388516) memory usage from building locally, it has been suggested to try the 4xl runner; I'm also enabling the intermediate ones in case those en up as sufficient.
Needed for https://github.com/conda-forge/pytorch-cpu-feedstock/pull/238
=> enable larger GPU runners on pytorch feedstock

requests/libdwarf-broken.yaml
The shared objects are missing from these packages, rendering them non-functional.
https://github.com/conda-forge/libdwarf-feedstock/issues/17
ping @conda-forge/libdwarf
=> Mark libdwarf 0.9.2 broken

requests/namaster_broken.yml
The latest namaster [build](https://github.com/conda-forge/namaster-feedstock/pull/42) updated it to numpy v2. This is not yet a stable numpy release, and some of the changes are actually not compatible with namaster and some of its current dependencies.
ping @conda-forge/namaster
=> Declare latest namaster build as broken

requests/openmpi-external-broken.yml
=> ENH mark older external builds of openmpi 5.X broken

requests/qt6_main_6.7.1_broken.yml
As part of a refactor of the recipe we were planning on removing qtmultimedia from the recipe in 6.7.2 but accidentally did so in 6.7.1 build 1
https://github.com/conda-forge/qt-main-feedstock/pull/256
xref: https://github.com/conda-forge/qt-main-feedstock/issues/265
This is causing issues for downstream recipes such as pyside6 https://github.com/conda-forge/pyside2-feedstock/pull/228
And thus likely causing issues for a subset of users
The recipe is being fixed at the moment and a test has been added to ensure an other library isn't missed in the process https://github.com/conda-forge/qt-main-feedstock/pull/264
instead of marking packages as broken. This alternative …
=> Mark qt6 6.7.1 build 1 as broken on windows

requests/broken.yml
The windows build of minizip 4.0.7 changed a .dll file name conda-forge/minizip-feedstock#17 and is causing downstream build grief on conda-forge.  @ocefpaf asked that I mark it as broken for now
=> mark minzip 4.0.7 on windows as broken

requests/xformers.yml
xformers compiles a lot of symbols per architecture, and times out with our default set of architectures, which _should_ look like this:
```bash
if [[ ${cuda_compiler_version} == 11.8 ]]; then
export TORCH_CUDA_ARCH_LIST="3.5;5.0;6.0;6.1;7.0;7.5;8.0;8.6;8.9+PTX"
elif [[ ${cuda_compiler_version} == 12.0 ]]; then
export TORCH_CUDA_ARCH_LIST="5.0;6.0;6.1;7.0;7.5;8.0;8.6;8.9;9.0+PTX"
```
To avoid timing out with the 6h limit on azure, we're currently just able to build
```bash
if [[ ${cuda_compiler_version} == 11.8 ]]; then
export TORCH_CUDA_ARCH_LIST="5.0;8.9+PTX"
elif [[ ${cuda_compiler_version} == 12.0 ]]; then
export TORCH_CUDA_ARCH_LIST="5.0;7.0;8.0;9.0+PTX"
```
i.e. 2-4 instead of 9 GPU architectures. I think it would be good to build the full set of architectures on the cirun server. …
=> add xformers to cirun

requests/domb-napari.yml
=> Mark domb-napari 2023.* broken

requests/riskfolio-lib-broken.yml
riskfolio-lib 4.1.0 is compiled but erroneously marked as noarch https://anaconda.org/conda-forge/riskfolio-lib/files
=> mark riskfolio-lib “noarch” packages as broken

.github/workflows/create_feedstocks.yml
This PR add support to run the feedstock generation when a rattler-build `recipe.yaml` file is found. I've just expanded the `if` clause to these cases.
I think this PR should be merged **after**: https://github.com/conda-forge/staged-recipes/pull/26981
So I'll make a draft of it till that one is merged.
Let me know if I'm missing something, happy to make any changes.
=> feat: runs feedstock generation when `recipe.yaml` exists

requests/rattler-build-compat-broken.yml
See https://github.com/conda-forge/rattler-build-conda-compat-feedstock/issues/11
We can't patch repodata since building that requires building a feedstock and all feedstocks are broken right now.
cc @conda-forge/rattler-build-conda-compat
=> Mark rattler-build-compat-broken as broken

requests/rdkit-broken.yml
An update to the conda-forge version of `libcxx` triggered a bug in some very basic functionality within the rdkit packages on MacOS (intel and arm64), rendering those packages unuseable for many people.
This PR will remove build 1 of these MacOS packages, leaving build 0, which used the older version of `libcxx` and so doesn't trigger the bug.
More context and a link to the upstream fixes here:
https://github.com/conda-forge/rdkit-feedstock/issues/162
This will, unfortunately, remove the numpy 2.0 compatible RDKit builds for MacOS.
We're also doing an upstream release today so that we can get an up-to-date RDKit version (with numpy 2.0 support) out there for all systems.
=> mark the RDKit MacOS 2024.3.4 build 1 packages as broken

requests/mpich.yml
=> fix: add back mpich external package with new deps

.github/workflows/main.yml, .github/workflows/pr.yml, .github/workflows/repodata_patching.yml
Comes from https://github.com/conda-forge/miniforge/issues/602#issuecomment-2248188930
We were using Mambaforge and not Miniforge, but they should be equivalent.
Also fixed the version comments of some GHA hash pins.
=> Use Miniforge, not Mambaforge

requests/mongodb.yaml
Follow-up to #949.
Despite reduced parallelism, https://github.com/conda-forge/mongodb-feedstock/pull/80 keeps dying from running into what appears to be an OOM issue (c.f. https://github.com/Quansight/open-gpu-server/issues/28).
Try with the next-larger runner (not sure why this isn't listed in the [.cirun](https://github.com/conda-forge/.cirun) readme, https://github.com/conda-forge/.cirun/issues/19).
CC @jaimergp @isuruf
=> add next-larger runner for mongodb

requests/flash-attn-open-gpu-server.yml
Applying for `cirun-openstack-gpu-large` and `cirun-openstack-cpu-large` for building flash-attn. Builds were originally using `TORCH_CUDA_ARCH_LIST=8.0+PTX` only to try to keep under 6 hour limit at https://github.com/conda-forge/staged-recipes/pull/26239, but they recently started to timeout at https://github.com/conda-forge/flash-attn-feedstock/pull/10.
Using a bigger instance will also allow us to build for `TORCH_CUDA_ARCH_LIST=8.0;8.6;8.9;9.0+PTX`, xref https://github.com/conda-forge/flash-attn-feedstock/issues/4
=> Request large CPU/GPU runners for flash-attn

requests/pip-broken.yml
=> Request to mark pip 24.1.2 as broken.

requests/pip.yml
=> fix: add pip 24.1.2  back to the index

requests/fastcan_broken.yml
=> mark fastcan noarch 0.2.0 build 0 as broken

requests/build.yml
=> feat: mark build as broken

broken/jaxlib.txt
`jax==0.4.31` has a check at runtime (that is not reflected on cuda metadata) on cudnn>=9, and so trying to use `cuda` on `jax==0.4.31` result in an error like:
~~~
CUDA backend failed to initialize: Unable to use CUDA because of the following issues with CUDA components:
Outdated cuDNN installation found.
Version JAX was built against: 8907
Minimum supported: 9100
Installed version: 8907
~~~
See https://github.com/conda-forge/jaxlib-feedstock/issues/277 and https://github.com/conda-forge/jax-feedstock/issues/149 .
As the only possible combinations of `jaxlib` and `jax` that can be installed together (given their mutual constrained dependencies) is:
* jax==0.4.31 + jaxlib==0.4.31
* jax==0.4.31 + jaxlib==0.4.30
I think it make sense to mark as broken the cuda builds of `jaxlib==0.4.31` and …
=> Mark cuda builds of jaxlib 0.4.30 and 0.4.31 as broken due to jax runtime check on cudnn version

requests/pytorch_osx_mkl_240-broken.yml
xref: https://github.com/conda-forge/numpy-feedstock/issues/327
xref: https://github.com/conda-forge/pytorch-cpu-feedstock/pull/252 …
=> Mark pytorch 2.4.0 osx + mkl build 0 as broken

requests/libcxx.yml
The work from https://github.com/conda-forge/libcxx-feedstock/pull/183 needs tighter synchronization with the compiler stack than I realized at first. Mark as broken for now, and re-enable later.
=> mark libcxx 18.1.8 _5 broken for now

requests/vs.yml
---
cc: @isuruf, @h-vetinari, @conda-forge/vc 
Undoes #1056 
The Azure Windows Server 2022 image has been switching back and forth between Visual Studio 17.10 (19.40) and 17.11 (19.41). Currently it is back to image version 20240825.1.0, which requires vs2022_win-64 19.41. Hopefully Azure keeps the image version stable going forward
xref: https://github.com/actions/runner-images/pull/10490, https://github.com/conda-forge/vc-feedstock/pull/82#issuecomment-2313344988, https://github.com/TileDB-Inc/conda-forge-nightly-controller/issues/133#issuecomment-2313329076
=> Mark vs 19.41 as not broken

broken/jaxlib.txt, broken/py-build-cmake.txt, requests/jaxlib_broken.yml, requests/py-build-cmake_broken.yml
=> fix jaxlib py-build-cmake broken labels

requests/rubin-scheduler.yml
I would like to mark version 1.2.2 of rubin-scheduler as broken. 
There was a backwards-incompatible change introduced at this tag, which I didn't notice, and thus the semver version number is inaccurate and misleading. 
* In some cases where the number of users of a package is small or it …
=> Mark rubin-scheduler 1.2.2 broken

.feedstock_outputs_autoreg_allowlist.yml
This PR adds an allow list for automatically registering new feedstock outputs. I have not added an admin request job because this should be rare.
=> feat: add allow list for feedstock autoreg

.feedstock_outputs_autoreg_allowlist.yml
Follow-up from #1074 
> @beckermr: I added a few items to start. We can add more over time as we hit things. They are hard to track down a priori.
There's a bunch more using [this search](https://github.com/search?q=org%3Aconda-forge+%2F-+name%3A%5Cs%5Cw%2B%5C%7B%5C%7B%2F+path%3Arecipe%2Fmeta.yaml&type=code&p=1), but for now I'm not adding all these (for `vc14_runtime`, `vs2022_win-64`, etc. I didn't add it because it should be extremely rare to touch this)
=> Expand globs for known versioned ouputs

requests/flox.yml
=> Mark flox wrong version as broken

requests/r-betareg-broken.yml
The `r-betareg` package [added some compiled components from v3.1-4 to v3.2-0](https://github.com/cran/betareg/compare/3.1-4...3.2-0), but this was not caught until https://github.com/conda-forge/r-betareg-feedstock/pull/18. Hence, there are some uploaded artifacts that are labeled as **noarch**, but are in fact **linux-64**. This PR marks them as broken.
ping @conda-forge/r-betareg
=> label as broken non-noarch `r-betareg` artifacts

requests/pysimplegui.yml
cc @conda-forge/pysimplegui 
See the reasoning here: https://github.com/conda-forge/pysimplegui-feedstock/issues/83
Keeping this simply as broken could bring us into legal trouble. If this PR is merged, I would manually delete the package as we don't have automation for it.
@conda-forge/core Deleting a package is drastic but required from my PoV. Let's get more than one approval here given its drastic nature (and to keep a positive mood in core).
=> Delete pysimplegui 5

requests/mpi-broken.yml
these cause problems in conda due to a bug in conda not handling x.y versions in noarch packages
https://github.com/conda-forge/mpi-feedstock/issues/17
The `1.0.1` builds don't appear to have this problem
cc @leofang
=> mark noarch mpi metapackages broken

requests/python.yml
@conda-forge/core @conda-forge/python these didn't have some files and for some reason, these builds gets picked up.
=> Mark some older python windows freethreading builds as broken

requests/archive-pyqmix.yml
Following a suggestion by @beckermr, I'd like to request the archiving of the pyqmix feedstock, as the upstream project has been archived as well and doesn't receive updates any longer.
=> Archive pyqmix

requests/openexr-broken.yml
conflict due to bundling libdeflate dependency: https://github.com/conda-forge/openexr-feedstock/issues/49
=> mark openexr 3.3.1_0 builds broken

requests/gym.yml
For reasoning see https://github.com/conda-forge/gym-feedstock/issues/39. The package got renamed and moved to https://github.com/conda-forge/gymnasium-feedstock, but more importantly, it also messes up the dependency graph. In sum, let's archive it.
=> archive gym feedstock

requests/broken_python_multipart_0.0.13.yml
[python_multipart](https://github.com/conda-forge/python-multipart-feedstock) 0.0.13 was yanked from pypi, see https://github.com/conda-forge/python-multipart-feedstock/issues/11
=> Mark python_multipart 0.0.13 as broken

requests/twine.yml
=> mark twine 5.1.0 broken

requests/archive_feedstocks.yml
These feedstocks have all been removed from CRAN and should be archived:
- https://github.com/conda-forge/r-best-feedstock/issues/3
- https://github.com/conda-forge/r-cairodevice-feedstock/issues/17
- https://github.com/conda-forge/r-freetypeharfbuzz-feedstock/issues/8
- https://github.com/conda-forge/r-gwidgetsrgtk2-feedstock/issues/9
- https://github.com/conda-forge/r-rgtk2-feedstock/issues/12
- https://github.com/conda-forge/r-sen2r-feedstock/issues/8
Note that while `r-gwidgetsrgtk2` depends on `r-rgtk2`, none of these package have any dependents outside of this list.
instead of marking packages as broken. This alternative workflow makes environments more …
=> archive R feedstocks removed from CRAN

requests/scip-920-rc.yml
I did a mistake in https://github.com/conda-forge/scipoptsuite-feedstock/pull/76, which uploaded a Linux build for a release candidate of packages for SCIP Optimization Suite 9.2.0 (scip 9.2.0, soplex 7.1.2, papilo 2.4.0, gcg 3.7.0) to conda-forge.
Closes conda-forge/scipoptsuite-feedstock#80.
but should be patched in the repo data and be marked unbroken …
=> request to mark packages with release candidate (linux/x86_64) as broken.

requests/openff-units-broken.yml
This release introduced an [esoteric bug](https://github.com/openforcefield/openff-toolkit/issues/1960) that was difficult to detect in our testing environments but shows up immediately in production. The problem is simply in the source code, making it a bad release, not in the dependencies/metadata which could be fixed by patching repodata. In no case do we want our users to install this particular version of this package. (The only ways I could think of working around this via patching repodata seemed a little obtuse, i.e. patching our other main package to never install this version of this package.)
instead of marking packages as broken. This alternative workflow …
=> Mark broken `openff-units` 0.2.3

requests/sherpa-broken.yml
Resolves https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/issues/899
* The version number was mistakenly set to `v2.2.16` and not `2.2.16`. Dependency solvers are not resolving the 'v' part correctly resulting in broken environment solves. Despite fixing and rebuilding (https://github.com/conda-forge/sherpa-feedstock/pull/5), the download number on the package continues to increase, and so to stop it from being downloaded it should be marked as broken.
- c.f. https://anaconda.org/conda-forge/sherpa/files?version=v2.2.16 …
=> Mark sherpa v2.2.16 as broken

requests/ittapi-add-feedstock-output.yml
ping @conda-forge/ittapi
I want to add `ittapi-static` package in addition to `ittapi`. It seems like `ittapi` was created as python package, but there is an option to have a static library that can be used by other projects. For example, I intent to use it intel-pti, but I've seen similar requests from folks.
Changes introduced in the PR: https://github.com/conda-forge/ittapi-feedstock/pull/34
It also looks like the feedstock does not have active maintainers, so I'm requesting to add myself there: https://github.com/conda-forge/ittapi-feedstock/pull/33
=> Add ittapi-static package

requests/pti-gpu-unitrace-add-feedstock-output.yml
ping @conda-forge/pti-gpu-unitrace 
Intel recently release `intel-pti` package in https://software.repos.intel.com/python/conda channel. This package is important cause it is required dependency for the intel's gpu (aka xpu) backend for pytorch. Instead of adding it as a repack at https://github.com/conda-forge/intel_repack-feedstock it is possible to build it from source here:
https://github.com/conda-forge/pti-gpu-unitrace-feedstock/pull/1
`pti-gpu-unitrace` does not have independent release cycle, so we will get regular updates on this as well.
=> Add intel-pti package

requests/dparse.yml
=> add dparse-with-* outputs to dparse

requests/add-pyright-node.yaml
ping @conda-forge/pyright 
The `pyright` feedstock currently packages a small Python wrapper around the `pyright` language server (written in TypeScript) that provides a CLI and LSP interface to the TypeScript package. However, the TypeScript code itself is not packaged in the feedstock. This causes the package to run an npm install in the background on its first invocation, requiring internet access.
In https://github.com/conda-forge/pyright-feedstock/pull/184, I've added pyright-node as a feedstock output. This packages the JavaScript code, making the `pyright` package self-contained and removing the need for the npm install at runtime.
=> add `pyright-node` output to `pyright`

requests/openmpi-cuda.yml
latest build got an improper link of cuda not loaded as-needed with dlopen
https://github.com/conda-forge/openmpi-feedstock/issues/185
=> mark latest openmpi linux builds as broken

requests/rattler-build-windows.yml
Unfortunately the latest rattler-build build is empty on Windows. Will debug now.
=> mark latest rattler-build build on win as broken

requests/ctng.yml
Now that we have CFEP-24, the new `clang{,xx}_impl` outputs from https://github.com/conda-forge/ctng-compiler-activation-feedstock/pull/131 are failing validation. Add them.
=> enable clang_impl outputs on ctng-compiler-activation

requests/flask-security.yml
Ref: https://github.com/conda-forge/flask-security-feedstock/pull/7
Failing with:
```
+ validate_recipe_outputs flask-security-feedstock
WARNING: No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.26
Adding in variants from internal_defaults
Adding in variants from /home/conda/feedstock_root/.ci_support/linux_64_.yaml
validation results:
{
"noarch/flask-security-5.5.2-pyhff2d567_0.conda": false
}
```
Did the previous checks, but seems the feedstock has been inactive for a number of years and just recently got a new version, which might explain why the token reset might be needed.
=> Request token reset for `flask-security`

requests/name_change_eth-account
Upstream renamed the package from using dash to underscore. Thus I added a new output, which needs permission to be uploaded.
@conda-forge/eth-account
=> Allow secondary output due to upstream name change

requests/adam-robotics.yml
This PR will enable support for multiple outputs in the `adam-robotics` package. By modularizing the package depending on the backend, we can streamline the dependency list and reduce its overall size, making it more lightweight
FYI @conda-forge/adam-robotics @traversaro @giulero @xela-95
* [`requests/adam-robotics.yml`](diffhunk://#diff-53bf2f3eaaa4ae30055a42e2f1f173192a8f4450ad8c7b8034c74a185fa38101R1-R3): Added a new action `add_feedstock_output` with a mapping for `adam-robotics` to `adam-robotics-*`.
* Packages with requirements/metadata that are too strict but …
=> Add allowed glob pattern to `adam-robotics` outputs

requests/rust-std-aarch64-pc-windows-msvc.yml
=> allow rust-feedstock to output rust-std-aarch64-pc-windows-msvc

requests/pyarrow.yml
Due to https://github.com/conda-forge/pyarrow-feedstock/issues/115; a retrigger of the webservice by Matt didn't help, so let's rotate the tokens.
=> request token reset for pyarrow

requests/spacy-models.yml
Spacy models has an elaborate setup where new languages (resulting in new `spacy-models-*` packages) get [added](https://github.com/conda-forge/spacy-models-feedstock/blob/main/recipe/conda_build_config.yaml.j2) based on upstream configuration.
Reflect this in the allowed-package outputs.
=> add glob for spacy-models

requests/astropy-base.yml
@conda-forge/astropy Would like to split the astropy feedstock into an astropy package with many deps and an astropy-base package with minimal deps.
https://github.com/conda-forge/astropy-feedstock/pull/137
=> Add astropy-base output to astropy-feedstock

requests/split-suitesparse.yml
each library will get its own output, including the addition of suitesparse-mongoose not previously included:
https://github.com/conda-forge/suitesparse-feedstock/pull/98
package names match those in ubuntu (not including the ABI suffix, so libamd, not libamd3)
=> prepare to split suitesparse outputs

requests/gz-physics-token-reset.yml
The token seems to have expired: https://github.com/conda-forge/gz-physics-feedstock/issues/55
=> Reset token for gz-physics

requests/broken.yml
What is old is new again, same as #1019, the updated minizip build for windows is broken as it has a different name for the dll, which breaks things left and right :(
cc: @rouault
ping @conda-forge/minizip
=> mark minizip windows 4.0.7-h9fa1bad_1 as broken

requests/broken.yml
This package can't be built against as my file renaming hack on windows was insufficient. conda-forge/freexl-feedstock#32
ping @conda-forge/minizip 
Hopefully the last minizip build on windows that needs to be marked as broken.  build 3 hopefully fixes all the boats.
=> mark minizip-4.0.7-h9fa1bad_2[win] as broken

requests/zellij-broken.yml
=> mark zellij packages as broken

requests/codspeed-broken.yml
=> pytest-codspeed-3.1.0 is broken

requests/add-osmnx-base.yml
=> Add `osmnx-base`

requests/cuquantum-python.yml
As discussed here: https://github.com/conda-forge/cuquantum-feedstock/pull/68#discussion_r1887672838
Requesting to unarchive the cuquantum-python feedstock and build the cuquantum-python package separately again.
The original feedstocks were combined because CDN population time between C-API package and Python-API package was inconvenient. However, now the C-API package has more build variants and the build matrix would be very large. Having separate feedstocks seems better than applying complicated skip logic to prune extra builds.
cc: @conda-forge/cuquantum @conda-forge/cuquantum-python @jakirkham 
instead of marking packages as broken. This alternative workflow makes …
=> Unarchive cuquantum-python feedstock

requests/archive-napoleon.yml
per @ocefpaf's request in https://github.com/conda-forge/sphinxcontrib-napoleon-feedstock/pull/6#issuecomment-2559607728. The upstream package has been defunct for a decade, as it was merged to the core of Sphinx 1.3 in 2014.
Best wishes,
Adam
=> Archive sphinxcontrib-napoleon

requests/torchvision-add-tests-output.yml
-----
As discussed in https://github.com/conda-forge/torchvision-feedstock/pull/107.
=> torchvision: Allow torchvision-tests output

requests/archive-r-gdalutils.yml
The upstream of `r-gdalutils` is unmaintained and has been removed from CRAN. Requesting to archive.
See https://github.com/conda-forge/r-gdalutils-feedstock/issues/12
ping @conda-forge/r
=> Archive `r-gdalutils`

requests/add-ff-feedstock-output.yml
=> Add ff-feedstock mapping to ff-static

requests/sirius-ms-6.0.7-broken.yml
During the Arch Migrator process, new `linux-aarch64` and `linux-ppc64le` packages were created for SIRIUS 6.0.7 (`sirius-ms v6.0.7`). Unfortunately, some platform-dependent Java libraries in SIRIUS 6.0.7 do not support these architectures. Because our tests did not catch this issue, those packages were published but cannot produce usable results. We would therefore like to mark them as broken.
We are now releasing SIRIUS 6.1.0 with improved tests and proper `linux-aarch64` support. However, `linux-ppc64le` remains unsupported and will be disabled in future builds.
For more details, please see:  
[https://github.com/conda-forge/sirius-ms-feedstock/pull/30](https://github.com/conda-forge/sirius-ms-feedstock/pull/30)
* We prefer to patch the repo data (see …
=> linux-aarch64 and linux-ppc64le builds of sirius-ms v6.0.7 are broken.

requests/bleach-with-css-broken.yml
=> mark bleach-with-css-6.2.0-hd8ed1ab_2 broken

requests/add-serpy-output.yml
Having issues in https://github.com/conda-forge/serpy-feedstock/pull/2. This is an old package with no new builds in the past 7 years. I already tried a token reset in #1267. Error message on the PR is:
```
validation results:
{
"noarch/serpy-0.3.1-pyhd8ed1ab_1.conda": false
}
```
=> Add serpy output

requests/add-tracy-profiler-output.yml
=> Add tracy-profiler

requests/activemq-cpp.yml
cc @conda-forge/activemq-cpp 
Headers were in the wrong place.
=> Mark old activemq-cpp builds broken

conda_forge_admin_requests/access_control.py
Fixes https://github.com/conda-forge/admin-requests/actions/runs/12689155477/job/35367226282
=> MNT: Fix `.startswith()` typo

requests/doppel-cli-archive.yml
Requesting that the `doppel-cli` feedstock be archived.
Following the process at https://conda-forge.org/docs/maintainer/updating_pkgs/#archiving-feedstocks, I've opened an issue (https://github.com/conda-forge/doppel-cli-feedstock/issues/2) and pinged `@conda-forge/core`.
Thank you for your time.
=> archive doppel-cli

requests/example-token-reset.yml
These feedstock PRs are failing to valid their artifacts and a likely suspect is an expired token:
- https://github.com/conda-forge/dmd-feedstock/pull/7
- https://github.com/conda-forge/r-volumodel-feedstock/pull/2
=> reset feedstock tokens

requests/rubin-scheduler.yml
The Rubin Summit team indicated that this release is not compatible with their use at this time, and that maintaining two branches and two series of tags would be likely to take many months to reconcile, thus we should instead mark this version as broken and replan the release schedule. 
In short - release is broken at the source code for primary consumer usage and removing this release is the best way forward.
* Packages with missing …
=> Mark rubin_scheduler 4.0.0 broken

requests/add-parsl-output.yml
We have `parsl-with-*` packages for many `parsl` extras already.  A new one was added in a recent update, `parsl-with-globus_compute`:
https://github.com/conda-forge/parsl-feedstock/pull/115
In general, we want to keep up with new extras as they are added to parsl. …
=> Add `parsl-with-*` extras

requests/spyder-memory-profiler-archive.yml
I was the maintainer of the upstream project [spyder-ide/spyder-memory-profiler](https://github.com/spyder-ide/spyder-memory-profiler) until about two years ago, when I decided to archive the project because its main dependency is no longer maintained.
I just realized that the feedstock is still active, so I want to archive the feedstock.
Link to issue on feedstock: conda-forge/spyder-memory-profiler-feedstock#15
Pinging other feedstock maintainers: @conda-forge/spyder-memory-profiler
=> Archive spyder-memory-profiler feedstock

requests/add-ray-cgraph.yml
@ping @conda-forge/ray-packages 
There is a new feedstock output ray-cgraph for v2.41.0, see https://github.com/conda-forge/ray-packages-feedstock/pull/193
=> add mapping for ray-cgraph

requests/oliver-archive.yml
We've stopped maintaining `oliver` in favor of our own execution engine, [`sprocket`](https://github.com/stjude-rust-labs/sprocket). At this point, we're not going to release any more updates, so it makes sense to archive the feedstock. Here is a link to the [Github Issue](https://github.com/conda-forge/oliver-feedstock/issues/22) on the feedstock repository.
=> revise: archive `oliver-feedstock`

requests/pipefunc.yml
In https://github.com/conda-forge/pipefunc-feedstock/pull/80 I accidentally set `noarch: generic`. Fixed this in https://github.com/conda-forge/pipefunc-feedstock/pull/83 …
=> Mark incorrect `noarch` builds for pipefunc as broken

requests/add_ncrystal_outputs.yml
In order to split the C++/library parts of NCrystal from the Python layer, the ncrystal-feedstock needs to be modified to use multiple outputs. So before there was just an "ncrystal" package, but in the future there will be at least "ncrystal-core", "ncrystal-python",  and "ncrystal" packages, where the last will be a metapackage depending on the rest and ensuring synchronisation of versions. In the future the ncrystal-core itself might be split further (into libs, headers, data files), but that is not going to happen in the short term.
I am the maintainer of the ncrystal-feedstock, so I count myself as having been pinged :-)
=> allow multiple outputs in ncrystal-feedstock

conda_forge_admin_requests/feedstock_outputs.py
xref: https://github.com/conda-forge/admin-requests/pull/1347
=> fix: correct exception handling

requests/feedstocks-archive.yml
=> Archive some stale feedstocks

requests/vtki.yml
cc @conda-forge/vtki archiving [vtki feedstock](https://github.com/conda-forge/vtki-feedstock) per https://github.com/conda-forge/vtki-feedstock/issues/17
vtki was renamed to PyVista nearly 6 years ago and vtki was only supported up to Python 3.7 which is well beyond End of Life
See https://github.com/conda-forge/pyvista-feedstock instead
=> Archive vtki

requests/petsc-broken.yml
I want to mark a package as broken:
This package broke the conda-forge repodata.json for linux-64 as describe in:
https://github.com/conda/conda-build/issues/5608
@conda-forge/petsc
=> Mark petsc as broken packages

requests/petsc-broken-more-platforms.yml
I want to mark a package as broken:
This package broke the conda-forge repodata.json for linux-ppc64le and linux-aarch64 as described in:
https://github.com/conda/conda-build/issues/5608
@conda-forge/petsc
=> Mark petsc as broken packages for linux-ppc64le and linux-aarch64

requests/petsc-broken.yml
same as #1363
merged prematurely before the rattler-build fix has been deployed (waiting for rattler-build 0.35.10, I believe)
=> mark more petsc cuda complex builds broken

requests/broken-files.yml
A version of the diffpy.pdffit2 package was accidentally uploaded to the no-arch channel two years ago.  Since we don't have a Mac OS arm64 build for the current version of diffpy.pdffit2, when Mac users conda-install this package, they, by default, get this broken package installed with no error message. 
ping @conda-forge/diffpy.pdffit2
=> request to remove broken package files from diffpy.pdffit2 in conda-forge

conda_forge_admin_requests/feedstock_outputs.py
Prevent misformatted requests like the ones observed in https://github.com/conda-forge/admin-requests/pull/1374
=> Check type of output names in 'add_feedstock_output' requests

examples/example-add-feedstock-output.yml
This PR adds another example line in the file for adding feedstock outputs to make it clear how to list more than one output for a feedstock in a given job.
=> doc: update example for outputs

.github/workflows/create_feedstocks.yml, .github/workflows/main.yml
This is supposed to address the issues observed in https://github.com/conda-forge/admin-requests/pull/1374. We had this line in other workflows, so let's add it everywhere for consistency.
=> Set pull.rebase = false for global git configs

requests/add-oneloop-static-output.yaml
* To work properly as dependencies of mg5amcnlo (https://github.com/conda-forge/mg5amcnlo-feedstock) add static library output to the oneloop (https://github.com/conda-forge/oneloop-feedstock) feedstock.
- Required for: https://github.com/conda-forge/oneloop-feedstock/pull/3
-  PR follows [CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md)
but …
=> Add static output to oneloop

requests/sdl.yml
This PR adds the `sdl2` and `sdl3`output to the [sdl-feedstock](https://github.com/conda-forge/sdl-feedstock).
To follow package manager habits, SDL major version are released with different package name, but following discussion in https://github.com/conda-forge/staged-recipes/pull/29061#issuecomment-2658421352 we manage to reunite all the major version in one feedstock.
=> Add sdl2 and sdl3 outputs in sdl feedstock

requests/archive_sdl2_feedstock.yml
Following the discussion here: https://github.com/conda-forge/staged-recipes/pull/29061, the recipes for packages `sdl`, `sdl2`, `sdl3` are now all released through the feedstock: https://github.com/conda-forge/sdl-feedstock.
Thus, the feedstock: https://github.com/conda-forge/sdl2-feedstock can be archived as mentioned in the issue: https://github.com/conda-forge/sdl2-feedstock/issues/61.
@dschreij, @matham, @traversaro do you validate the approach ?
=> Archive sdl2-feedstock

requests/libiconv-broken.yml
The `libiconv` 1.18=*_0 build on Windows contains an ABI break that creates a problem in pkg-config and due to the use of pkg-config in a activation script, also in the installation of any package that depends (even transitively) on `gdk-pixbuf` . While we look into a fix, the best option is to mark the problematic package as broken. 
Related issues:
* https://github.com/conda-forge/ffmpeg-feedstock/issues/312
* https://github.com/conda-forge/gdk-pixbuf-feedstock/issues/48
* https://github.com/conda-forge/libiconv-feedstock/issues/48
* https://github.com/conda-forge/vtk-feedstock/pull/368
@conda-forge/core @conda-forge/libiconv  @conda-forge/pkg-config @conda-forge/gdk-pixbuf @conda-forge/vtk @conda-forge/ffmpeg
=> Mark libiconv 1.18=*_0 on Windows as broken due to a ABI break

requests/broken-oneloop-and-oneloop-static.yml
* https://github.com/conda-forge/oneloop-feedstock was accidentally building with quad precision enabled for all platforms, even those that didn't support it. So linux-aarch64 and osx builds have incorrectly built binaries.
* Fixed in https://github.com/conda-forge/oneloop-feedstock/pull/6 for build 3.
> [!NOTE]
> Note to future self: The full names of the packages were retrieved programatically with
> 
> ```
> $ curl -s https://api.anaconda.org/package/conda-forge/oneloop | grep basename | grep 3.7.2 | grep 'aarch64\|osx' | awk '{print $NF}' | sed 's/"//g' | sed 's/,//g'
> ```
> There is obviously a cleaner way to do that, but the above works.
> 
> c.f. [conda-forge Zulip conversation](https://conda-forge.zulipchat.com/#narrow/channel/457337-general/topic/Programatically.20get.20full.20na …
=> Mark oneloop v2.2.16 v3.7.1,v3.7.2 and oneloop-static v3.7.2 as broken

requests/open_telm_pro_broken.yml
I filed a bug here: https://github.com/conda-forge/opentelemetry-exporter-prometheus-feedstock/issues/17
And I posted this on zulipchat. [conda-forge.zulipchat.com#narrow/channel/457337-general/topic/Bad.20version.20of.20opentelemetry-exporter-prometheus](https://conda-forge.zulipchat.com/#narrow/channel/457337-general/topic/Bad.20version.20of.20opentelemetry-exporter-prometheus)
A release of opentelemetry-exporter-prometheus was released a while ago with the wrong version of 1.12.0rc1 and it was yanked on PyPI. 
https://github.com/open-telemetry/opentelemetry-python/issues/3521 
The latest is 0.51b0 which has a lower version.
Conda-forge still has the label at latest on this broken old release still as latest because it's higher. This mistaken release is still breaking in conda-forge 2 …
=> Mark bad opentelemetry-exporter-prometheus release as broken

requests/archive-lenskit-subpackages.yml, requests/lenskit-subpackages.yml
We have changed how LensKit is packaged upstream, to release a single PyPI package with extras for add-on dependencies, with the intent to package corresponding meta-packages on conda-forge to activate them (e.g. `lenskit[implicit]` is installed by `lenskit-implicit`), similar to how Ray is packaged.
This request archives the one sub-package that had been packaged for conda-forge, and adds the `lenskit-*` sub-package names as valid outputs from the `lenskit` package (which is building in conda-forge/lenskit-feedstock#18).
I am the feedstock team.
=> Refactor LensKit add-on packages

requests/broken-ipython-900-0.yml
=> mark ipython-9.0.0-*_0 broken

requests/biomechanical-analysis-framework.yaml
In release 0.2.0 (https://github.com/conda-forge/biomechanical-analysis-framework-feedstock/pull/2),  the biomechanical-analysis-framework library added two outputs that it make sense to package as `biomechanical-analysis-framework-python` and `biomechanical-analysis-framework-kpi`.
To handle this request and possible similar modifications in the future, I think it could make sense to allow all the outputs with `biomechanical-analysis-framework-` prefix to `biomechanical-analysis-framework` feedstock, as anyhow the prefix is not ambigous. If instead you prefer that I explicitly list the requested outputs (now `biomechanical-analysis-framework-python` and `biomechanical-analysis-framework-kpi`, and in the future possibly more) I can listed them explicitly, thanks!
ping …
=> Allow multiple outputs that start with biomechanical-analysis-framework- in the biomechanical-analysis-framework recipe

requests/r-geometry-osx-arm64-broken.yml
As reported in https://github.com/conda-forge/r-geometry-feedstock/issues/23, the recently added **osx-arm64** builds were not correctly built. This PR requests affected builds to be marked as broken.
ping @conda-forge/r-geometry
=> Mark r-geometry osx-arm64 builds as broken

requests/rubin-scheduler-broken.yml
I need to mark rubin-scheduler 4.0.0 build 1 broken. 
Previously rubin-scheduler 4.0.0 was already marked broken. 
However, I merged a bot request in the conda-forge feedstock, where going from astropy to astropy-base in the recipe was suggested. 
I agreed with the suggestion, and the file for the PR was marked as pointing to v3.4.0 of rubin-scheduler, so I thought this would be fine -- and I merged it.
Unfortunately, the result was that the broken 4.0.0 package had a new build created, which is NOT marked as broken. 
So please, can we mark 4.0.0 build 1 as broken as well as the original build 0. 
(this does bring up a question I have -- at some point, I'd like to replace 4.0.0 with a new version, when our downstream consumers are ready for 4.0.0. Will I be able to do this?? Ideally 4.0.0 …
=> Mark rubin-scheduler 4.0.0_1 as broken

requests/tiledb.yml
There were multiple tiledb binaries built with fmt 11.1 which is incompatible with spdlog. I tested `linux-64::tiledb-2.27.2-he747b34_1.conda` when the repodata patch (https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/976) was in effect to install it with fmt 11.0. It still failed. Now that the patch was reversed (https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/979), these binaries are uninstallable because the fmt 11.1 binaries were marked as broken (https://github.com/conda-forge/admin-requests/pull/1433).
However, since their pin is `fmt >=11.1.4,<12.0a0`, there is the possibility they could be installed again after future fmt 11.1 releases. And given that the binaries are fundamentally broken, I think the safest option is to mark …
=> Mark as broken tiledb binaries built with fmt 11.1

requests/archive_vllm-nccl-cu12.yml, requests/broken_vllm-nccl.yml
Fixes https://github.com/conda-forge/vllm-nccl-cu12-feedstock/issues/2
`vllm-nccl-cu12` was used to [perform binary redistribution]( https://github.com/vllm-project/vllm-nccl/blob/7bd6f94268858602b42632a010ac44b014ffe4f7/setup.py ) of [the NVIDIA NCCL library]( https://developer.nvidia.com/nccl ) for wheels. However conda-forge does not need this nor should it. Further newer versions of `vllm` do [not need `vllm-nccl-cu12`]( https://github.com/vllm-project/vllm/pull/5091/files ). Hence [the `vllm-nccl` repo was archived]( https://github.com/vllm-project/vllm-nccl )
NVIDIA NCCL supplies [source on GitHub]( https://github.com/NVIDIA/nccl ) under [the BSD-3-Clause license]( https://github.com/NVIDIA/nccl/blob/f44ac759fee12ecb3cc6891e9e739a000f66fd70/LICENSE.txt ). We also build [the NCCL …
=> Archive feedstock & mark broken packages of `vllm-nccl-cu12`

requests/tracy-broken.yml
The name of the tracy package (created by https://github.com/conda-forge/tracy-feedstock/) clashes with the tracy package from bioconda (https://github.com/bioconda/bioconda-recipes/tree/master/recipes/tracy). The package has already been renamed on the conda-forge side (see https://github.com/conda-forge/tracy-feedstock/issues/8#issuecomment-2739698661) but the existing packages built need to be marked as broken so as not to show up in searches.
not technically broken and should not be …
=> Mark tracy package as broken

requests/request-add-feedstock-output.yml
=> add expected outputs for gradient-aware-harmonisation

requests/bcolz.yml
Upstream https://github.com/Blosc/bcolz has been archived for almost 5 years and doesn't support anything past py3.8
There's been no response in https://github.com/conda-forge/bcolz-feedstock/issues/20 for 1.5 years, which is also a good indicator that it's time.
=> archive bcolz

requests/doctr-archive.yml
xref conda-forge/doctr-feedstock#35
I am one of the maintainers of the underlying project (which is no longer developed) and the feedstock (which can be archived).
=> chore: archive doctr-feedstock

requests/tinyxml2-broken.yml
This PR proposes to mark as broken the `tinyxml2` 10.1.0 builds, I was and I am still not sure if it make sense to mark them as broken, but I will explain the rationale for marking them as broken in the following.
Shortly after the release of tinyxml2 10.1.0 on conda-forge, we realized that an ABI breakage was present, even if the run_exports of the package assume ABI compatibility for each major version (see https://github.com/conda-forge/tinyxml2-feedstock/issues/16). Right after that, we proceed in updating the `run_exports` of the package to be more tight (https://github.com/conda-forge/tinyxml2-feedstock/pull/21 and https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/7151), and added an appropriate repodata patch …
=> Mark tinyxml2 10.1.0 builds as broken

requests/libint.yml
After discussion in conda-forge/libint-feedstock#32, we're switching the single output `libint` into something like `libint-c` and `libint` for c/c++ and fortran parts respectively. Obligatory @conda-forge/libint  ping, though I'm the primary active maintainer. This PR is adding a glob because we haven't firmly settled on language names for the split. The nearest unrelated popular package name looks to be `libintl`. Hopefully by claiming `libint-*`, we're not interfering or blocking to other projects, but if you think the claim is too broad, I can make a decision or claim `libint-c`, `libint-cpp`, `libint-fortran` individually.
=> Add libint outputs

requests/flang-rt.yml
This was messed up by the bot between https://github.com/conda-forge/staged-recipes/pull/29582 and the feedstock registration, which ended up ruling out windows completely (needed https://github.com/conda-forge/flang-rt-feedstock/commit/bb26b306dfa516c397ef8cd6ee9452ae38f335fa)
=> allow initial flang-rt outputs

requests/universal_pathlib-add-feedstock-output.yml
ping @conda-forge/universal_pathlib 
This is addressing conda-forge/universal_pathlib-feedstock#45, requesting a meta package `universal-pathlib` to align with pypi behaviour when installing `universal_pathlib`.
=> Add hyphenated output to universal_pathlib feedstock

requests/add_mcpl_outputs.yml
For the incoming release 2.0.0 of MCPL (https://github.com/mctools/mcpl) the `mcpl` package is being split into multiple distinct packages (`mcpl-lib`, `mcpl-core`, `mcpl-python`, `mcpl-extra`) with `mcpl` itself simply becoming a meta-package pulling in all the other packages except `mcpl-extra`. This split reflect the current state and how the package is being split up at PyPI, but might of course be modified somewhat in the future, hence the request for a `mcpl-*` glob pattern to be associated with the mcpl-feedstock.
(I am the maintainer of the mcpl-feedstock repo, so I count myself as having been "pinged").
=> allow multiple outputs in mcpl-feedstock

requests/dagster-cloud-cli-feedstock-output.yml
=> add dagster-cloud-cli output to dagster-feedstock

requests/nurikit-add-output.yml
ping @conda-forge/nurikit
This splits build into python-independent c++ library (libnurikit) and the python bindings (nurikit, previous name).
See conda-forge/nurikit-feedstock#7 and seoklab/nurikit#479, and seoklab/nurikit#481.
=> Add new outputs nurikit-split/libnurikit to nurikit

requests/torchcodec.yaml
In https://github.com/conda-forge/torchcodec-feedstock/pull/5 I added a torchcodec-tests output to the torchcodec feedstock, as originally requested in https://github.com/conda-forge/staged-recipes/pull/29447#discussion_r2019978513 .
To handle this request and possible similar modifications in the future, I think it could make sense to allow all the outputs with `torchcodec-` prefix to `torchcodec` feedstock, as anyhow the prefix is not ambigous. If instead you prefer that I explicitly list the requested outputs (now `torchcoded`, and in the future possibly more) I can listed them explicitly, thanks!
ping @conda-forge/torchcodec (that is actually just me)
=> Allow multiple outputs that start with torchcodec- in the torchcodec feedstock

requests/add-pydantic-evals.yaml
ping @conda-forge/pydantic_ai 
pydantic-ai maintains another package in their [monorepo](https://github.com/pydantic/pydantic-ai), pydantic-evals. I want to add it to the feedstock outputs so we can produce a package for it, like we already do for pydantic-graph and pydantic-ai.
The approval is necessary to merge [this PR](https://github.com/conda-forge/pydantic_ai-feedstock/pull/27).
=> Add pydantic-evals.

requests/opencv-python-headless-broken.yml
As discussed in https://github.com/conda-forge/opencv-python-headless-feedstock/issues/3, the `opencv-python-headless` package is a problematic package that should have not been added in conda-forge in the first place, as the same functionalities are already provided in the `py-opencv` package.
The packages maintainer and staged-recipe reviewers @nilchia and @bgruening agreed in a private mail exchange on doing this, even if it is going to break the `vtp-core` package they mantain on bioconda (see https://github.com/bioconda/bioconda-recipes/blob/e0db9267b2d8b60b377a5c2e8941f696d5090080/recipes/vpt-core/meta.yaml#L41). @hmaarrfk from @conda-forge/core was in the cc in the mail exchange.
fyi @conda-forge/opencv @conda-forge/opencv-python-headless
=> Mark all opencv-python-headless builds as broken

requests/broken.yml
I want to mark the latest `mayavi` build as broken. It wasn't properly tested (which is difficult due to X windowing stuff) and is unusable, see https://github.com/conda-forge/mayavi-feedstock/issues/94 and https://github.com/enthought/mayavi/pull/1345. I am on the maintainer team and merged the problematic build PR, so no need for further ping(s) I think.
=> Mark mayavi build broken

requests/ratter-build-41-osx-64.yml
this is causing a number of v1 mac builds to fail in unfixable ways during download. Since a fix is not immediately forthcoming, mark 0.41 as broken in the meantime. only osx-64 is affected, osx-arm64 is not, nor is linux or windows.
it's unclear what has caused the problem, but tracking upstream: https://github.com/prefix-dev/rattler-build/issues/1608 on. Testing possible fixes in https://github.com/conda-forge/rattler-build-feedstock/pull/153
cc @wolfv
ping @conda-forge/rattler-build
not …
=> mark osx-64 build of rattler-build 0.41 as broken

requests/polars-default.yaml
This PR requests the whitelisting of a new package output `polars-default` for the `polars` feedstock. Currently, the `polars` feedstock already builds `polars`, `polars-lts-cpu` and `polars-u64-idx`. The need and use case for the new `polars-default` output are motivated in [this PR](https://github.com/conda-forge/polars-feedstock/pull/321), which introduces it. The TLDR is that we want to be able to use the `polars` name for a new metapackage to unify the different variants and make it easier for users to switch between the builds.
cc codeowners of the polars feedstock @0xbe7a @Maxyme @borchero @dhirschfeld @pavelzw @ritchie46 @sugatoray @timkpaine @xhochy
instead of …
=> Request new output name `polars-default` for feedstock `polars`

requests/add-apache-airflow-providers-amazon-output.yml
Following up on #1511, adding another extra needed in https://github.com/conda-forge/apache-airflow-providers-amazon-feedstock/pull/70 …
=> Add output apache-airflow-providers-amazon-with-common-messaging

requests/vtk-m-cirun-request.yml
@conda-forge/vtk-m
VTK-m is toolkit for scientific visualization that heavily uses devices adapters such as GPUs to speedup its algorithms. VTK-m build times are very extended due to the heavy use of  metaprogramming in its source code, this is specially true when using CUDA which eventually yields builds exceeding the 6 hours max build time in conda-forge standard CI resources.
I have a PR adding CUDA to VTK-m, however, I cannot merge it since the build times sometime exceeds our 6h allocation. Having more or faster resources would alleviate this.
https://github.com/conda-forge/vtk-m-feedstock/pull/9
We need VTK-m to support CUDA in Conda since it is the only way for VTK and ParaView to support CUDA for its algorithms, since they delegate in VTK-m for GPU accelerated algorithms. This …
=> Request larger runners for VTK-m

requests/add-fasta2a.yaml
ping @conda-forge/pydantic_ai
pydantic-ai maintains another package in their [monorepo](https://github.com/pydantic/pydantic-ai), fasta2a. I want to add it to the feedstock outputs so we can produce a package for it, like we already do for pydantic-graph, pydantic-ai and pydantic-evals.
The approval is necessary to merge https://github.com/conda-forge/pydantic_ai-feedstock/pull/36.
=> Add fasta2a to pydantic-ai.

requests/rattler-build-0.42.0.yml
ping @conda-forge/rattler-build 
Rattler-build 0.42.0 has a serious regression and should be pulled: https://github.com/prefix-dev/rattler-build/issues/1670
=> mark rattler-build 0.42.0 as broken

requests/add-airflow-outputs.yml
Somehow missed in https://github.com/conda-forge/admin-requests/pull/1526
ping @conda-forge/airflow
Needed for https://github.com/conda-forge/airflow-feedstock/pull/148 …
=> Add `airflow-with-all-core` output

requests/broken-mpfun90.yml
Given a bug (c.f. https://github.com/prefix-dev/rattler-build/issues/1685) `osx-64` and `osx-arm64` builds of `mpfun90` (c.f. https://github.com/conda-forge/mpfun90-feedstock/pull/3) had the wrong version number created (https://anaconda.org/conda-forge/mpfun90/files?version=2024.12.6). This has been fixed upstream, but the version numbers that were created do not correspond to any release and could cause problems if they entered into an environment.
not technically broken and should not be …
=> FIX: Mark osx mpfun90 packages with wrong version number as broken

requests/onnxruntime-cirun.yml
Hoping to get https://github.com/conda-forge/onnxruntime-feedstock/pull/145 https://github.com/conda-forge/onnxruntime-feedstock/pull/139
cc: @cbourjau
Windows GPU builds time out due to out of memory. Locally, I've seen my laptop's RAM usage spike to 33GB so i'm hoping that was due to:
1. Too many concurrent compilation
2. Other tasks open
Will try again. but hopefully this can all help move onnxruntime to windows!
I've noticed most of the challenges are due to 1-2 CUDA kernels that take about 1-2 hours to compile...
* Packages with requirements/metadata that are too …
=> Add onnxruntime to the cirun queue

requests/add-fastjet-cxx-python-output.yml
* Allow for the feedstock to become multiouptut and split into producing the C++ only fastjet-cxx output and the FastJet library with Python bindings in the fastjet-cxx-python output.
* Required for https://github.com/conda-forge/fastjet-cxx-feedstock/pull/12
* In some cases where the number …
=> Add separate output for Python bindings to fastjet-cxx feedstock

requests/add-dagster-outputs.yml
=> add dagster outputs create-dagster, dagster-dg-core, dagster-dg-cli

requests/add-some-outputs.yml
=> add names for nvcc and nvshmem

requests/add_fastjet-contrib-split-output.yml
=> add fastjet-contrib-split output to fastjet-contrib

README.md, examples/example-add-feedstock-output.yml
I personally think that we shouldn't use globs ever. They squat on future outputs and can have "unbound" consequences.
Instead, I want to push people to use very specific output names.
Essentially, I want to decrease my mental load when reviewing these PRs.
With the glob, it becomes a "discussion". without the glob, it is SUPER easy.
=> Discourage the use of glob patterns when requesting additional outputs

requests/tsam-broken.yml
Hello, 
I would like to mark tsam 2.3.8 as broken. The following issue has been raised, which was not caught by our test suite:
https://github.com/FZJ-IEK3-VSA/tsam/issues/99
As I am also a feedstock maintainer, there is no need to contact them. I would be very grateful if you could add the 'broken' label quickly and easily.
=> Request to remove tsam 2.3.8

requests/pixi-pycharm-not-executable.yaml
=> Mark pixi-pycharm-0.0.8-unix_hf108a03_1.conda as broken

requests/jupytercad-add-outputs.yml
This is to allow https://github.com/conda-forge/jupytercad-feedstock/issues/23
=> Add outputs for jupytercad

requests/add-fastapi-core-output.yml
In https://github.com/conda-forge/fastapi-feedstock/pull/157 I'm adding an new output `fastapi-core` for FastAPI with no optional dependency. The current `fastapi` output is kept for backwards-compatibility, although it should have been named `fastapi-standard` because it contains the [standard](https://github.com/fastapi/fastapi/blob/cad6880fd97d6f25d3f05025c88230285386e7f9/pyproject.toml#L60-L77) dependencies.
See also https://github.com/conda-forge/fastapi-feedstock/issues/155.
ping @conda-forge/fastapi
=> Add fastapi-core output to fastapi feedstock

requests/dbt-spark.yml
Package is [empty](https://conda-metadata-app.streamlit.app/?q=conda-forge%2Fnoarch%2Fdbt-spark-1.9.2-pyhd8ed1ab_0.conda) (and thus obviously [broken](https://github.com/conda-forge/dbt-spark-feedstock/pull/21)) because tag doesn't [exist](https://github.com/dbt-labs/dbt-spark/tags).
CC @conda-forge/dbt-spark
=> mark dbt-spark v1.9.2 as broken

requests/astra-toolbox-gpu-runner.yml
ASTRA Toolbox is a library of GPU-accelerated tomography primitives making use of CUDA. The main functionality of the toolbox can only be tested on GPU, and we would like to enable it in the CI setup on conda-forge. The build takes ~10 min and the testing phase is ~1 min. I am the maintainer of the feedstock and I'm already added to the access list of open-gpu-server.
=> Enable GPU runner for astra-toolbox-feedstock

requests/add-pyhyperscattering-outputs.yml
Add output names `pyhyperscattering-base` and `pyhyperscattering-gpu` to `pyhyperscattering` for noarch metapackages to better cover pip extras for this package.  
ping @conda-forge/pyhyperscattering (I am the only member at present)
=> Add additional output names to PyHyperScattering for optional dependencies

requests/robotraconteur-add-feedstock-output.yml
After a review of #1587 by @xhochy I have renamed the C++ output package to `librobotraconteur`. This request adds the output name `librobotraconteur` to the feedstock.
I am the owner of the upstream project and the feedstock.
=> Add additional outputs to robotraconteur feedstock

requests/add-duckdb-feedstock-to-ducklake-output.yml
=> Add duckdb-split feedstock to duckdb-extension-ducklake output

requests/gcc.yaml
For https://github.com/conda-forge/ctng-compilers-feedstock/pull/180
=> allow gcc-no-conda-spec output

requests/click-broken.yml
This version has been yanked from PyPI:
https://pypi.org/project/click/#history
See more discussion at:
https://github.com/conda-forge/click-feedstock/issues/55 …
=> Mark click v8.2.2 as broken

requests/broken.yml
It's a new package, first release, but it still had a lot of undiscovered issues. Yanked on PyPI. Small user-base.
ping @conda-forge/formulate
=> Add formulate to broken

requests/fancylog-broken.yml
This PR marks version 0.5.1 of fancylog as broken due to a bug that needs fixing that causes running programs to crash. It has been [yanked on PyPI](https://pypi.org/project/fancylog/0.5.1/). I'm one of the maintainers of the package. 
cc @alessandrofelder, @IgorTatarnikov
=> Add broken fancylog version

requests/pytorch-2-8-0.yml
-----
Accidentally pushed a branch to the wrong remote. I've removed it immediately afterwards, but I didn't notice that CI already started building `osx-arm64` packages, and they got uploaded. I'm sorry for the trouble.
Fixes conda-forge/pytorch-cpu-feedstock#410
ping @conda-forge/pytorch-cpu
=> Request removing accidental upload for pytorch 2.8.0

requests/causal-conv1d.yml
For some reason, this feedstock's output did not get registered at feedstock creation time
=> Fix improperly registered feedstock

requests/xeus-octave-output.yml
* @SylvainCorlay 
* @AntoinePrv 
* @rapgenic
* The package and feedstock have been renamed from `xeus_octave` to `xeus-octave`
* Currently the package `xeus-octave` maps to the **archived** [`xeus_octave-feedstock`](https://github.com/conda-forge/xeus_octave-feedstock). The output must be updated to map to the new [`xeus-octave-feedstock`](https://github.com/conda-forge/xeus-octave-feedstock).
* This PR is a continuation of https://github.com/conda-forge/admin-requests/pull/1628
=> Add xeus-octave output

requests/moor.yaml
The `moar` package was [recently renamed to `moor`](https://github.com/walles/moor/pull/305). I've started working on a PR in the `moar` feedstock to update it, but the `moor` output is required for the CI to finish successfully.
@conda-forge/moar
=> Add moor output to the moar feedstock

requests/onemkl_pkgs.yaml
Add new outputs to intel_repack:
- `mkl-devel-dpcpp` containing MKL SYCL libraries
- `onemkl-sycl-include` containing headers for oneAPI interface of MKL
They are required to build [oneDAL](https://github.com/uxlfoundation/oneDAL) from source using conda recipe with conda-forge packages.
Ping @conda-forge/intel_repack
=> Add new MKL outputs to intel_repack

requests/add-feedstock-output.yml, requests/archive.yml
=> Unify `jupyter-ai` feedstocks

requests/glfw-broken.yml
See https://github.com/conda-forge/glfw-feedstock/issues/26 for the full context.
Basically, upstream glfw 3.5.0 accidentally created a 3.5.0 tag that was not a release, and we actually packaged it. However, that 3.5.0 tag has problems (see https://github.com/pygfx/pygfx/issues/1203), so we need to mark it as broken. 
Existing packages that were built against glfw 3.5.0 will not break due to https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/1083, as we were lucky enough and 3.4 and 3.5.0 basically have exactly the same public headers.
ping @conda-forge/glfw
=> Mark glfw 3.5.0 as broken

requests/mg5amcnlo-pythia8-interface-build-2-broken.yaml
* Variants were incorrectly removed (c.f. https://github.com/conda-forge/mg5amcnlo-pythia8-interface-feedstock/pull/3) and `run_exports` from the pythia8 dependency are breaking the ability to use mg5amcnlo-pythia8-interface with pythia8 v8.311 and v8.312.
- c.f. https://github.com/conda-forge/mg5amcnlo-pythia8-interface-feedstock/pull/4
- c.f. [#general > Properly restirct host dependency without variants?](https://conda-forge.zulipchat.com/#narrow/channel/457337-general/topic/Properly.20restirct.20host.20dependency.20without.20variants.3F/with/541927665)
* Packages …
=> Mark mg5amcnlo-pythia8-interface v1.3.0 build 2 as broken

requests/archive-cuda-11.yml
Migrations are underway for CUDA 12.9 and CUDA 13.0:
https://conda-forge.org/status/migration/?name=cuda129
https://conda-forge.org/status/migration/?name=cuda130
An opt-in migration to keep CUDA 11.8 is available, but no updates will be provided for CUDA 11.x infrastructure.
https://conda-forge.org/status/migration/?name=cuda118
=> Archive CUDA 11 infrastructure packages
